(() => {
  'use strict';
  const $=s=>document.querySelector(s),B=window.BPMLogic,player=$('#bpm-player'),canvas=$('#bpm-wave');
  let context=null,worker=null,generation=0,times=[],timer=0,visual=0,nextBeat=0,beat=0,scheduled=[],mode=null;
  let buffer=null,music=null,position=0,anchorClock=0,anchorPosition=0,wave=null,result=null,gridBpm=120,offset=0,full=false,segment=0,drag=null,playGeneration=0,wantPlay=false;
  const nodes=new Set(),active=()=>location.hash==='#tools/bpm'&&!document.hidden;
  const format=t=>{t=Math.max(0,Number(t)||0);return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');};
  let master=null,clickGain=null,clickBuffers=[],detectedSegments=[],tempoSegments=[],useSegments=false,selectedSegment=0,lastSongScheduled=-Infinity;
  function volumes(){if(!context||!master)return;master.gain.setValueAtTime(Number($('#bpm-volume').value)/100,context.currentTime);clickGain.gain.setValueAtTime(Number($('#bpm-click-volume').value)/100,context.currentTime);}
  async function audio(){if(!context){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('当前浏览器不支持音频处理。');context=new Audio();master=context.createGain();master.connect(context.destination);clickGain=context.createGain();clickGain.connect(master);clickBuffers=[false,true].map(accent=>{const data=B.clickSamples(context.sampleRate,accent),b=context.createBuffer(1,data.length,context.sampleRate);b.getChannelData(0).set(data);return b;});volumes();}await context.resume();if(context.state&&context.state!=='running')throw Error('音频尚未启动，请再点击开始，并检查浏览器的声音权限。');return context;}
  function tempo(){const n=Number($('#bpm-tempo').value);if(!Number.isFinite(n)||n<30||n>300)throw Error('请输入 30–300 之间的 BPM。');return n;}
  function current(){return buffer?Math.max(0,Math.min(buffer.duration,music?anchorPosition+context.currentTime-anchorClock:position)):0;}
  function clearClicks(){for(const o of nodes){try{o.stop();}catch{}}nodes.clear();scheduled=[];}
  function stopClock(){mode=null;clearInterval(timer);cancelAnimationFrame(visual);timer=visual=0;clearClicks();$('#bpm-start').textContent='开始节拍';$('#bpm-beat').classList.remove('pulse');}
  function pauseMusic(){playGeneration++;wantPlay=false;position=current();if(music){const old=music;music=null;old.onended=null;try{old.stop();}catch{}old.disconnect();}if(mode==='song')stopClock();$('#bpm-play').textContent=position>0?'继续试听':'试听';transport();draw();}
  function stop(){pauseMusic();stopClock();player.pause();}
  function clickAt(time,index){const meter=Number($('#bpm-meter').value)||4,accent=((index%meter)+meter)%meter===0,o=context.createBufferSource();o.buffer=clickBuffers[accent?1:0];o.connect(clickGain);o.start(time);nodes.add(o);o.onended=()=>{nodes.delete(o);o.disconnect();};scheduled.push(time);}
  function songGrid(start,end){return useSegments&&tempoSegments.length?B.segmentedGridTimes(tempoSegments,start,end):B.gridTimes(gridBpm,offset,start,end);}
  function primeSong(){if(!music||!context)return;lastSongScheduled=anchorPosition+context.currentTime-anchorClock+.01-1e-7;}
  function scheduler(){if(!mode||!active()){stop();return;}const now=context.currentTime;
    if(mode==='song'){if(!$('#bpm-click-track').checked)return;const start=Math.max(0,anchorPosition+now-anchorClock),end=Math.min(buffer.duration,anchorPosition+now+.12-anchorClock);for(const t of songGrid(start,end)){if(t.time<=lastSongScheduled+1e-7)continue;clickAt(Math.max(now,anchorClock+t.time-anchorPosition),t.index);lastSongScheduled=t.time;}return;}
    let speed;try{speed=tempo();}catch{stopClock();return;}const period=60/speed;
    if(nextBeat<now-.05)nextBeat=now+.03;
    while(nextBeat<now+.12){clickAt(Math.max(now,nextBeat),beat);nextBeat+=period;beat++;}
  }
  function flash(){if(!mode)return;const now=context.currentTime;while(scheduled.length&&scheduled[0]<now-.1)scheduled.shift();$('#bpm-beat').classList.toggle('pulse',scheduled.some(t=>now>=t&&now<t+.085));if(music){transport();if($('#bpm-follow').checked&&!full)segment=Math.min(Math.floor(current()/30),Math.max(0,Math.ceil(buffer.duration/30)-1));draw();}visual=requestAnimationFrame(flash);}
  function clock(kind){mode=kind;scheduler();timer=setInterval(scheduler,25);visual=requestAnimationFrame(flash);}
  function refreshGrid(){if(mode==='song'){clearClicks();primeSong();scheduler();}draw();}
  $('#bpm-start').onclick=async()=>{if(mode==='standalone'){stopClock();return;}try{tempo();await audio();if(!active())return;pauseMusic();stopClock();nextBeat=context.currentTime+.06;beat=0;$('#bpm-start').textContent='停止节拍';clock('standalone');}catch(error){$('#bpm-analysis-status').textContent=error.message;}};
  async function play(){if(!buffer)return;if(music||wantPlay){pauseMusic();return;}const id=++playGeneration;wantPlay=true;try{await audio();if(id!==playGeneration||!active()||!buffer)return;stopClock();if(position>=buffer.duration)position=0;
    const source=context.createBufferSource();source.buffer=buffer;source.connect(master);anchorClock=context.currentTime+.045;anchorPosition=position;music=source;source.onended=()=>{if(music!==source)return;position=buffer.duration;music=null;wantPlay=false;source.disconnect();stopClock();$('#bpm-play').textContent='重新试听';transport();draw();};source.start(anchorClock,position);$('#bpm-play').textContent='暂停试听';primeSong();clock('song');
  }catch(error){if(id===playGeneration)wantPlay=false;$('#bpm-analysis-status').textContent='无法播放：'+error.message;}}
  $('#bpm-play').onclick=play;
  function seek(value){if(!buffer)return;const wasPlaying=!!music||wantPlay;pauseMusic();position=Math.max(0,Math.min(buffer.duration,value));if($('#bpm-follow').checked&&!full)segment=Math.min(Math.floor(position/30),Math.max(0,Math.ceil(buffer.duration/30)-1));transport();draw();if(position>=buffer.duration){$('#bpm-play').textContent='重新试听';return;}if(wasPlaying)play();}
  $('#bpm-seek').oninput=e=>seek(Number(e.target.value));
  function transport(){const p=current(),duration=buffer?.duration||0;$('#bpm-seek').value=String(p);$('#bpm-time').textContent=format(p)+' / '+format(duration);canvas.setAttribute('aria-valuemax',String(duration));canvas.setAttribute('aria-valuenow',p.toFixed(2));canvas.setAttribute('aria-valuetext',format(p));}
  function grid(bpm,ms,ratio=null){if(!Number.isFinite(bpm)||bpm<20||bpm>600||!Number.isFinite(ms)||Math.abs(ms)>3600000){$('#bpm-analysis-status').textContent='BPM 范围为 20–600，偏移范围为 ±3600000 ms。';return false;}bpm=Number(bpm.toFixed(2));ms=Number(ms.toFixed(1));gridBpm=bpm;offset=ms;if(useSegments&&tempoSegments[selectedSegment]){tempoSegments[selectedSegment].bpm=bpm;tempoSegments[selectedSegment].offset=ms;paintSegments();}$('#bpm-result').textContent=bpm.toFixed(2);$('#bpm-offset-result').textContent=ms.toFixed(1);$('#bpm-grid-tempo').value=bpm.toFixed(2);$('#bpm-offset').value=ms.toFixed(1);if(bpm>=30&&bpm<=300)$('#bpm-tempo').value=bpm.toFixed(2);document.querySelectorAll('[data-bpm-ratio]').forEach(b=>b.setAttribute('aria-pressed',String(ratio!==null&&Math.abs(Number(b.dataset.bpmRatio)-ratio)<1e-8)));$('#bpm-grid-note').textContent=(useSegments?'当前第 '+(selectedSegment+1)+' 段，offset 相对于片段起点；':'')+'offset = '+ms.toFixed(1)+' ms；节拍网格之后每 '+(60000/bpm).toFixed(1)+' ms 一拍。自动偏移按一个拍长取模，不代表小节第一拍。';$('#bpm-copy-tempo').disabled=false;$('#bpm-copy-offset').disabled=false;refreshGrid();return true;}
  $('#bpm-grid-tempo').onchange=e=>grid(Number(e.target.value),offset);$('#bpm-offset').onchange=e=>grid(gridBpm,Number(e.target.value));
  document.querySelectorAll('[data-bpm-ratio]').forEach(b=>b.onclick=()=>grid(Number((useSegments?detectedSegments[selectedSegment]?.bpm||120:result?.bpm||120).toFixed(2))*Number(b.dataset.bpmRatio),offset,Number(b.dataset.bpmRatio)));
  document.querySelectorAll('[data-bpm-offset]').forEach(b=>b.onclick=()=>grid(gridBpm,offset+Number(b.dataset.bpmOffset)));
  document.querySelectorAll('[data-bpm-shift]').forEach(b=>b.onclick=()=>grid(gridBpm,offset+Number(b.dataset.bpmShift)*60000/gridBpm));
  $('#bpm-grid-reset').onclick=()=>grid(useSegments?detectedSegments[selectedSegment]?.bpm||120:result?.bpm||120,offset,1);$('#bpm-offset-reset').onclick=()=>grid(gridBpm,useSegments?detectedSegments[selectedSegment]?.offset||0:result?.offset||0);
  $('#bpm-click-track').onchange=()=>refreshGrid();$('#bpm-volume').oninput=e=>{$('#bpm-volume-label').textContent=e.target.value+'%';volumes();};$('#bpm-click-volume').oninput=e=>{$('#bpm-click-volume-label').textContent=e.target.value+'%';volumes();};
  async function copy(value,label){try{await navigator.clipboard.writeText(value);$('#bpm-analysis-status').textContent='已复制 '+label+'：'+value;}catch{$('#bpm-analysis-status').textContent='请从输入框手动复制 '+label+'：'+value;const input=$(label==='BPM'?'#bpm-grid-tempo':'#bpm-offset');input.focus();input.select();}}
  $('#bpm-copy-tempo').onclick=()=>copy(gridBpm.toFixed(2),'BPM');$('#bpm-copy-offset').onclick=()=>copy(offset.toFixed(1),'offset');
  function paintSegments(){const list=$('#bpm-segments-list');list.replaceChildren(...tempoSegments.map((s,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-pressed',String(useSegments&&i===selectedSegment));const strong=document.createElement('strong');strong.textContent=format(s.start)+' – '+format(s.end)+' · '+s.bpm.toFixed(2)+' BPM';const small=document.createElement('small');small.textContent='偏移 '+s.offset.toFixed(1)+' ms · '+(s.confidence>.65?'可信度较高':s.confidence>.3?'需试听校对':'低可信度');b.append(strong,small);b.onclick=()=>{useSegments=true;$('#bpm-use-segments').checked=true;selectedSegment=i;full=false;segment=Math.floor(s.start/30);$('#bpm-follow').checked=false;$('#bpm-window').setAttribute('aria-pressed','true');$('#bpm-full').setAttribute('aria-pressed','false');grid(s.bpm,s.offset);seek(s.start);};return b;}));}
  $('#bpm-use-segments').onchange=e=>{useSegments=e.target.checked;if(useSegments&&tempoSegments[selectedSegment])grid(tempoSegments[selectedSegment].bpm,tempoSegments[selectedSegment].offset);else grid(result?.bpm||120,result?.offset||0,1);paintSegments();};
  $('#bpm-copy-segments').onclick=async()=>{const data=tempoSegments.map(s=>({start:Number(s.start.toFixed(3)),end:Number(s.end.toFixed(3)),bpm:Number(s.bpm.toFixed(3)),offsetMs:Number(s.offset.toFixed(1))})),text=JSON.stringify(data,null,2);try{await navigator.clipboard.writeText(text);$('#bpm-analysis-status').textContent='已复制分段 BPM 与偏移。';}catch{$('#bpm-analysis-status').textContent='浏览器不允许复制，请查看分段结果。';}};
  function bounds(){const duration=buffer?.duration||30,start=full?0:segment*30;return {start,end:full?duration:Math.min(duration,start+30)};}
  function draw(){const {start,end}=bounds(),width=Math.max(1,canvas.getBoundingClientRect().width||720),height=160,dpr=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.round(width*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);}const ctx=canvas.getContext('2d');if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);
    $('#bpm-window-time').textContent=format(start)+' – '+format(end);$('#bpm-segment').textContent=buffer?(full?'全曲':'片段 '+(segment+1)+' / '+Math.ceil(buffer.duration/30)):'等待音频';$('#bpm-prev').disabled=!buffer||full||segment===0;$('#bpm-next').disabled=!buffer||full||end>=buffer.duration;$('#bpm-wave-empty').hidden=!!buffer;
    if(!buffer||!wave||end<=start)return;const x=t=>(t-start)/(end-start)*width;ctx.strokeStyle='#a6c8b536';ctx.beginPath();ctx.moveTo(0,height*.5);ctx.lineTo(width,height*.5);ctx.stroke();ctx.fillStyle='#a7c6b97d';
    for(let px=0;px<width;px+=3){const a=Math.floor((start+px/width*(end-start))*200),b=Math.min(wave.length,Math.ceil((start+(px+3)/width*(end-start))*200));let amplitude=0;for(let i=a;i<b;i++)amplitude=Math.max(amplitude,wave[i]||0);const h=Math.max(1,Math.sqrt(amplitude)*106);ctx.fillRect(px,height*.5-h/2,2,h);}
    const stride=Math.max(1,Math.ceil(4*(end-start)/(width*60/gridBpm)));for(const t of songGrid(start,end)){if(t.index%stride!==0)continue;ctx.strokeStyle=t.index%4===0?'#e8d7a8dd':'#a7cdbc75';ctx.lineWidth=t.index%4===0?1.5:1;ctx.beginPath();ctx.moveTo(x(t.time),12);ctx.lineTo(x(t.time),height-12);ctx.stroke();}
    if(useSegments)for(const s of tempoSegments){if(s.start<=start||s.start>=end)continue;ctx.strokeStyle='#dfad8277';ctx.beginPath();ctx.moveTo(x(s.start),0);ctx.lineTo(x(s.start),height);ctx.stroke();ctx.fillStyle='#e5c6a0';ctx.fillText(s.bpm.toFixed(1),Math.min(width-45,x(s.start)+4),height-5);}
    ctx.fillStyle='#b8d0c8';ctx.font='11px sans-serif';ctx.fillText(format(start),8,14);ctx.fillText(format(end),Math.max(8,width-42),14);const p=current();if(p>=start&&p<=end){ctx.strokeStyle='#f1dfb9';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x(p),0);ctx.lineTo(x(p),height);ctx.stroke();}
  }
  $('#bpm-window').onclick=()=>{full=false;$('#bpm-window').setAttribute('aria-pressed','true');$('#bpm-full').setAttribute('aria-pressed','false');draw();};$('#bpm-full').onclick=()=>{full=true;$('#bpm-window').setAttribute('aria-pressed','false');$('#bpm-full').setAttribute('aria-pressed','true');draw();};
  for(const [id,delta]of [['prev',-1],['next',1]])$('#bpm-'+id).onclick=()=>{if(!buffer)return;segment=Math.max(0,Math.min(Math.ceil(buffer.duration/30)-1,segment+delta));$('#bpm-follow').checked=false;draw();};$('#bpm-follow').onchange=()=>{if(buffer&&$('#bpm-follow').checked)segment=Math.min(Math.floor(current()/30),Math.ceil(buffer.duration/30)-1);draw();};
  canvas.addEventListener('pointerdown',e=>{if(!buffer||e.button!==0)return;const rect=canvas.getBoundingClientRect(),view=bounds();drag={id:e.pointerId,x:e.clientX,offset,rect,view,moved:false,follow:$('#bpm-follow').checked};canvas.setPointerCapture(e.pointerId);});
  canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x;if(Math.abs(dx)>4)drag.moved=true;if(drag.moved){$('#bpm-follow').checked=false;grid(gridBpm,drag.offset+dx/drag.rect.width*(drag.view.end-drag.view.start)*1000);}});
  canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;if(!d.moved)seek(d.view.start+Math.max(0,Math.min(1,(e.clientX-d.rect.left)/d.rect.width))*(d.view.end-d.view.start));else $('#bpm-follow').checked=d.follow;});canvas.addEventListener('pointercancel',()=>{if(drag)$('#bpm-follow').checked=drag.follow;drag=null;});
  canvas.addEventListener('keydown',e=>{if(!buffer)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();if(e.shiftKey)grid(gridBpm,offset+(e.key==='ArrowRight'?1:-1));else seek(current()+(e.key==='ArrowRight'?1:-1));}});
  if(window.ResizeObserver)new ResizeObserver(()=>{if(active())draw();}).observe(canvas);window.addEventListener('resize',()=>{if(active())draw();});
  function tap(now=performance.now()){if(times.length&&now-times.at(-1)>2500)times=[];if(times.length&&now-times.at(-1)<100)return;times.push(now);if(times.length>32)times.shift();const r=B.taps(times);$('#bpm-tap-status').textContent=r?'已敲击 '+r.count+' 次 · 稳定度 '+Math.round(r.stability*100)+'%':'已敲击 '+times.length+' 次，还需 '+Math.max(0,4-times.length)+' 次';if(r){$('#bpm-tap-result').textContent=r.bpm.toFixed(1);if(r.bpm>=30&&r.bpm<=300)$('#bpm-tempo').value=r.bpm.toFixed(1);}}
  $('#bpm-tap').addEventListener('pointerdown',e=>{if(e.button!==0)return;const now=performance.now();tap(Math.abs(e.timeStamp-now)<1000?e.timeStamp:now);});$('#bpm-tap').addEventListener('click',e=>{if(e.detail===0)tap();});$('#bpm-tap').addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(!e.repeat)tap();}});$('#bpm-tap-reset').onclick=()=>{times=[];$('#bpm-tap-result').textContent='—';$('#bpm-tap-status').textContent='至少敲击 4 次；多敲几拍可提高稳定性。';};
  $('#bpm-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;const id=++generation;worker?.terminate();worker=null;stop();buffer=null;wave=null;result=null;tempoSegments=[];detectedSegments=[];useSegments=false;selectedSegment=0;$('#bpm-segments-panel').hidden=true;$('#bpm-use-segments').checked=false;position=segment=0;gridBpm=120;offset=0;$('#bpm-result').textContent=$('#bpm-offset-result').textContent='—';$('#bpm-candidates').replaceChildren();$('#bpm-variation').hidden=true;for(const key of ['play','seek','copy-tempo','copy-offset'])$('#bpm-'+key).disabled=true;$('#bpm-analysis-status').textContent='正在解码音频…';draw();
    try{if(file.size>60*1024*1024)throw Error('请使用 60 MB 以内的音频。');const ctx=await audio();if(id!==generation)return;const decoded=await ctx.decodeAudioData(await file.arrayBuffer());if(id!==generation)return;if(decoded.duration<6||decoded.duration>600)throw Error('请选择 6 秒至 10 分钟的音频。');buffer=decoded;const channels=Array.from({length:buffer.numberOfChannels},(_,c)=>buffer.getChannelData(c)),rate=11025,seconds=buffer.duration,samples=new Float32Array(Math.floor(seconds*rate)),ratio=buffer.sampleRate/rate;
      wave=new Float32Array(Math.ceil(buffer.duration*200));const waveStep=Math.max(1,Math.floor(buffer.sampleRate/16000));for(let i=0;i<channels[0].length;i+=waveStep){const j=Math.min(wave.length-1,Math.floor(i/buffer.sampleRate*200));for(const channel of channels)wave[j]=Math.max(wave[j],Math.abs(channel[i]));}
      for(let i=0;i<samples.length;i++){const start=Math.floor(i*ratio),end=Math.max(start+1,Math.floor((i+1)*ratio));let sum=0;for(const channel of channels)for(let k=start;k<end&&k<channel.length;k++)sum+=channel[k];samples[i]=sum/((end-start)*channels.length);}
      $('#bpm-play').disabled=$('#bpm-seek').disabled=false;$('#bpm-seek').max=String(buffer.duration);$('#bpm-seek').value='0';$('#bpm-grid-tempo').value='120';$('#bpm-offset').value='0';$('#bpm-play').textContent='试听';transport();draw();$('#bpm-analysis-status').textContent='正在分析 '+Math.round(seconds)+' 秒的节奏与偏移…';worker=new Worker('bpm-worker.js?v=b07486e76029');worker.onmessage=({data})=>{if(id!==generation)return;worker.terminate();worker=null;if(data.error){$('#bpm-analysis-status').textContent=data.error+' 可以手动输入 BPM 与偏移。';return;}result=data.result;detectedSegments=(result.segments||[]).filter(s=>Number.isFinite(s.end)&&Number.isFinite(s.offset)).map(s=>({...s}));tempoSegments=detectedSegments.map(s=>({...s}));useSegments=!!result.variable&&tempoSegments.length>1;selectedSegment=0;$('#bpm-use-segments').checked=useSegments;$('#bpm-segments-panel').hidden=!tempoSegments.length;grid(useSegments?tempoSegments[0].bpm:result.bpm,useSegments?tempoSegments[0].offset:result.offset,1);paintSegments();$('#bpm-analysis-status').textContent=file.name+' · 节奏可信程度：'+(result.confidence>.65?'较高':result.confidence>.3?'中等':'较低')+' · '+result.beats+' 个明显起音。'+(result.offsetConfidence<.5?' 偏移可信程度较低，请试听微调。':' 请试听确认拍点。');$('#bpm-variation').hidden=!result.variable;$('#bpm-variation').textContent='检测到 BPM 变化，已划分 '+tempoSegments.length+' 个片段并启用分段节拍网格。请试听确认变速边界。';$('#bpm-candidates').replaceChildren(...result.candidates.map(c=>{const b=document.createElement('button');b.className='button secondary';b.textContent=c.bpm.toFixed(2)+' BPM';b.onclick=()=>grid(c.bpm,offset);return b;}));};worker.onerror=()=>{if(id===generation){$('#bpm-analysis-status').textContent='分析未完成，可以手动输入 BPM 与偏移，或重新选择音频。';worker?.terminate();worker=null;}};worker.postMessage({samples,rate},[samples.buffer]);
    }catch(error){if(id===generation)$('#bpm-analysis-status').textContent='无法分析：'+error.message;}
  };
  function leave(){if(active()){draw();return;}stop();if(worker){worker.terminate();worker=null;$('#bpm-analysis-status').textContent='已停止分析，可重新选择音频。';}generation++;drag=null;}
  window.addEventListener('hashchange',leave);document.addEventListener('visibilitychange',leave);window.addEventListener('pagehide',()=>{stop();worker?.terminate();worker=null;generation++;});transport();draw();
})();
