(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f();else r.BPMLogic=f();})(typeof globalThis!=='undefined'?globalThis:this,()=>{
  const median=a=>{const v=a.slice().sort((a,b)=>a-b);return v.length?(v[Math.floor((v.length-1)/2)]+v[Math.ceil((v.length-1)/2)])/2:0;};
  function taps(times){if(times.length<4)return null;const intervals=times.slice(1).map((t,i)=>t-times[i]),mid=median(intervals),filtered=intervals.filter(t=>Math.abs(t-mid)<mid*.2);if(filtered.length<3||mid<=0)return null;const period=filtered.reduce((a,b)=>a+b,0)/filtered.length,spread=Math.sqrt(filtered.reduce((a,b)=>a+(b-period)**2,0)/filtered.length)/period;return {bpm:60000/period,stability:Math.max(0,1-spread*6),count:times.length};}
  function fft(re,im){const n=re.length;for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]];}}for(let len=2;len<=n;len<<=1){const angle=-2*Math.PI/len,wr=Math.cos(angle),wi=Math.sin(angle);for(let i=0;i<n;i+=len){let ur=1,ui=0;for(let j=0;j<len/2;j++){const a=i+j,b=a+len/2,vr=re[b]*ur-im[b]*ui,vi=re[b]*ui+im[b]*ur;re[b]=re[a]-vr;im[b]=im[a]-vi;re[a]+=vr;im[a]+=vi;const next=ur*wr-ui*wi;ui=ur*wi+ui*wr;ur=next;}}}}
  function gridTimes(bpm,offsetMs,start,end){if(!Number.isFinite(bpm)||bpm<=0||!Number.isFinite(offsetMs)||end<=start)return [];const period=60/bpm,offset=offsetMs/1000,first=Math.ceil((start-offset)/period-1e-9),last=Math.floor((end-offset)/period+1e-9),out=[];for(let i=first;i<=last&&out.length<12000;i++)out.push({time:offset+i*period,index:i});return out;}
  function alignment(samples,rate,peaks,bpm){
    const period=60/bpm,width=Math.max(4,Math.round(rate*.004)),prefix=new Float64Array(samples.length+1);for(let i=0;i<samples.length;i++)prefix[i+1]=prefix[i]+Math.abs(samples[i]);
    // Locate each attack in sample time; spectral flux frames begin before the actual transient.
    const onsets=peaks.map(p=>{let at=0,best=-Infinity;for(let i=Math.max(width,Math.floor((p.time-.015)*rate));i<Math.min(samples.length-width,Math.ceil((p.time+.1)*rate));i++){const rise=prefix[i+width]-2*prefix[i]+prefix[i-width];if(rise>best){best=rise;at=i;}}return {time:at/rate,weight:p.weight};});
    let cos=0,sin=0,total=0;for(const p of onsets){const a=p.time/period*2*Math.PI;cos+=Math.cos(a)*p.weight;sin+=Math.sin(a)*p.weight;total+=p.weight;}let phase=((Math.atan2(sin,cos)/(2*Math.PI))%1+1)%1*period;
    const aligned=onsets.filter(p=>Math.abs(((p.time-phase+period/2)%period+period)%period-period/2)<period*.15);if(aligned.length){const residual=median(aligned.map(p=>((p.time-phase+period/2)%period+period)%period-period/2));phase=((phase+residual)%period+period)%period;}
    const segments=[];for(let start=0;start<samples.length/rate;start+=12){const local=onsets.filter(p=>p.time>=start&&p.time<start+12),intervals=[];for(let i=1;i<local.length;i++){const gap=local[i].time-local[i-1].time,k=Math.round(gap/period);if(k>0&&Math.abs(gap/k-period)<period*.15)intervals.push(gap/k);}if(intervals.length>=5)segments.push({start,bpm:60/median(intervals)});}
    const speeds=segments.map(s=>s.bpm),variable=speeds.length>1&&(Math.max(...speeds)-Math.min(...speeds))/bpm>.025;
    return {offset:phase*1000,offsetConfidence:Math.hypot(cos,sin)/(total||1),variable,segments};
  }
  function analyze(samples,rate){
    if(!samples||samples.length<rate*6)throw Error('请使用至少 6 秒的音频。');const n=1024,hop=128,hz=rate/hop,count=Math.floor((samples.length-n)/hop),flux=new Float64Array(count),previous=new Float64Array(n/2),re=new Float64Array(n),im=new Float64Array(n),window=Float64Array.from({length:n},(_,i)=>.5-.5*Math.cos(2*Math.PI*i/(n-1)));let peak=0;
    for(let f=0;f<count;f++){for(let i=0;i<n;i++){re[i]=samples[f*hop+i]*window[i];im[i]=0;}fft(re,im);let value=0;for(let k=3;k<n/2;k++){const mag=Math.log1p(Math.hypot(re[k],im[k])*10);value+=Math.max(0,mag-previous[k])*(k*rate/n<250?1.6:1);previous[k]=mag;}flux[f]=value;peak=Math.max(peak,value);}
    if(peak<.001)throw Error('没有检测到足够的节奏信息。');const env=new Float64Array(count);for(let i=0;i<count;i++){let sum=0;for(let j=Math.max(0,i-8);j<=Math.min(count-1,i+8);j++)sum+=flux[j];env[i]=Math.max(0,flux[i]-sum/Math.min(17,count)*.65);}
    const peaks=[];for(let i=2;i<count-2;i++)if(env[i]>peak*.035&&env[i]>=env[i-1]&&env[i]>env[i+1]&&env[i]>=env[i-2]&&env[i]>=env[i+2]){const correction=.5*(env[i-1]-env[i+1])/(env[i-1]-2*env[i]+env[i+1]||1),p={time:(i+Math.max(-.5,Math.min(.5,correction)))/hz,weight:Math.sqrt(env[i])};if(peaks.length&&p.time-peaks.at(-1).time<.16){if(p.weight>peaks.at(-1).weight)peaks[peaks.length-1]=p;}else peaks.push(p);}
    if(peaks.length<6)throw Error('明显拍点过少，请换一段节奏更清晰的音频。');
    const minLag=Math.floor(hz*60/240),maxLag=Math.ceil(hz*60/40),corr=[];
    for(let lag=minLag;lag<=maxLag;lag++){let xy=0,xx=0,yy=0;for(let i=lag;i<count;i++){xy+=env[i]*env[i-lag];xx+=env[i]*env[i];yy+=env[i-lag]*env[i-lag];}corr[lag]=xy/Math.sqrt(xx*yy||1);}
    const candidates=[];for(let lag=minLag+1;lag<maxLag;lag++){if(corr[lag]<corr[lag-1]||corr[lag]<corr[lag+1])continue;const offset=.5*(corr[lag-1]-corr[lag+1])/(corr[lag-1]-2*corr[lag]+corr[lag+1]||1);let period=(lag+Math.max(-.5,Math.min(.5,offset)))/hz;
      for(let pass=0;pass<2;pass++){let sum=0,weight=0;for(let i=0;i<peaks.length;i++)for(let j=i+1;j<peaks.length&&peaks[j].time-peaks[i].time<6;j++){const gap=peaks[j].time-peaks[i].time,k=Math.round(gap/period);if(k>0&&Math.abs(gap-k*period)<Math.min(.045,period*.1)){const w=Math.min(peaks[i].weight,peaks[j].weight)*k;sum+=gap/k*w;weight+=w;}}if(weight)period=sum/weight;}
      const bpm=60/period;if(bpm<40||bpm>240)continue;let cos=0,sin=0,weight=0;for(const p of peaks){const a=2*Math.PI*p.time/period;cos+=Math.cos(a)*p.weight;sin+=Math.sin(a)*p.weight;weight+=p.weight;}const coherence=Math.hypot(cos,sin)/weight;const score=corr[lag]*.7+coherence*.3;candidates.push({bpm,score,coherence});}
    candidates.sort((a,b)=>b.score-a.score);if(!candidates.length||candidates[0].score<.08)throw Error('节奏不够稳定，建议使用手动敲击测速。');const top=candidates[0].score,near=candidates.filter(c=>c.score>=top*.92);near.sort((a,b)=>b.bpm-a.bpm);const best=near[0],alternatives=[best,...candidates].filter((v,i,a)=>a.findIndex(o=>Math.abs(o.bpm-v.bpm)<1)===i).slice(0,4);
    return {bpm:best.bpm,confidence:Math.max(0,Math.min(1,best.score)),candidates:alternatives.map(c=>({bpm:c.bpm,score:c.score})),beats:peaks.length,duration:samples.length/rate,...alignment(samples,rate,peaks,best.bpm)};
  }
  return {analyze,taps,gridTimes};
});
