(() => {
  'use strict';const $=s=>document.querySelector(s),L=window.CadLogic,canvas=$('#cad-canvas'),ctx=canvas.getContext('2d');
  let objects=[],selected=-1,undo=[],redo=[],zoom=1.5,pan={x:0,y:0},drag=null,pending=[],cursor={x:0,y:0},width=800,height=420;
  let nativeContext=null,busy=false,worker=null,requestId=0;const requests=new Map();
  const clone=x=>JSON.parse(JSON.stringify(x)),mode=()=>$('#cad-mode').value;
  function download(text,type,name){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
  function snapshot(previous=objects){return {objects:clone(previous),context:nativeContext,unit:$('#cad-unit').value};}
  function checkpoint(previous=objects){undo.push(snapshot(previous));if(undo.length>60)undo.shift();redo=[];}
  function resetWorker(message){worker?.terminate();worker=null;for(const item of requests.values()){clearTimeout(item.timer);item.reject(Error(message));}requests.clear();}
  function rpc(action,data){if(!worker){if(!window.Worker)throw Error('此浏览器不支持后台 DWG 处理，请使用新版浏览器');worker=new Worker(new URL('cad-dwg-worker.js?v=1f4cf8e313bc',document.baseURI),{type:'module'});worker.onmessage=e=>{const item=requests.get(e.data.id);if(!item)return;requests.delete(e.data.id);clearTimeout(item.timer);e.data.error?item.reject(Error(e.data.error)):item.resolve(e.data.result);};worker.onerror=e=>{e.preventDefault();resetWorker('DWG 模块加载失败，请确认使用 HTTPS 或 localhost，刷新页面后重试');};}return new Promise((resolve,reject)=>{const id=++requestId,timer=setTimeout(()=>resetWorker('图纸处理超过 40 秒，已停止。请拆分或简化图纸后重试。'),40000);requests.set(id,{resolve,reject,timer});worker.postMessage({id,action,data});});}
  async function runCad(message,fn){if(busy)return;busy=true;const controls=[...document.querySelectorAll('#tool-cad button,#tool-cad input,#tool-cad select')].map(e=>[e,e.disabled]);controls.forEach(([e])=>e.disabled=true);canvas.setAttribute('aria-busy','true');$('#cad-status').textContent=message;try{await fn();}catch(e){$('#cad-status').textContent=e.message;}finally{busy=false;canvas.removeAttribute('aria-busy');controls.forEach(([e,disabled])=>e.disabled=disabled);properties();render();}}
  function setUnit(unit){const select=$('#cad-unit'),value=String(unit??0);if(![...select.options].some(o=>o.value===value)){const option=document.createElement('option');option.value=value;option.textContent='原图单位（代码 '+value+'）';select.append(option);}select.value=value;}
  function nativeInfo(){const summary=$('#cad-native-summary'),box=$('#cad-dwg-notices'),list=$('#cad-dwg-notice-list');summary.textContent=nativeContext?'原图 '+nativeContext.meta.version+' · '+nativeContext.meta.total+' 个模型实体 · '+nativeContext.meta.retained+' 个只读保留实体。文字、图块、曲线和三维内容作为只读背景；保存时保留原图层和受支持的图纸数据。':'可绘制二维图形，也可导入 DWG 图纸进行编辑。';list.replaceChildren();for(const text of nativeContext?.meta.warnings??[]){const li=document.createElement('li');li.textContent=text;list.append(li);}box.hidden=!list.children.length;}
  async function contextFrom(data,name){let background=null;const warnings=[...data.warnings];if(data.background){const image=new Image(),url=URL.createObjectURL(new Blob([data.background.svg],{type:'image/svg+xml'}));try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('只读图形预览无法显示，但已保留图纸数据'));image.src=url;});background={...data.background,image};}catch(e){warnings.push(e.message);}finally{URL.revokeObjectURL(url);}}return {source:data.source,background,name:name.replace(/\.[^.]+$/,'').replace(/[\\/:*?"<>|]/g,'_').slice(0,100)||'drawing',meta:{version:data.version,total:data.total,retained:data.retained,warnings}};}
  function exportData(format){return rpc('save',{source:nativeContext?.source||null,objects,unit:Number($('#cad-unit').value),format,version:$('#cad-dwg-version').value});}
  function position(e,snap=true){const rect=canvas.getBoundingClientRect();let p={x:(e.clientX-rect.left-width/2-pan.x)/zoom,y:-(e.clientY-rect.top-height/2-pan.y)/zoom};if(snap&&$('#cad-snap').checked){const grid=Number($('#cad-grid').value);if(grid>0&&grid<=10000)p={x:Math.round(p.x/grid)*grid,y:Math.round(p.y/grid)*grid};}return p;}
  function move(o,dx,dy){if(o.points)o.points.forEach(p=>{p.x+=dx;p.y+=dy;});else{o.cx+=dx;o.cy+=dy;}}
  function drawObject(o,chosen=false){ctx.strokeStyle=chosen?'#207c91':o.color;ctx.lineWidth=(chosen?2.5:o.width)/zoom;ctx.beginPath();if(o.type==='circle')ctx.arc(o.cx,o.cy,o.r,0,Math.PI*2);else if(o.type==='arc'){let sweep=(o.end-o.start)%360;if(sweep<=0)sweep+=360;const start=(o.start%360)*Math.PI/180;ctx.arc(o.cx,o.cy,o.r,start,start+sweep*Math.PI/180);}else{o.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(o.closed)ctx.closePath();}ctx.stroke();}
  function render(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);const ratio=canvas.width/width;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle='#fafbf6';ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(width/2+pan.x,height/2+pan.y);ctx.scale(zoom,-zoom);
    let step=Number($('#cad-grid').value);if(!Number.isFinite(step)||step<=0||step>10000)step=10;while(step*zoom<15)step*=2;const left=(-width/2-pan.x)/zoom,right=(width/2-pan.x)/zoom,bottom=(-height/2+pan.y)/zoom,top=(height/2+pan.y)/zoom;
    ctx.strokeStyle='#8eaaa522';ctx.lineWidth=1/zoom;ctx.beginPath();for(let x=Math.ceil(left/step)*step;x<=right;x+=step){ctx.moveTo(x,bottom);ctx.lineTo(x,top);}for(let y=Math.ceil(bottom/step)*step;y<=top;y+=step){ctx.moveTo(left,y);ctx.lineTo(right,y);}ctx.stroke();ctx.strokeStyle='#72958a66';ctx.beginPath();ctx.moveTo(0,bottom);ctx.lineTo(0,top);ctx.moveTo(left,0);ctx.lineTo(right,0);ctx.stroke();const bg=nativeContext?.background;if(bg){ctx.save();ctx.scale(1,-1);ctx.drawImage(bg.image,bg.x,bg.y,bg.w,bg.h);ctx.restore();}objects.forEach((o,i)=>drawObject(o,i===selected));
    if(pending.length)drawObject({type:'polyline',points:[...pending,cursor],color:$('#cad-color').value,width:1});
    if(drag&&['line','circle','rect'].includes(drag.mode)){const preview=shape(drag.start,cursor,drag.mode);if(preview)drawObject(preview);}
    ctx.restore();$('#cad-cursor').textContent='X '+cursor.x.toFixed(2)+' · Y '+cursor.y.toFixed(2)+' · 缩放 '+Math.round(zoom*100)+'% · '+objects.length+' 个对象';$('#cad-undo').disabled=busy||!undo.length;$('#cad-redo').disabled=busy||!redo.length;$('#cad-delete').disabled=busy||selected<0;}
  function shape(a,b,type){const style={color:$('#cad-color').value,width:1};if(type==='circle'){const r=Math.hypot(b.x-a.x,b.y-a.y);return r>.001?{...style,type:'circle',cx:a.x,cy:a.y,r}:null;}if(Math.hypot(b.x-a.x,b.y-a.y)<.001)return null;if(type==='rect'){if(a.x===b.x||a.y===b.y)return null;return {...style,type:'polyline',closed:true,points:[a,{x:b.x,y:a.y},b,{x:a.x,y:b.y}]};}return {...style,type:'line',points:[a,b]};}
  function properties(){const o=objects[selected];$('#cad-selected').textContent=o?'已选择第 '+(selected+1)+' 个对象（'+({line:'线段',polyline:'多段线',circle:'圆',arc:'圆弧'}[o.type])+'）':'请选择一个对象。';for(const id of ['cad-x','cad-y','cad-width'])$('#'+id).disabled=!o;for(const id of ['cad-x2','cad-y2'])$('#'+id).disabled=o?.type!=='line';$('#cad-radius').disabled=!['circle','arc'].includes(o?.type);for(const id of ['cad-angle-start','cad-angle-end'])$('#'+id).disabled=o?.type!=='arc';$('#cad-apply').disabled=!o;
    if(o){const p=o.points?.[0]||{x:o.cx,y:o.cy};$('#cad-x').value=p.x;$('#cad-y').value=p.y;$('#cad-width').value=o.width;$('#cad-color').value=o.color;$('#cad-x2').value=o.type==='line'?o.points[1].x:'';$('#cad-y2').value=o.type==='line'?o.points[1].y:'';$('#cad-radius').value=o.r??'';$('#cad-angle-start').value=o.start??'';$('#cad-angle-end').value=o.end??'';}}
  function hit(p){const tolerance=8/zoom;function segment(a,b){const dx=b.x-a.x,dy=b.y-a.y,div=dx*dx+dy*dy,t=div?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/div)):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)<tolerance;}
    for(let i=objects.length-1;i>=0;i--){const o=objects[i];if(o.type==='circle'&&Math.abs(Math.hypot(p.x-o.cx,p.y-o.cy)-o.r)<tolerance)return i;if(o.type==='arc'){let angle=(Math.atan2(p.y-o.cy,p.x-o.cx)*180/Math.PI+360)%360,start=(o.start%360+360)%360,end=(o.end%360+360)%360;if(end<=start)end+=360;if(angle<start)angle+=360;if(angle<=end&&Math.abs(Math.hypot(p.x-o.cx,p.y-o.cy)-o.r)<tolerance)return i;}if(o.points){for(let j=1;j<o.points.length;j++)if(segment(o.points[j-1],o.points[j]))return i;if(o.closed&&segment(o.points[o.points.length-1],o.points[0]))return i;}}return -1;}
  canvas.addEventListener('pointerdown',e=>{if(busy||e.button!==0)return;e.preventDefault();canvas.focus();cursor=position(e);const m=mode();if(m==='polyline'){if(pending.length>=10000)return;if(!pending.length||Math.hypot(cursor.x-pending[pending.length-1].x,cursor.y-pending[pending.length-1].y)>.001)pending.push({...cursor});render();return;}if(m==='select'){selected=hit(position(e,false));properties();}drag={mode:m,start:{...cursor},pixel:{x:e.clientX,y:e.clientY},pan:{...pan},before:clone(objects),object:selected>=0?clone(objects[selected]):null};canvas.setPointerCapture(e.pointerId);render();});
  canvas.addEventListener('pointermove',e=>{if(busy)return;cursor=position(e);if(drag){if(drag.mode==='pan')pan={x:drag.pan.x+e.clientX-drag.pixel.x,y:drag.pan.y+e.clientY-drag.pixel.y};else if(drag.mode==='select'&&drag.object){objects[selected]=clone(drag.object);move(objects[selected],cursor.x-drag.start.x,cursor.y-drag.start.y);properties();}}render();});
  canvas.addEventListener('pointerup',()=>{if(busy||!drag)return;if(['line','circle','rect'].includes(drag.mode)){const o=shape(drag.start,cursor,drag.mode);if(o){if(objects.length>=2000){$('#cad-status').textContent='最多 2000 个对象。';drag=null;render();return;}checkpoint();objects.push(o);selected=objects.length-1;}}else if(drag.mode==='select'&&JSON.stringify(objects)!==JSON.stringify(drag.before))checkpoint(drag.before);drag=null;properties();render();});
  canvas.addEventListener('pointercancel',()=>{if(drag){objects=drag.before;drag=null;properties();render();}});
  function zoomAt(factor,px=width/2,py=height/2){const ox=(px-width/2-pan.x)/zoom,oy=(py-height/2-pan.y)/zoom;zoom=Math.max(1e-7,Math.min(100,zoom*factor));pan={x:px-width/2-ox*zoom,y:py-height/2-oy*zoom};render();}
  canvas.addEventListener('wheel',e=>{e.preventDefault();const rect=canvas.getBoundingClientRect();zoomAt(e.deltaY<0?1.15:1/1.15,e.clientX-rect.left,e.clientY-rect.top);},{passive:false});
  function finish(){if(busy)return;if(pending.length<2){pending=[];render();return;}if(objects.length>=2000){$('#cad-status').textContent='最多 2000 个对象。';return;}checkpoint();objects.push({type:'polyline',points:clone(pending),closed:false,color:$('#cad-color').value,width:1});selected=objects.length-1;pending=[];properties();render();}
  $('#cad-finish').onclick=finish;canvas.addEventListener('dblclick',()=>{if(mode()==='polyline')finish();});$('#cad-mode').onchange=()=>{pending=[];drag=null;render();};
  function undoRedo(isRedo){if(busy)return;const source=isRedo?redo:undo,target=isRedo?undo:redo;if(!source.length)return;target.push(snapshot());const previous=source.pop(),changedContext=previous.context!==nativeContext;objects=previous.objects;nativeContext=previous.context;setUnit(previous.unit);selected=-1;pending=[];nativeInfo();properties();changedContext?fit():render();}
  $('#cad-undo').onclick=()=>undoRedo(false);$('#cad-redo').onclick=()=>undoRedo(true);$('#cad-delete').onclick=()=>{if(busy||selected<0)return;checkpoint();objects.splice(selected,1);selected=-1;properties();render();};$('#cad-clear').onclick=()=>{if(busy)return;checkpoint();objects=[];nativeContext=null;selected=-1;pending=[];nativeInfo();properties();render();};
  canvas.addEventListener('keydown',e=>{if(busy)return;if(['Delete','Backspace','Enter','Escape'].includes(e.key)||(e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();if(['Delete','Backspace'].includes(e.key))$('#cad-delete').click();else if(e.key==='Enter')finish();else if(e.key==='Escape'){pending=[];drag=null;render();}else undoRedo(e.key.toLowerCase()==='y'||e.shiftKey);}});
  function fit(){let b=L.bounds(objects);const retained=nativeContext?.background?.bounds;if(retained)b=objects.length?{x1:Math.min(b.x1,retained.x1),y1:Math.min(b.y1,retained.y1),x2:Math.max(b.x2,retained.x2),y2:Math.max(b.y2,retained.y2)}:retained;const spanX=Math.max(20,b.x2-b.x1),spanY=Math.max(20,b.y2-b.y1);zoom=Math.max(1e-7,Math.min(100,Math.min((width-60)/spanX,(height-60)/spanY)));pan={x:-(b.x1+b.x2)/2*zoom,y:(b.y1+b.y2)/2*zoom};render();}
  $('#cad-fit').onclick=fit;$('#cad-zoom-in').onclick=()=>zoomAt(1.25);$('#cad-zoom-out').onclick=()=>zoomAt(.8);$('#cad-grid').oninput=render;$('#cad-snap').onchange=render;
  $('#cad-properties').onsubmit=e=>{e.preventDefault();const o=objects[selected];if(!o)return;try{const changed=clone(o),read=id=>{const input=$('#'+id);if(!input.value.trim())throw Error('请填写所有可编辑属性');return Number(input.value);},x=read('cad-x'),y=read('cad-y'),p=o.points?.[0]||{x:o.cx,y:o.cy};move(changed,x-p.x,y-p.y);if(o.type==='line')changed.points[1]={x:read('cad-x2'),y:read('cad-y2')};if(o.r)changed.r=read('cad-radius');if(o.type==='arc'){changed.start=read('cad-angle-start');changed.end=read('cad-angle-end');}changed.width=read('cad-width');changed.color=$('#cad-color').value;const valid=L.validate([changed])[0];checkpoint();objects[selected]=valid;properties();render();$('#cad-status').textContent='对象属性已更新。';}catch(err){$('#cad-status').textContent=err.message;}};
  $('#cad-demo').onclick=()=>{if(busy)return;checkpoint();nativeContext=null;objects=L.validate([{type:'polyline',closed:true,points:[{x:-100,y:-60},{x:100,y:-60},{x:100,y:60},{x:-100,y:60}]},{type:'circle',cx:-65,cy:0,r:16},{type:'circle',cx:65,cy:0,r:16},{type:'line',points:[{x:-35,y:0},{x:35,y:0}]},{type:'arc',cx:0,cy:0,r:35,start:0,end:180}]);selected=-1;nativeInfo();properties();fit();$('#cad-status').textContent='示例图纸已加载，可撤销恢复上一张。';};
  $('#cad-file').onchange=async()=>{const file=$('#cad-file').files[0];if(!file)return;await runCad('正在读取图纸……',async()=>{const ext=file.name.split('.').pop().toLowerCase();if(!['dwg','dxf','json'].includes(ext))throw Error('请选择 DWG、DXF 或工程 JSON 文件');if(file.size>(ext==='json'?100:20)*1024*1024)throw Error('DWG/DXF 最大 20 MB，工程 JSON 最大 100 MB');let data,context=null;
    if(ext==='dwg'){data=await rpc('open',{bytes:await file.arrayBuffer()});context=await contextFrom(data,file.name);}else if(ext==='dxf')data=L.dxfRead(await file.text());else{const json=JSON.parse(await file.text());data={objects:L.validate(json.objects),unit:json.unit,ignored:0};if(json.nativeSource){const original=await rpc('project',{source:json.nativeSource});context=await contextFrom(original,file.name);await rpc('save',{source:original.source,objects:data.objects,unit:Number(json.unit),format:'json'});}}
    const validated=L.validate(data.objects);checkpoint();objects=validated;nativeContext=context;selected=-1;pending=[];drag=null;setUnit(data.unit??0);nativeInfo();properties();fit();$('#cad-status').textContent='已导入 '+objects.length+' 个可编辑对象。'+(context?'其余 '+context.meta.retained+' 个模型实体只读保留。':data.ignored?'已略过 '+data.ignored+' 个暂不支持的 DXF 实体。':'');});$('#cad-file').value='';};
  $('#cad-dwg').onclick=()=>runCad('正在生成并校验 DWG……',async()=>{const result=await exportData('dwg');download(result.bytes,'application/acad',(nativeContext?.name||'drawing')+'-已编辑.dwg');$('#cad-status').textContent='已保存 '+result.version+' DWG，共 '+result.count+' 个模型实体。'+(result.warnings.length?'保存有 '+result.warnings.length+' 条兼容提示，请展开查看。':'保存后重新读取校验通过。');if(result.warnings.length){const list=$('#cad-dwg-notice-list');list.replaceChildren();for(const text of result.warnings){const li=document.createElement('li');li.textContent=text;list.append(li);}$('#cad-dwg-notices').hidden=false;}});
  $('#cad-dxf').onclick=()=>{if(nativeContext)return runCad('正在保存完整图纸为 DXF……',async()=>{const result=await exportData('dxf');download(result.text,'application/dxf',nativeContext.name+'-已编辑.dxf');$('#cad-status').textContent='已导出完整图纸的 DXF。';});try{download(L.dxfWrite(objects,Number($('#cad-unit').value)),'application/dxf','drawing.dxf');$('#cad-status').textContent='已导出几何数据为 DXF；颜色和线宽保存在工程 JSON 中。';}catch(e){$('#cad-status').textContent=e.message;}};
  $('#cad-json').onclick=()=>{if(nativeContext)return runCad('正在保存包含原图数据的工程……',async()=>{const result=await exportData('json');download(result.text,'application/json',nativeContext.name+'-工程.json');$('#cad-status').textContent='工程已保存，包含编辑记录和原图数据。';});download(JSON.stringify({version:1,unit:Number($('#cad-unit').value),objects},null,2),'application/json','drawing.json');};
  $('#cad-svg').onclick=()=>{try{const b=L.bounds(objects),margin=10,w=Math.max(1,b.x2-b.x1)+margin*2,h=Math.max(1,b.y2-b.y1)+margin*2;const shapes=objects.map(o=>{const style='fill="none" stroke="'+o.color+'" stroke-width="'+o.width+'"';if(o.type==='circle')return '<circle cx="'+o.cx+'" cy="'+(-o.cy)+'" r="'+o.r+'" '+style+'/>';if(o.type==='arc'){let sweep=(o.end-o.start)%360;if(sweep<=0)sweep+=360;if(sweep===360)return '<circle cx="'+o.cx+'" cy="'+(-o.cy)+'" r="'+o.r+'" '+style+'/>';const a=o.start*Math.PI/180,z=(o.start+sweep)*Math.PI/180;return '<path d="M '+(o.cx+o.r*Math.cos(a))+' '+(-o.cy-o.r*Math.sin(a))+' A '+o.r+' '+o.r+' 0 '+(sweep>180?1:0)+' 0 '+(o.cx+o.r*Math.cos(z))+' '+(-o.cy-o.r*Math.sin(z))+'" '+style+'/>';}return '<'+(o.closed?'polygon':'polyline')+' points="'+o.points.map(p=>p.x+','+(-p.y)).join(' ')+'" '+style+'/>';}).join('');download('<svg xmlns="http://www.w3.org/2000/svg" viewBox="'+(b.x1-margin)+' '+(-b.y2-margin)+' '+w+' '+h+'">'+shapes+'</svg>','image/svg+xml','drawing.svg');}catch(e){$('#cad-status').textContent=e.message;}};
  const basicSvg=$('#cad-svg').onclick;$('#cad-svg').onclick=()=>nativeContext?runCad('正在导出图纸 SVG……',async()=>{const result=await exportData('svg');download(result.text,'image/svg+xml',nativeContext.name+'-已编辑.svg');$('#cad-status').textContent='已导出完整图纸的 SVG。';}):basicSvg();
  function resize(){const rect=canvas.getBoundingClientRect();if(rect.width<1)return;width=rect.width;height=rect.height;const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);render();}new ResizeObserver(resize).observe(canvas);document.addEventListener('site:pagechange',e=>{if(e.detail.page==='tools'&&e.detail.section==='cad')resize();});window.addEventListener('pagehide',()=>resetWorker('页面已关闭'));nativeInfo();properties();resize();
})();
