(() => {
  'use strict';const $=s=>document.querySelector(s),L=window.CadLogic,canvas=$('#cad-canvas'),ctx=canvas.getContext('2d');
  let objects=[],selected=-1,undo=[],redo=[],zoom=1.5,pan={x:0,y:0},drag=null,pending=[],cursor={x:0,y:0},width=800,height=420;
  const clone=x=>JSON.parse(JSON.stringify(x)),mode=()=>$('#cad-mode').value;
  function download(text,type,name){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
  function checkpoint(previous=objects){undo.push(clone(previous));if(undo.length>60)undo.shift();redo=[];}
  function position(e,snap=true){const rect=canvas.getBoundingClientRect();let p={x:(e.clientX-rect.left-width/2-pan.x)/zoom,y:-(e.clientY-rect.top-height/2-pan.y)/zoom};if(snap&&$('#cad-snap').checked){const grid=Number($('#cad-grid').value);if(grid>0&&grid<=10000)p={x:Math.round(p.x/grid)*grid,y:Math.round(p.y/grid)*grid};}return p;}
  function move(o,dx,dy){if(o.points)o.points.forEach(p=>{p.x+=dx;p.y+=dy;});else{o.cx+=dx;o.cy+=dy;}}
  function drawObject(o,chosen=false){ctx.strokeStyle=chosen?'#207c91':o.color;ctx.lineWidth=(chosen?2.5:o.width)/zoom;ctx.beginPath();if(o.type==='circle')ctx.arc(o.cx,o.cy,o.r,0,Math.PI*2);else if(o.type==='arc'){let sweep=(o.end-o.start)%360;if(sweep<=0)sweep+=360;const start=(o.start%360)*Math.PI/180;ctx.arc(o.cx,o.cy,o.r,start,start+sweep*Math.PI/180);}else{o.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(o.closed)ctx.closePath();}ctx.stroke();}
  function render(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);const ratio=canvas.width/width;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle='#fafbf6';ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(width/2+pan.x,height/2+pan.y);ctx.scale(zoom,-zoom);
    let step=Number($('#cad-grid').value);if(!Number.isFinite(step)||step<=0||step>10000)step=10;while(step*zoom<15)step*=2;const left=(-width/2-pan.x)/zoom,right=(width/2-pan.x)/zoom,bottom=(-height/2+pan.y)/zoom,top=(height/2+pan.y)/zoom;
    ctx.strokeStyle='#8eaaa522';ctx.lineWidth=1/zoom;ctx.beginPath();for(let x=Math.ceil(left/step)*step;x<=right;x+=step){ctx.moveTo(x,bottom);ctx.lineTo(x,top);}for(let y=Math.ceil(bottom/step)*step;y<=top;y+=step){ctx.moveTo(left,y);ctx.lineTo(right,y);}ctx.stroke();ctx.strokeStyle='#72958a66';ctx.beginPath();ctx.moveTo(0,bottom);ctx.lineTo(0,top);ctx.moveTo(left,0);ctx.lineTo(right,0);ctx.stroke();objects.forEach((o,i)=>drawObject(o,i===selected));
    if(pending.length)drawObject({type:'polyline',points:[...pending,cursor],color:$('#cad-color').value,width:1});
    if(drag&&['line','circle','rect'].includes(drag.mode)){const preview=shape(drag.start,cursor,drag.mode);if(preview)drawObject(preview);}
    ctx.restore();$('#cad-cursor').textContent='X '+cursor.x.toFixed(2)+' · Y '+cursor.y.toFixed(2)+' · 缩放 '+Math.round(zoom*100)+'% · '+objects.length+' 个对象';$('#cad-undo').disabled=!undo.length;$('#cad-redo').disabled=!redo.length;$('#cad-delete').disabled=selected<0;}
  function shape(a,b,type){const style={color:$('#cad-color').value,width:1};if(type==='circle'){const r=Math.hypot(b.x-a.x,b.y-a.y);return r>.001?{...style,type:'circle',cx:a.x,cy:a.y,r}:null;}if(Math.hypot(b.x-a.x,b.y-a.y)<.001)return null;if(type==='rect'){if(a.x===b.x||a.y===b.y)return null;return {...style,type:'polyline',closed:true,points:[a,{x:b.x,y:a.y},b,{x:a.x,y:b.y}]};}return {...style,type:'line',points:[a,b]};}
  function properties(){const o=objects[selected];$('#cad-selected').textContent=o?'已选择第 '+(selected+1)+' 个对象（'+({line:'线段',polyline:'多段线',circle:'圆',arc:'圆弧'}[o.type])+'）':'请选择一个对象。';for(const id of ['cad-x','cad-y','cad-width'])$('#'+id).disabled=!o;for(const id of ['cad-x2','cad-y2'])$('#'+id).disabled=o?.type!=='line';$('#cad-radius').disabled=!['circle','arc'].includes(o?.type);for(const id of ['cad-angle-start','cad-angle-end'])$('#'+id).disabled=o?.type!=='arc';$('#cad-apply').disabled=!o;
    if(o){const p=o.points?.[0]||{x:o.cx,y:o.cy};$('#cad-x').value=+p.x.toFixed(4);$('#cad-y').value=+p.y.toFixed(4);$('#cad-width').value=o.width;$('#cad-color').value=o.color;$('#cad-x2').value=o.type==='line'?o.points[1].x:'';$('#cad-y2').value=o.type==='line'?o.points[1].y:'';$('#cad-radius').value=o.r??'';$('#cad-angle-start').value=o.start??'';$('#cad-angle-end').value=o.end??'';}}
  function hit(p){const tolerance=8/zoom;function segment(a,b){const dx=b.x-a.x,dy=b.y-a.y,div=dx*dx+dy*dy,t=div?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/div)):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)<tolerance;}
    for(let i=objects.length-1;i>=0;i--){const o=objects[i];if(o.type==='circle'&&Math.abs(Math.hypot(p.x-o.cx,p.y-o.cy)-o.r)<tolerance)return i;if(o.type==='arc'){let angle=(Math.atan2(p.y-o.cy,p.x-o.cx)*180/Math.PI+360)%360,start=(o.start%360+360)%360,end=(o.end%360+360)%360;if(end<=start)end+=360;if(angle<start)angle+=360;if(angle<=end&&Math.abs(Math.hypot(p.x-o.cx,p.y-o.cy)-o.r)<tolerance)return i;}if(o.points){for(let j=1;j<o.points.length;j++)if(segment(o.points[j-1],o.points[j]))return i;if(o.closed&&segment(o.points[o.points.length-1],o.points[0]))return i;}}return -1;}
  canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();canvas.focus();cursor=position(e);const m=mode();if(m==='polyline'){if(pending.length>=10000)return;if(!pending.length||Math.hypot(cursor.x-pending[pending.length-1].x,cursor.y-pending[pending.length-1].y)>.001)pending.push({...cursor});render();return;}if(m==='select'){selected=hit(position(e,false));properties();}drag={mode:m,start:{...cursor},pixel:{x:e.clientX,y:e.clientY},pan:{...pan},before:clone(objects),object:selected>=0?clone(objects[selected]):null};canvas.setPointerCapture(e.pointerId);render();});
  canvas.addEventListener('pointermove',e=>{cursor=position(e);if(drag){if(drag.mode==='pan')pan={x:drag.pan.x+e.clientX-drag.pixel.x,y:drag.pan.y+e.clientY-drag.pixel.y};else if(drag.mode==='select'&&drag.object){objects[selected]=clone(drag.object);move(objects[selected],cursor.x-drag.start.x,cursor.y-drag.start.y);properties();}}render();});
  canvas.addEventListener('pointerup',()=>{if(!drag)return;if(['line','circle','rect'].includes(drag.mode)){const o=shape(drag.start,cursor,drag.mode);if(o){if(objects.length>=2000){$('#cad-status').textContent='最多 2000 个对象。';drag=null;render();return;}checkpoint();objects.push(o);selected=objects.length-1;}}else if(drag.mode==='select'&&JSON.stringify(objects)!==JSON.stringify(drag.before))checkpoint(drag.before);drag=null;properties();render();});
  canvas.addEventListener('pointercancel',()=>{if(drag){objects=drag.before;drag=null;properties();render();}});
  function zoomAt(factor,px=width/2,py=height/2){const ox=(px-width/2-pan.x)/zoom,oy=(py-height/2-pan.y)/zoom;zoom=Math.max(.02,Math.min(100,zoom*factor));pan={x:px-width/2-ox*zoom,y:py-height/2-oy*zoom};render();}
  canvas.addEventListener('wheel',e=>{e.preventDefault();const rect=canvas.getBoundingClientRect();zoomAt(e.deltaY<0?1.15:1/1.15,e.clientX-rect.left,e.clientY-rect.top);},{passive:false});
  function finish(){if(pending.length<2){pending=[];render();return;}if(objects.length>=2000){$('#cad-status').textContent='最多 2000 个对象。';return;}checkpoint();objects.push({type:'polyline',points:clone(pending),closed:false,color:$('#cad-color').value,width:1});selected=objects.length-1;pending=[];properties();render();}
  $('#cad-finish').onclick=finish;canvas.addEventListener('dblclick',()=>{if(mode()==='polyline')finish();});$('#cad-mode').onchange=()=>{pending=[];drag=null;render();};
  function undoRedo(isRedo){const source=isRedo?redo:undo,target=isRedo?undo:redo;if(!source.length)return;target.push(clone(objects));objects=source.pop();selected=-1;pending=[];properties();render();}
  $('#cad-undo').onclick=()=>undoRedo(false);$('#cad-redo').onclick=()=>undoRedo(true);$('#cad-delete').onclick=()=>{if(selected<0)return;checkpoint();objects.splice(selected,1);selected=-1;properties();render();};$('#cad-clear').onclick=()=>{checkpoint();objects=[];selected=-1;pending=[];properties();render();};
  canvas.addEventListener('keydown',e=>{if(['Delete','Backspace','Enter','Escape'].includes(e.key)||(e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();if(['Delete','Backspace'].includes(e.key))$('#cad-delete').click();else if(e.key==='Enter')finish();else if(e.key==='Escape'){pending=[];drag=null;render();}else undoRedo(e.key.toLowerCase()==='y'||e.shiftKey);}});
  function fit(){const b=L.bounds(objects),spanX=Math.max(20,b.x2-b.x1),spanY=Math.max(20,b.y2-b.y1);zoom=Math.max(.02,Math.min(100,Math.min((width-60)/spanX,(height-60)/spanY)));pan={x:-(b.x1+b.x2)/2*zoom,y:(b.y1+b.y2)/2*zoom};render();}
  $('#cad-fit').onclick=fit;$('#cad-zoom-in').onclick=()=>zoomAt(1.25);$('#cad-zoom-out').onclick=()=>zoomAt(.8);$('#cad-grid').oninput=render;$('#cad-snap').onchange=render;
  $('#cad-properties').onsubmit=e=>{e.preventDefault();const o=objects[selected];if(!o)return;try{const changed=clone(o),read=id=>{const input=$('#'+id);if(!input.value.trim())throw Error('请填写所有可编辑属性');return Number(input.value);},x=read('cad-x'),y=read('cad-y'),p=o.points?.[0]||{x:o.cx,y:o.cy};move(changed,x-p.x,y-p.y);if(o.type==='line')changed.points[1]={x:read('cad-x2'),y:read('cad-y2')};if(o.r)changed.r=read('cad-radius');if(o.type==='arc'){changed.start=read('cad-angle-start');changed.end=read('cad-angle-end');}changed.width=read('cad-width');changed.color=$('#cad-color').value;const valid=L.validate([changed])[0];checkpoint();objects[selected]=valid;properties();render();$('#cad-status').textContent='对象属性已更新。';}catch(err){$('#cad-status').textContent=err.message;}};
  $('#cad-demo').onclick=()=>{checkpoint();objects=L.validate([{type:'polyline',closed:true,points:[{x:-100,y:-60},{x:100,y:-60},{x:100,y:60},{x:-100,y:60}]},{type:'circle',cx:-65,cy:0,r:16},{type:'circle',cx:65,cy:0,r:16},{type:'line',points:[{x:-35,y:0},{x:35,y:0}]},{type:'arc',cx:0,cy:0,r:35,start:0,end:180}]);selected=-1;properties();fit();$('#cad-status').textContent='示例图纸已加载，可撤销恢复上一张。';};
  $('#cad-file').onchange=async()=>{const file=$('#cad-file').files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('图纸须小于 10 MB');const text=await file.text();let data;if(file.name.toLowerCase().endsWith('.dxf'))data=L.dxfRead(text);else{const json=JSON.parse(text);data={objects:L.validate(json.objects),unit:json.unit,ignored:0};}checkpoint();objects=data.objects;selected=-1;pending=[];if(['1','4','5','6'].includes(String(data.unit)))$('#cad-unit').value=String(data.unit);properties();fit();$('#cad-status').textContent='已导入 '+objects.length+' 个对象。'+(data.ignored?'已略过 '+data.ignored+' 个暂不支持的 DXF 实体。':'');}catch(err){$('#cad-status').textContent='导入失败：'+err.message;}};
  $('#cad-dxf').onclick=()=>{try{download(L.dxfWrite(objects,Number($('#cad-unit').value)),'application/dxf','drawing.dxf');$('#cad-status').textContent='已导出几何数据为 DXF；颜色和线宽保存在工程 JSON 中。';}catch(e){$('#cad-status').textContent=e.message;}};
  $('#cad-json').onclick=()=>download(JSON.stringify({version:1,unit:Number($('#cad-unit').value),objects},null,2),'application/json','drawing.json');
  $('#cad-svg').onclick=()=>{try{const b=L.bounds(objects),margin=10,w=Math.max(1,b.x2-b.x1)+margin*2,h=Math.max(1,b.y2-b.y1)+margin*2;const shapes=objects.map(o=>{const style='fill="none" stroke="'+o.color+'" stroke-width="'+o.width+'"';if(o.type==='circle')return '<circle cx="'+o.cx+'" cy="'+(-o.cy)+'" r="'+o.r+'" '+style+'/>';if(o.type==='arc'){let sweep=(o.end-o.start)%360;if(sweep<=0)sweep+=360;if(sweep===360)return '<circle cx="'+o.cx+'" cy="'+(-o.cy)+'" r="'+o.r+'" '+style+'/>';const a=o.start*Math.PI/180,z=(o.start+sweep)*Math.PI/180;return '<path d="M '+(o.cx+o.r*Math.cos(a))+' '+(-o.cy-o.r*Math.sin(a))+' A '+o.r+' '+o.r+' 0 '+(sweep>180?1:0)+' 0 '+(o.cx+o.r*Math.cos(z))+' '+(-o.cy-o.r*Math.sin(z))+'" '+style+'/>';}return '<'+(o.closed?'polygon':'polyline')+' points="'+o.points.map(p=>p.x+','+(-p.y)).join(' ')+'" '+style+'/>';}).join('');download('<svg xmlns="http://www.w3.org/2000/svg" viewBox="'+(b.x1-margin)+' '+(-b.y2-margin)+' '+w+' '+h+'">'+shapes+'</svg>','image/svg+xml','drawing.svg');}catch(e){$('#cad-status').textContent=e.message;}};
  function resize(){const rect=canvas.getBoundingClientRect();if(rect.width<1)return;width=rect.width;height=rect.height;const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);render();}new ResizeObserver(resize).observe(canvas);document.addEventListener('site:pagechange',e=>{if(e.detail.page==='tools'&&e.detail.section==='cad')resize();});properties();resize();
})();
