(() => {
  'use strict';const $=s=>document.querySelector(s),L=window.StudioLogic;
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  const nowParts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'numeric',day:'numeric'}).formatToParts(new Date()),part=k=>Number(nowParts.find(p=>p.type===k).value);
  const today={year:part('year'),month:part('month')-1,day:part('day')};let selected={...today},year=today.year,month=today.month;
  const iso=({year,month,day})=>year+'-'+String(month+1).padStart(2,'0')+'-'+String(day).padStart(2,'0');
  const cnDays=['初一','初二','初三','初四','初五','初六','初七','初八','初九','初十','十一','十二','十三','十四','十五','十六','十七','十八','十九','二十','廿一','廿二','廿三','廿四','廿五','廿六','廿七','廿八','廿九','三十'];
  function calendar(){
    $('#calendar-year').value=year;$('#calendar-month').value=month;$('#calendar-heading').textContent=year+' 年 '+(month+1)+' 月';$('#calendar-prev').disabled=year===1900&&month===0;$('#calendar-next').disabled=year===2100&&month===11;
    const grid=$('#calendar-grid');grid.replaceChildren();const offset=L.dayInfo(year,month,1).weekday,days=new Date(Date.UTC(year,month+1,0)).getUTCDate();
    for(let i=0;i<42;i++){if(i<offset||i>=offset+days){const blank=document.createElement('span');blank.className='calendar-blank';grid.append(blank);continue;}
      const day=i-offset+1,info=L.dayInfo(year,month,day),button=document.createElement('button');button.className='calendar-day'+(info.weekday>=5?' weekend':'')+(iso(info)===iso(today)?' today':'')+(iso(info)===iso(selected)?' selected':'');button.type='button';button.dataset.day=day;button.setAttribute('aria-label',year+'年'+(month+1)+'月'+day+'日，农历'+info.lunar.month+cnDays[info.lunar.day-1]+(info.festivals.length?'，'+info.festivals.join('、'):''));button.setAttribute('aria-pressed',iso(info)===iso(selected));
      const number=document.createElement('strong'),sub=document.createElement('span');number.textContent=day;sub.textContent=info.festivals[0]||(info.lunar.day===1?info.lunar.month:cnDays[info.lunar.day-1]);if(info.festivals.length)sub.className='festival';button.append(number,sub);button.onclick=()=>{selected={year,month,day};calendar();};button.onkeydown=e=>{const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7}[e.key];if(delta===undefined)return;e.preventDefault();const d=new Date(Date.UTC(year,month,day+delta));if(d.getUTCFullYear()<1900||d.getUTCFullYear()>2100)return;selected={year:d.getUTCFullYear(),month:d.getUTCMonth(),day:d.getUTCDate()};year=selected.year;month=selected.month;calendar();grid.querySelector('[data-day="'+selected.day+'"]').focus();};grid.append(button);
    }
    const info=L.dayInfo(selected.year,selected.month,selected.day),detail=$('#calendar-detail');detail.replaceChildren();const heading=document.createElement('h3');heading.textContent=selected.year+' 年 '+(selected.month+1)+' 月 '+selected.day+' 日';detail.append(heading);for(const text of ['星期'+['一','二','三','四','五','六','日'][info.weekday],'农历 '+info.lunar.month+cnDays[info.lunar.day-1],info.lunar.yearName?info.lunar.yearName+'年':'农历年 '+info.lunar.year,info.festivals.join(' · ')||'今日没有已收录节日']){const p=document.createElement('p');p.textContent=text;detail.append(p);}$('#calendar-date').value=iso(selected);$('#calendar-status').textContent='农历由浏览器的中国历法数据计算，按北京时间显示。';
  }
  function moveMonth(delta){const d=new Date(Date.UTC(year,month+delta,1));if(d.getUTCFullYear()<1900||d.getUTCFullYear()>2100)return;year=d.getUTCFullYear();month=d.getUTCMonth();selected={year,month,day:1};calendar();}
  $('#calendar-prev').onclick=()=>moveMonth(-1);$('#calendar-next').onclick=()=>moveMonth(1);$('#calendar-today').onclick=()=>{selected={...today};year=today.year;month=today.month;calendar();};
  for(const id of ['calendar-year','calendar-month'])$('#'+id).onchange=()=>{const y=Number($('#calendar-year').value),m=Number($('#calendar-month').value);if(!Number.isInteger(y)||y<1900||y>2100){$('#calendar-status').textContent='请输入 1900–2100 的年份。';return;}year=y;month=m;selected={year,month,day:1};calendar();};
  $('#calendar-jump').onclick=()=>{try{const values=$('#calendar-date').value.split('-').map(Number),info=L.dayInfo(values[0],values[1]-1,values[2]);selected={year:info.year,month:info.month,day:info.day};year=info.year;month=info.month;calendar();}catch{$('#calendar-status').textContent='请选择 1900–2100 年间的有效日期。';}};calendar();
  const canvas=$('#pixel-canvas'),ctx=canvas.getContext('2d');let size=32,pixels=Array(size*size).fill(null),tool='pen',undo=[],redo=[],stroke=null,cursor={x:0,y:0},showCursor=false;
  const pixelStatus=text=>$('#pixel-status').textContent=text;
  function snapshot(){undo.push({size,pixels:[...pixels]});if(undo.length>60)undo.shift();redo=[];}
  function draw(){const cell=canvas.width/size;ctx.clearRect(0,0,canvas.width,canvas.height);for(let y=0;y<size;y++)for(let x=0;x<size;x++){ctx.fillStyle=pixels[y*size+x]||((x+y)%2?'#d8e3e0':'#eff4ed');ctx.fillRect(x*cell,y*cell,cell,cell);}if($('#pixel-grid').checked){ctx.strokeStyle='#213d4430';ctx.lineWidth=.7;ctx.beginPath();for(let i=0;i<=size;i++){ctx.moveTo(i*cell,0);ctx.lineTo(i*cell,canvas.height);ctx.moveTo(0,i*cell);ctx.lineTo(canvas.width,i*cell);}ctx.stroke();}if(showCursor){ctx.strokeStyle='#172f3d';ctx.lineWidth=3;ctx.strokeRect(cursor.x*cell+2,cursor.y*cell+2,cell-4,cell-4);ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.strokeRect(cursor.x*cell+2,cursor.y*cell+2,cell-4,cell-4);}$('#pixel-undo').disabled=!undo.length;$('#pixel-redo').disabled=!redo.length;$('#pixel-size').value=size;}
  function point(e){const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(size-1,Math.floor((e.clientX-r.left)/r.width*size))),y:Math.max(0,Math.min(size-1,Math.floor((e.clientY-r.top)/r.height*size)))};}
  function apply(p){const at=p.y*size+p.x,color=$('#pixel-color').value;cursor=p;if(tool==='pick'){if(pixels[at])$('#pixel-color').value=pixels[at];return;}if(tool==='fill')L.fillPixels(pixels,size,at,color);else pixels[at]=tool==='erase'?null:color;}
  function line(a,b){let x=a.x,y=a.y,dx=Math.abs(b.x-x),dy=-Math.abs(b.y-y),sx=x<b.x?1:-1,sy=y<b.y?1:-1,err=dx+dy;for(;;){apply({x,y});if(x===b.x&&y===b.y)break;const twice=2*err;if(twice>=dy){err+=dy;x+=sx;}if(twice<=dx){err+=dx;y+=sy;}}}
  canvas.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();canvas.focus();const p=point(e);if(tool!=='pick')snapshot();stroke={pointer:e.pointerId,last:p};canvas.setPointerCapture(e.pointerId);showCursor=false;apply(p);draw();};canvas.onpointermove=e=>{if(!stroke||stroke.pointer!==e.pointerId)return;const p=point(e);if(tool==='pen'||tool==='erase')line(stroke.last,p);stroke.last=p;draw();};for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>{stroke=null;pixelStatus(size+' × '+size+' 像素。已更新画布，可撤销操作。');});
  canvas.onkeydown=e=>{const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(d){e.preventDefault();cursor={x:Math.max(0,Math.min(size-1,cursor.x+d[0])),y:Math.max(0,Math.min(size-1,cursor.y+d[1]))};showCursor=true;draw();}else if(e.key===' '||e.key==='Enter'){e.preventDefault();if(tool!=='pick')snapshot();apply(cursor);showCursor=true;draw();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('#pixel-'+(e.shiftKey?'redo':'undo')).click();}};
  canvas.onblur=()=>{showCursor=false;draw();};document.querySelectorAll('[data-pixel-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.pixelTool;document.querySelectorAll('[data-pixel-tool]').forEach(n=>n.setAttribute('aria-pressed',n===b));});
  for(const color of ['#173948','#b6dedc','#edf1e8','#e9cc92','#d18b7f','#92b88e','#739fc1','#454e60','#c75f56','#eea84d','#61afa5','#ffffff']){const b=document.createElement('button');b.style.background=color;b.setAttribute('aria-label','选择颜色 '+color);b.onclick=()=>$('#pixel-color').value=color;$('#pixel-palette').append(b);}
  $('#pixel-grid').onchange=draw;$('#pixel-size').onchange=()=>{snapshot();const next=Number($('#pixel-size').value),old=pixels;pixels=Array.from({length:next*next},(_,i)=>old[Math.floor(Math.floor(i/next)*size/next)*size+Math.floor(i%next*size/next)]);size=next;cursor={x:0,y:0};draw();pixelStatus('画布已调整为 '+size+' × '+size+'，可撤销。');};
  for(const key of ['undo','redo'])$('#pixel-'+key).onclick=()=>{const from=key==='undo'?undo:redo,to=key==='undo'?redo:undo;if(!from.length)return;to.push({size,pixels:[...pixels]});const old=from.pop();size=old.size;pixels=old.pixels;cursor={x:0,y:0};draw();pixelStatus(key==='undo'?'已撤销。':'已重做。');};
  $('#pixel-clear').onclick=()=>{snapshot();pixels.fill(null);draw();pixelStatus('已清空画布，可撤销。');};$('#pixel-mirror').onclick=()=>{snapshot();for(let y=0;y<size;y++){const row=pixels.slice(y*size,(y+1)*size).reverse();pixels.splice(y*size,size,...row);}draw();};
  $('#pixel-save').onclick=()=>{download(new Blob([JSON.stringify({version:1,size,pixels})],{type:'application/json'}),'像素画项目.json');pixelStatus('已保存项目，可稍后导入继续编辑。');};
  $('#pixel-export').onclick=()=>{const scale=Number($('#pixel-scale').value),out=document.createElement('canvas');out.width=out.height=size*scale;const c=out.getContext('2d');pixels.forEach((color,i)=>{if(color){c.fillStyle=color;c.fillRect(i%size*scale,Math.floor(i/size)*scale,scale,scale);}});out.toBlob(blob=>{if(blob){download(blob,'像素画.png');pixelStatus('已导出 '+out.width+' × '+out.height+' PNG，保留透明背景。');}});};
  let importId=0;$('#pixel-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;const id=++importId;let url;try{if(file.size>20*1024*1024)throw Error('文件不能超过 20 MB');if(file.name.toLowerCase().endsWith('.json')||file.type==='application/json'){if(file.size>1024*1024)throw Error('项目文件过大');const data=JSON.parse(await file.text());if(data.version!==1||![16,32,64].includes(data.size)||!Array.isArray(data.pixels)||data.pixels.length!==data.size**2||data.pixels.some(c=>c!==null&&(typeof c!=='string'||!/^#[0-9a-f]{6}$/i.test(c))))throw Error('项目格式不正确');if(id!==importId)return;snapshot();size=data.size;pixels=data.pixels;}else{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('请选择 PNG、JPEG、WebP 或项目 JSON');url=URL.createObjectURL(file);const image=new Image();image.src=url;await image.decode();if(image.width*image.height>40000000)throw Error('图片分辨率过大');if(id!==importId)return;const out=document.createElement('canvas');out.width=out.height=size;const c=out.getContext('2d');c.imageSmoothingEnabled=false;c.drawImage(image,0,0,size,size);const bytes=c.getImageData(0,0,size,size).data;snapshot();pixels=Array.from({length:size*size},(_,i)=>bytes[i*4+3]<128?null:'#'+[bytes[i*4],bytes[i*4+1],bytes[i*4+2]].map(n=>n.toString(16).padStart(2,'0')).join(''));}cursor={x:0,y:0};draw();pixelStatus('已导入，可继续绘制或撤销。');}catch(error){pixelStatus(error.message||'导入失败，请检查文件。');}finally{if(url)URL.revokeObjectURL(url);}};draw();
})();
