(() => {
  'use strict';const $=s=>document.querySelector(s),G=window.GardenLogic,T=window.TowerLogic;
  const shapes={leaf:'M7 25C2 10 14 4 28 5c0 15-5 23-20 21M7 26 24 9',flower:'M16 12C5-4 1 17 12 16 0 25 22 34 20 20 35 23 32 3 21 12 23-4 7-3 16 12M13 16a4 4 0 1 0 8 0 4 4 0 1 0-8 0',moon:'M25 24A12 12 0 1 1 12 4a11 11 0 0 0 13 20',star:'m16 3 4 8 9 2-7 6 2 10-8-5-8 5 2-10-7-6 9-2z',drop:'M16 3C13 11 5 15 7 22c3 10 18 8 19-1 0-6-7-12-10-18z',sun:'M10 16a6 6 0 1 0 12 0 6 6 0 1 0-12 0M16 2v4m0 20v4M2 16h4m20 0h4M6 6l3 3m14 14 3 3M6 26l3-3M23 9l3-3',gem:'m5 10 6-6h10l6 6-11 18zM5 10h22M11 4l5 24L21 4',cloud:'M8 25C-1 24 1 12 9 13 11 0 30 6 26 17c8 6-1 10-18 8z',shell:'M16 28 4 16C0 2 32 2 28 16zM16 28 10 8m6 20V6m0 22 6-20',sprout:'M16 29V14M16 18C4 19 3 13 3 7c9-1 14 4 13 11M16 14C17 3 25 3 29 3c1 9-6 13-13 11',fish:'M7 16C15 3 25 9 28 16 23 26 12 28 7 16L2 9v14zM22 13h.1',bell:'M6 23h20c-5-4-3-14-10-14S11 19 6 23zM12 27h8M16 5v4',hero:'M8 14C5 1 27 1 24 14l3 15H5zM11 13h10v6H11zM16 20v8',monster:'M5 25V11l5-7 6 5 6-5 5 7v14zM10 15v3m12-3v3M11 23h10',boss:'m4 8 6 4 6-8 6 8 6-4-3 19H7zM10 18h3m6 0h3',key:'M4 11a6 6 0 1 0 12 0 6 6 0 1 0-12 0M14 16l13 13m-5-5 4-4m-8 0 4-4',door:'M7 29V4h18v25M19 17h1',potion:'M12 3h8v8c15 16 1 22-8 17-9-5 0-12 0-17zM9 19h16',up:'M5 27h7v-7h7v-7h8V5M6 12l7-7 7 7M13 5v14',down:'M5 5h7v7h7v7h8v8M6 20l7 7 7-7M13 27V13',shop:'m3 12 13-9 13 9zM7 14v13m9-13v13m9-13v13M3 29h26',gold:'M5 16a11 11 0 1 0 22 0 11 11 0 1 0-22 0M12 12h8v8h-8z'};
  function icon(name){return '<svg viewBox="0 0 32 32" aria-hidden="true"><path d="'+(shapes[name]||shapes.gem)+'"/></svg>';}
  const colors=['#638e65','#c38379','#ad965b','#b39960','#609ba7','#be9e4d','#59968d','#739ba7','#b68571','#759c61','#6b9fa0','#b49357'];let garden=G.fresh(),tower=T.fresh();
  let gardenBusy=false,gardenQueue=[],gardenClearing=null,visualTray=null,motionSerial=0;const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
  const gardenBoard=$('#garden-board'),gardenShelf=$('#garden-shelf');let gardenTouch=null;
  function paintGardenArt(element,art){if(element.dataset.art!==art){element.innerHTML=art;element.dataset.art=art;}}
  function gardenPointerDown(event){
    if(event.button!==0||event.isPrimary===false||location.hash!=='#games/garden'||document.querySelector('dialog[open]'))return;
    const source=event.target.closest?.('.garden-tile,#garden-shelf button');if(!source||source.disabled)return;
    const id=Number(source.dataset.tileId),fromShelf=gardenShelf.contains(source);
    if(event.pointerType==='touch'){gardenTouch={pointerId:event.pointerId,id,source,fromShelf,x:event.clientX,y:event.clientY,state:garden,moved:false};return;}
    // Commit at press time; selection does not depend on a later native click target.
    event.preventDefault();selectGarden(id,source,fromShelf);
  }
  gardenBoard.addEventListener('pointerdown',gardenPointerDown,true);gardenShelf.addEventListener('pointerdown',gardenPointerDown,true);
  document.addEventListener('pointermove',event=>{if(gardenTouch&&gardenTouch.pointerId===event.pointerId&&Math.hypot(event.clientX-gardenTouch.x,event.clientY-gardenTouch.y)>10)gardenTouch.moved=true;},{passive:true});
  document.addEventListener('pointerup',event=>{if(!gardenTouch||gardenTouch.pointerId!==event.pointerId)return;const tap=gardenTouch;gardenTouch=null;if(!tap.moved&&Math.hypot(event.clientX-tap.x,event.clientY-tap.y)<=10&&tap.state===garden&&tap.source.isConnected&&location.hash==='#games/garden'&&!document.querySelector('dialog[open]'))selectGarden(tap.id,tap.source,tap.fromShelf);},true);
  document.addEventListener('pointercancel',event=>{if(gardenTouch&&gardenTouch.pointerId===event.pointerId)gardenTouch=null;});
  function trayRects(){return new Map([...document.querySelectorAll('#garden-tray .filled[data-tile-id]')].map(el=>[Number(el.dataset.tileId),el.getBoundingClientRect()]));}
  function slideTray(before){if(reduceMotion.matches)return;for(const el of document.querySelectorAll('#garden-tray .filled[data-tile-id]')){const old=before.get(Number(el.dataset.tileId));if(!old||!el.animate)continue;const rect=el.getBoundingClientRect(),dx=old.left-rect.left,dy=old.top-rect.top;if(Math.abs(dx)+Math.abs(dy)<.5)continue;el.animate([{transform:'translate('+dx+'px,'+dy+'px)'},{transform:'translate(0,0)'}],{duration:140,easing:'cubic-bezier(.22,1,.36,1)'});}}
  function settleGarden(){gardenTouch=null;motionSerial++;if(gardenClearing)clearTimeout(gardenClearing.timer);gardenClearing=null;for(const move of gardenQueue){clearTimeout(move.timer);move.animation?.cancel();move.element?.remove();}gardenQueue=[];visualTray=null;gardenBusy=false;drawGarden();}
  function flushGarden(){if(gardenClearing)return;
    while(gardenQueue[0]?.arrived){const move=gardenQueue.shift(),before=trayRects();visualTray=move.staged;drawGarden();slideTray(before);
      if(move.matched.length===3){for(const id of move.matched)$('#garden-tray [data-tile-id="'+id+'"]')?.classList.add('is-clearing');const token=motionSerial;gardenClearing={timer:setTimeout(()=>{if(token!==motionSerial)return;gardenClearing=null;const positions=trayRects();visualTray=move.finalTray;drawGarden();slideTray(positions);flushGarden();},110)};return;}
    }
    gardenBusy=gardenQueue.length>0;if(!gardenBusy)visualTray=null;drawGarden(undefined,true);
  }
  function selectGarden(id,source,fromShelf=false){
    const tile=garden.tiles[id],origin=source.getBoundingClientRect(),staged=garden.tray.slice();if(!tile)return;
    const last=staged.findLastIndex(i=>garden.tiles[i].kind===tile.kind),index=last<0?staged.length:last+1;staged.splice(index,0,id);
    if(!G.pick(garden,id,fromShelf))return;
    if(reduceMotion.matches||!origin.width||!origin.height){settleGarden();return;}
    const destination=$('#garden-tray').children[index]?.getBoundingClientRect();if(!destination?.width||!destination.height){settleGarden();return;}
    if(visualTray===null)visualTray=staged.filter(i=>i!==id);
    const token=motionSerial,move={staged,finalTray:garden.tray.slice(),matched:staged.filter(i=>garden.tiles[i].kind===tile.kind),arrived:false,timer:0,animation:null,element:null};gardenQueue.push(move);gardenBusy=true;drawGarden(undefined,true);
    const flying=document.createElement('div');flying.className='garden-flight';flying.dataset.tileId=String(id);flying.setAttribute('aria-hidden','true');flying.innerHTML=icon(G.icons[tile.kind]);flying.style.cssText='left:'+origin.left+'px;top:'+origin.top+'px;width:'+origin.width+'px;height:'+origin.height+'px;--tile-ink:'+colors[tile.kind];document.body.append(flying);move.element=flying;
    const dx=destination.left-origin.left,dy=destination.top-origin.top,sx=destination.width/origin.width,sy=destination.height/origin.height;
    const finish=()=>{if(token!==motionSerial||move.arrived)return;move.arrived=true;clearTimeout(move.timer);move.element.remove();move.element=null;flushGarden();};
    if(flying.animate){move.animation=flying.animate([{transform:'translate(0,0) scale(1,1)'},{transform:'translate('+dx*.55+'px,'+(dy*.45-18)+'px) scale('+(1+(sx-1)*.55)+','+(1+(sy-1)*.55)+')',offset:.55},{transform:'translate('+dx+'px,'+dy+'px) scale('+sx+','+sy+')'}],{duration:200,easing:'cubic-bezier(.22,1,.36,1)',fill:'forwards'});move.animation.finished.then(finish,()=>{});}
    else{for(const [key,value]of Object.entries({'mid-x':dx*.55+'px','mid-y':dy*.45-18+'px','mid-sx':1+(sx-1)*.55,'mid-sy':1+(sy-1)*.55,x:dx+'px',y:dy+'px',sx,sy}))flying.style.setProperty('--flight-'+key,value);flying.style.animation='garden-fly 200ms cubic-bezier(.22,1,.36,1) forwards';flying.onanimationend=finish;}
    move.timer=setTimeout(finish,250);
  }
  function drawGarden(displayTray=visualTray??garden.tray,preserveTray=false){
    const board=$('#garden-board'),existing=new Map([...board.querySelectorAll('.garden-tile')].map(el=>[Number(el.dataset.tileId),el]));board.querySelectorAll('.garden-pile-count,.garden-map-caption').forEach(el=>el.remove());board.setAttribute('aria-busy',String(gardenBusy));const names=['叶子','花朵','月亮','星星','水滴','太阳','宝石','云朵','贝壳','嫩芽','小鱼','铃铛'];
    for(const t of garden.tiles){if(t.removed)continue;const available=G.free(garden,t),b=existing.get(t.id)||document.createElement('button');existing.delete(t.id);b.dataset.tileId=String(t.id);b.className='garden-tile '+t.region+(t.pile&&!available?' blind-back':'')+(!available?' covered':'');b.style.cssText=`left:${3+t.x*10.2}%;top:${3+t.y*10.2}%;z-index:${t.z+1};--tile-ink:${colors[t.kind]}`;const art=t.pile&&!available?'<span aria-hidden="true">?</span>':icon(G.icons[t.kind]);paintGardenArt(b,art);b.disabled=!available||garden.status!=='playing';b.setAttribute('aria-label',t.pile&&!available?'盲牌，尚未揭开':names[t.kind]+'图案'+(!available?'，被遮挡':''));b.onclick=event=>{if(event.detail===0)selectGarden(t.id,b);};if(!b.isConnected)board.append(b);}existing.forEach(el=>el.remove());
    for(const pile of ['left','right']){const left=garden.tiles.filter(t=>t.pile===pile&&!t.removed);if(!left.length)continue;const label=document.createElement('span');label.className='garden-pile-count '+pile;label.textContent='盲牌 '+left.length;board.append(label);}
    if(garden.level>1){const label=document.createElement('span');label.className='garden-map-caption';label.textContent=garden.level===2?'四塔叠牌 · 辅助牌 · 双盲牌堆':'深层四塔 · 双盲牌堆';board.append(label);}
    if(!preserveTray)$('#garden-tray').replaceChildren(...Array.from({length:7},(_,i)=>{const e=document.createElement('span');e.className='garden-slot';const t=garden.tiles[displayTray[i]];if(t){e.dataset.tileId=String(t.id);e.innerHTML=icon(G.icons[t.kind]);e.style.setProperty('--tile-ink',colors[t.kind]);e.classList.add('filled');}return e;}));
    const shelf=$('#garden-shelf'),shelfExisting=new Map([...shelf.children].map(el=>[Number(el.dataset.tileId),el]));for(const id of garden.shelf){const t=garden.tiles[id],b=shelfExisting.get(id)||document.createElement('button');shelfExisting.delete(id);b.dataset.tileId=String(id);b.className='garden-slot filled';const art=icon(G.icons[t.kind]);paintGardenArt(b,art);b.style.setProperty('--tile-ink',colors[t.kind]);b.setAttribute('aria-label','取回暂存图案');b.disabled=garden.status!=='playing';b.onclick=event=>{if(event.detail===0)selectGarden(id,b,true);};if(!b.isConnected)shelf.append(b);}shelfExisting.forEach(el=>el.remove());
    $('#garden-level').textContent='第 '+garden.level+' 关';$('#garden-progress').textContent='已消除 '+garden.cleared+' / '+garden.tiles.length;$('#garden-moves').textContent=garden.moves+' 步';$('#garden-status').textContent=garden.status==='won'?(garden.level===3?'花园全部点亮，三关挑战完成！':'本关完成，前往更深的花园。'):garden.status==='lost'?'收集槽已满。可以撤回一步、移出三张，或重开本关。':'选择没有被覆盖的牌，三个相同图案会自动消除。';
    for(const [id,key]of [['undo','undos'],['remove','removes'],['shuffle','shuffles']]){$('#garden-'+id).textContent=({undo:'撤回',remove:'移出三张',shuffle:'重排图案'}[id])+' · '+garden[key];$('#garden-'+id).disabled=!garden[key]||garden.status==='won'||(id==='undo'&&!garden.history.length)||(id==='remove'&&(!garden.tray.length||garden.shelf.length))||(id==='shuffle'&&garden.status!=='playing');}
    $('#garden-next').hidden=garden.status!=='won'||garden.level===3;$('#garden-next').disabled=$('#garden-reset').disabled=false;
  }
  $('#garden-next').onclick=()=>{gardenTouch=null;if(gardenBusy)settleGarden();garden=G.fresh(Math.min(3,garden.level+1));drawGarden();};$('#garden-reset').onclick=()=>{gardenTouch=null;if(gardenBusy)settleGarden();garden=G.fresh(garden.level);drawGarden();};for(const action of ['undo','remove','shuffle'])$('#garden-'+action).onclick=()=>{gardenTouch=null;if(gardenBusy)settleGarden();G[action](garden);drawGarden();};
  window.addEventListener('hashchange',()=>{gardenTouch=null;if(gardenBusy&&location.hash!=='#games/garden')settleGarden();});document.addEventListener('visibilitychange',()=>{if(document.hidden)gardenTouch=null;if(document.hidden&&gardenBusy)settleGarden();});window.addEventListener('pagehide',()=>{if(gardenBusy)settleGarden();});window.addEventListener('resize',()=>{if(gardenBusy)settleGarden();});reduceMotion.addEventListener('change',()=>{if(reduceMotion.matches&&gardenBusy)settleGarden();});
  const tileNames={'#':'石墙','.':'通道',key:'金钥匙',red:'攻击宝石',blue:'防御宝石',potion:'生命药水',gold:'金币',door:'金门',up:'上楼',down:'下楼',shop:'星光祭坛',start:'入口',monster:'怪物',boss:'守望者'};
  function drawTower(){
    $('#tower-stats').replaceChildren(...['第 '+(tower.floor+1)+' / 10 层','生命 '+tower.hp,'攻击 '+tower.atk,'防御 '+tower.def,'钥匙 '+tower.keys,'金币 '+tower.gold].map(text=>{const span=document.createElement('span');span.textContent=text;return span;}));
    const grid=$('#tower-board');grid.replaceChildren();tower.floors[tower.floor].forEach((tile,i)=>{const hero=i===T.index(tower.x,tower.y),el=document.createElement(tile==='#'?'span':'button');el.className='tower-tile '+(hero?'hero':tile==='#'?'wall':tile);el.innerHTML=hero?icon('hero'):['.','#','start'].includes(tile)?'':icon(tile==='red'||tile==='blue'?'gem':tile);const e=['monster','boss'].includes(tile)?T.enemy(tower.floor,tile==='boss'):null;el.title=hero?'勇者':tileNames[tile]+(e?' · '+e.name+' · 预计损失 '+(Number.isFinite(T.damage(tower,e))?T.damage(tower,e):'无法战胜'):'');el.setAttribute('aria-label',el.title);if(tile!=='#'){el.tabIndex=-1;el.onclick=()=>{const x=i%11,y=Math.floor(i/11);T.move(tower,x-tower.x,y-tower.y);drawTower();};}grid.append(el);});
    $('#tower-status').textContent=tower.notice;$('#tower-shop').hidden=!tower.shop;document.querySelectorAll('[data-tower-buy]').forEach(b=>b.disabled=tower.gold<30);
    $('#tower-enemies').replaceChildren(...[false,...(tower.floor===9?[true]:[])].map(boss=>{const e=T.enemy(tower.floor,boss),row=document.createElement('div'),loss=T.damage(tower,e);row.className='tower-enemy';row.innerHTML=icon(boss?'boss':'monster');const p=document.createElement('p');p.textContent=e.name+' · 生命 '+e.hp+' / 攻 '+e.atk+' / 防 '+e.def;const small=document.createElement('small');small.textContent=!Number.isFinite(loss)?'无法破防':loss>=tower.hp?'生命不足 · 需要 '+(loss+1)+' 生命':'战斗损失 '+loss+' 生命';p.append(small);row.append(p);return row;}));
  }
  const directions={up:[0,-1],left:[-1,0],down:[0,1],right:[1,0]};for(const b of document.querySelectorAll('[data-tower-move]'))b.onclick=()=>{T.move(tower,...directions[b.dataset.towerMove]);drawTower();};for(const b of document.querySelectorAll('[data-tower-buy]'))b.onclick=()=>{T.buy(tower,b.dataset.towerBuy);drawTower();};$('#tower-reset').onclick=()=>{tower=T.fresh();drawTower();};
  document.addEventListener('keydown',e=>{if(e.defaultPrevented||document.querySelector('dialog[open]')||location.hash!=='#games/tower'||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const key={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'}[e.key];if(key){e.preventDefault();T.move(tower,...directions[key]);drawTower();}});
  drawGarden();drawTower();
})();
