(function(root,factory){const value=factory();if(typeof module==='object'&&module.exports)module.exports=value;else root.ExtraLogic=value;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  function gomokuWin(board,index,size=15){const mark=board[index];if(!mark)return false;const x=index%size,y=Math.floor(index/size);return [[1,0],[0,1],[1,1],[1,-1]].some(([dx,dy])=>{let count=1;for(const sign of [-1,1])for(let n=1;n<size;n++){const xx=x+dx*n*sign,yy=y+dy*n*sign;if(xx<0||xx>=size||yy<0||yy>=size||board[yy*size+xx]!==mark)break;count++;}return count>=5;});}
  function gomokuMove(board,size=15){let best=-1,bestScore=-1;for(let i=0;i<board.length;i++){if(board[i])continue;const x=i%size,y=Math.floor(i/size);let score=0;for(const mark of [1,2]){board[i]=mark;if(gomokuWin(board,i,size)){board[i]=0; if(mark===2)return i;score+=1e8;}board[i]=0;for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){let count=1,open=0;for(const sign of [-1,1])for(let n=1;n<=5;n++){let xx=x+dx*n*sign,yy=y+dy*n*sign;if(xx<0||xx>=size||yy<0||yy>=size)break;const v=board[yy*size+xx];if(v===mark)count++;else{if(v===0)open++;break;}}score+=Math.pow(12,count)*(open?open:0.05)*(mark===2?1.1:1);}}score+=14-Math.abs(x-7)-Math.abs(y-7);if(score>bestScore){bestScore=score;best=i;}}return best;}
  function neighbors(index,size){const result=[],x=index%size,y=Math.floor(index/size);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const xx=x+dx,yy=y+dy;if((dx||dy)&&xx>=0&&xx<size&&yy>=0&&yy<size)result.push(yy*size+xx);}return result;}
  function makeMines(size,count,first,random=Math.random){const excluded=new Set([first,...neighbors(first,size)]),positions=Array.from({length:size*size},(_,i)=>i).filter(i=>!excluded.has(i));for(let i=positions.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[positions[i],positions[j]]=[positions[j],positions[i]];}const mines=new Set(positions.slice(0,count));return Array.from({length:size*size},(_,i)=>mines.has(i)?-1:neighbors(i,size).filter(n=>mines.has(n)).length);}
  function revealMines(board,opened,flags,index,size){if(flags[index]||opened[index])return [];const changed=[],stack=[index];while(stack.length){const i=stack.pop();if(opened[i]||flags[i])continue;opened[i]=true;changed.push(i);if(board[i]===0)stack.push(...neighbors(i,size).filter(n=>board[n]>=0&&!opened[n]));}return changed;}
  function candidates(board,i){if(board[i])return [];const used=new Set(),row=Math.floor(i/9),col=i%9;for(let n=0;n<9;n++){used.add(board[row*9+n]);used.add(board[n*9+col]);used.add(board[(Math.floor(row/3)*3+Math.floor(n/3))*9+Math.floor(col/3)*3+n%3]);}return [1,2,3,4,5,6,7,8,9].filter(n=>!used.has(n));}
  function sudokuCount(board,limit=2){let index=-1,options;for(let i=0;i<81;i++)if(!board[i]){const c=candidates(board,i);if(!c.length)return 0;if(!options||c.length<options.length){options=c;index=i;if(c.length===1)break;}}if(index<0)return 1;let count=0;for(const value of options){board[index]=value;count+=sudokuCount(board,limit-count);board[index]=0;if(count>=limit)return count;}return count;}
  function sudokuConflicts(board){const bad=new Set();for(let i=0;i<81;i++)if(board[i])for(let j=i+1;j<81;j++)if(board[i]===board[j]&&(Math.floor(i/9)===Math.floor(j/9)||i%9===j%9||Math.floor(i/27)===Math.floor(j/27)&&Math.floor(i%9/3)===Math.floor(j%9/3))){bad.add(i);bad.add(j);}return bad;}
  function newSudoku(removals=40){const shuffle=a=>a.sort(()=>0).map(v=>({v,r:Math.random()})).sort((a,b)=>a.r-b.r).map(x=>x.v);const order=()=>shuffle([0,1,2]).flatMap(g=>shuffle([0,1,2]).map(n=>g*3+n));const rows=order(),cols=order(),digits=shuffle([1,2,3,4,5,6,7,8,9]);const solution=rows.flatMap(r=>cols.map(c=>digits[(r*3+Math.floor(r/3)+c)%9]));const puzzle=solution.slice();let removed=0;for(const i of shuffle(Array.from({length:81},(_,i)=>i))){const value=puzzle[i];puzzle[i]=0;if(sudokuCount(puzzle.slice())!==1)puzzle[i]=value;else removed++;if(removed>=removals)break;}return {puzzle,solution};}
  function rotate(matrix){return matrix[0].map((_,x)=>matrix.map(row=>row[x]).reverse());}
  function collides(board,piece,x,y){return piece.some((row,dy)=>row.some((v,dx)=>v&&(x+dx<0||x+dx>=10||y+dy>=20||y+dy>=0&&board[(y+dy)*10+x+dx])));}
  function clearLines(board){let lines=0;const rows=[],clearedRows=[];for(let y=0;y<20;y++){const row=board.slice(y*10,y*10+10);if(row.every(Boolean)){lines++;clearedRows.push(y);}else rows.push(row);}while(rows.length<20)rows.unshift(Array(10).fill(0));return {board:rows.flat(),lines,clearedRows};}
  function bmi(height,weight){if(!Number.isFinite(height)||!Number.isFinite(weight)||height<=0||height>300||weight<=0||weight>1000)throw Error('请输入有效的身高和体重');return weight/(height/100)**2;}
  function loan(amount,rate,months,method){if(![amount,rate,months].every(Number.isFinite)||amount<=0||amount>1e12||rate<0||rate>100||!Number.isInteger(months)||months<1||months>600)throw Error('请输入有效金额、年利率和 1–600 月期数');const r=rate/1200;if(method==='principal'){const first=amount/months+amount*r,last=amount/months+amount/months*r,interest=amount*r*(months+1)/2;return {first,last,interest,total:amount+interest};}const monthly=r===0?amount/months:amount*r/(1-Math.pow(1+r,-months));return {first:monthly,last:monthly,interest:monthly*months-amount,total:monthly*months};}
  function color(input){input=input.trim().toLowerCase();let rgb;const hex=input.match(/^#?([\da-f]{3}|[\da-f]{6})$/);if(hex){let v=hex[1];if(v.length===3)v=[...v].map(x=>x+x).join('');rgb=[0,2,4].map(i=>parseInt(v.slice(i,i+2),16));}else{const r=input.match(/^rgb\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*\)$/),h=input.match(/^hsl\(\s*([+-]?[\d.]+)\s*,\s*([\d.]+)%\s*,\s*([\d.]+)%\s*\)$/);if(r){rgb=r.slice(1).map(Number);if(rgb.some(v=>!Number.isFinite(v)||v<0||v>255))throw Error('RGB 范围为 0–255');rgb=rgb.map(Math.round);}else if(h){let [hue,s,l]=h.slice(1).map(Number);if(![hue,s,l].every(Number.isFinite)||s>100||l>100)throw Error('HSL 百分比范围为 0–100');hue=((hue%360)+360)%360/360;s/=100;l/=100;const f=n=>{const k=(n+hue*12)%12;return Math.round((l-s*Math.min(l,1-l)*Math.max(-1,Math.min(k-3,9-k,1)))*255);};rgb=[f(0),f(8),f(4)];}else throw Error('请输入 HEX、rgb(r,g,b) 或 hsl(h,s%,l%)');}const [r,g,b]=rgb.map(v=>v/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2,s=d===0?0:d/(1-Math.abs(2*l-1));let h=0;if(d)h=(max===r?(g-b)/d%6:max===g?(b-r)/d+2:(r-g)/d+4)*60;return {hex:'#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join(''),rgb:`rgb(${rgb.join(', ')})`,hsl:`hsl(${Math.round((h+360)%360)}, ${Math.round(s*100)}%, ${Math.round(l*100)}%)`};}
  return {gomokuWin,gomokuMove,neighbors,makeMines,revealMines,candidates,sudokuCount,sudokuConflicts,newSudoku,rotate,collides,clearLines,bmi,loan,color};
});
