(() => {
  'use strict';const panel=document.querySelector('#game-fishing');if(!panel)return;
  const $=selector=>panel.querySelector(selector),L=window.FishingLogic,V=window.FishingView,canvas=$('#fishing-canvas'),ctx=canvas.getContext('2d');
  let state=L.fresh(),run,active=false,entered=false,frame=0,last=0,held=0,pointer=null,bookDirty=true,lastBasket='',lastTrip=-1;const reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
  run=L.createRun(state);const ratio=Math.min(2,window.devicePixelRatio||1);canvas.width=800*ratio;canvas.height=600*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);
  window.GameExchange?.registerCurrency('fishing',{balance:()=>state.coins,debit:amount=>{if(state.coins<amount)return false;state.coins-=amount;update();return true;}});
  const visibleIcons=new Set(),iconObserver=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>{for(const e of entries)e.isIntersecting?visibleIcons.add(e.target):visibleIcons.delete(e.target);}):null;
  function paintIcon(icon,phase){const c=icon.getContext('2d');c.clearRect(0,0,icon.width,icon.height);V.fish(c,Number(icon.dataset.fishType),icon.width/2,icon.height/2,icon.dataset.small==='true'?54:80,1,phase);}
  function render(){V.draw(ctx,state,run,L,reduce);if(!reduce)for(const icon of visibleIcons){if(!icon.isConnected){iconObserver?.unobserve(icon);visibleIcons.delete(icon);continue;}paintIcon(icon,run.time);}}
  function fishIcon(type,small=false){const icon=document.createElement('canvas');icon.width=small?84:128;icon.height=small?60:80;icon.setAttribute('role','img');icon.setAttribute('aria-label',L.SPECIES[type].name);icon.dataset.fishType=type;icon.dataset.small=String(small);paintIcon(icon,0);if(iconObserver)iconObserver.observe(icon);else visibleIcons.add(icon);return icon;}
  function loot(list){return list.map(f=>{const div=document.createElement('div');div.className='fishing-loot';const image=fishIcon(f.type,true);const description=document.createElement('span'),name=document.createElement('b'),sub=document.createElement('small');name.textContent=L.SPECIES[f.type].name;sub.textContent=f.kg.toFixed(2)+' kg · '+f.value+' 金币';description.append(name,sub);div.append(image,description);return div;});}
  function update(){const depth=L.DEPTHS[state.depthLevel],capacity=L.CAPACITIES[state.capacityLevel],idle=run.phase==='idle';$('#fishing-coins').textContent=state.coins;$('#fishing-limit').textContent=depth+' m';$('#fishing-capacity').textContent=(idle?0:run.basket.length)+' / '+capacity;$('#fishing-depth').textContent=Math.floor(run.depth)+' m';$('#fishing-cast').disabled=!idle||run.paused;$('#fishing-reel').disabled=run.phase!=='diving'||run.paused;$('#fishing-pause').textContent=run.paused?'继续航程':'暂停海流';$('#fishing-left').disabled=idle||run.paused;$('#fishing-right').disabled=idle||run.paused;
    for(const kind of ['depth','capacity']){const isDepth=kind==='depth',level=state[isDepth?'depthLevel':'capacityLevel'],values=isDepth?L.DEPTHS:L.CAPACITIES,costs=isDepth?L.DEPTH_COSTS:L.CAPACITY_COSTS,cost=costs[level],button=$('#fishing-upgrade-'+kind);button.disabled=!idle||run.paused||cost===undefined||state.coins<cost;button.textContent=cost===undefined?'已满级':cost+' 金币';$('#fishing-'+kind+'-next').textContent=cost===undefined?'已达到最高等级':values[level]+(isDepth?' m → ':' 尾 → ')+values[level+1]+(isDepth?' m':' 尾');}
    $('#fishing-status').textContent=run.paused?'已暂停，当前鱼获与鱼群都停在原处。':run.noticeTime>0?run.notice:run.phase==='diving'?'快速下潜至鱼线极限，随后缓慢收线。':run.phase==='reeling'?(run.basket.length>=capacity?'鱼篓已满，正在快速收竿。':'缓慢收线捕鱼；鱼篓装满后加速返回水面。'):'点击抛竿出发，每竿免费。';
    const list=idle?(state.lastTrip?.fish||[]):run.basket,signature=(idle?'landed':'fishing')+list.map(f=>f.type+':'+f.kg+':'+f.value).join(',');if(signature!==lastBasket){lastBasket=signature;$('#fishing-basket').replaceChildren(...loot(list));}
    $('#fishing-catch-title').textContent=idle?(state.lastTrip?'上一竿的收获':'等待第一竿鱼获'):'本竿鱼获 · '+run.basket.length+' / '+capacity;$('#fishing-trip-total').textContent=idle?(state.lastTrip?'第 '+state.lastTrip.number+' 竿已入账 '+(state.lastTrip.value+state.lastTrip.bounty)+' 金币 · 鱼获 '+state.lastTrip.value+(state.lastTrip.bounty?' · 航程奖励 +'+state.lastTrip.bounty:''):'返回水面后，鱼获自动兑换金币。'):'预计鱼获 '+run.basket.reduce((a,f)=>a+f.value,0)+' 金币 · 返回水面后结算';
    if(lastTrip!==state.casts)bookDirty=true;if(bookDirty){lastTrip=state.casts;bookDirty=false;$('#fishing-discovered').textContent=L.discovered(state)+' / '+L.SPECIES.length;$('#fishing-caught').textContent=state.caught;$('#fishing-best').textContent=state.bestTrip;
      $('#fishing-book').replaceChildren(...L.SPECIES.map((f,i)=>{const card=document.createElement('div');card.className='fishing-species'+(state.book[i].count?'':' undiscovered')+(f.weight<=1.8?' rare':'');const image=fishIcon(i);const title=document.createElement('h4');title.textContent=f.name;const habitat=document.createElement('p');habitat.textContent=f.min+'–'+f.max+' m · 基础价值 '+f.value+' 金币';const record=document.createElement('p');record.className='fishing-species-record';record.textContent=state.book[i].count?'钓获 '+state.book[i].count+' 尾 · 最大 '+state.book[i].largest.toFixed(2)+' kg':'尚未发现'+(f.min>depth?' · 升级鱼线探索':'');card.append(image,title,habitat,record);return card;}));
      $('#fishing-missions').replaceChildren(...L.MISSIONS.map(m=>{const div=document.createElement('div');div.className='fishing-mission'+(state.missions.includes(m.id)?' complete':'');const title=document.createElement('b'),desc=document.createElement('small'),reward=document.createElement('span');title.textContent=m.name;desc.textContent=m.description;reward.textContent=state.missions.includes(m.id)?'已获得':'+'+m.reward;div.append(title,desc,reward);return div;}));}
  }
  function animate(time){frame=0;if(!active||run.paused||document.hidden)return;const dt=last?Math.min(.1,(time-last)/1000):0;last=time;if(held&&run.phase!=='idle')L.steer(run,run.x+held*500*dt);if(L.step(state,run,dt)){bookDirty=true;}update();render();frame=requestAnimationFrame(animate);}
  function startFrames(){if(active&&!run.paused&&!document.hidden&&!frame){last=0;frame=requestAnimationFrame(animate);}}
  function pause(){run.paused=true;held=0;pointer=null;if(frame)cancelAnimationFrame(frame);frame=0;last=0;update();render();}
  function resume(){if(!active||document.hidden)return;run.paused=false;last=0;update();render();startFrames();}
  function cast(){if(!active)return;if(L.cast(state,run)){update();render();startFrames();canvas.focus({preventScroll:true});}}
  function reset(){const paused=run.paused;run=L.createRun(state);run.paused=paused;run.notice='本竿已重置，已入账金币和装备保留。';run.noticeTime=3;held=0;pointer=null;lastBasket='';update();render();startFrames();}
  $('#fishing-cast').addEventListener('click',cast);$('#fishing-reel').addEventListener('click',()=>{L.reel(run);update();render();});$('#fishing-pause').addEventListener('click',()=>run.paused?resume():pause());$('#fishing-reset').addEventListener('click',reset);
  for(const kind of ['depth','capacity'])$('#fishing-upgrade-'+kind).addEventListener('click',()=>{try{const {bounty}=L.upgrade(state,run,kind);run.targetDepth=L.DEPTHS[state.depthLevel];run.notice='装备升级完成'+(bounty?' · 航程奖励 +'+bounty:'');run.noticeTime=3;bookDirty=true;}catch(error){run.notice=error.message;run.noticeTime=3;}update();render();});
  function aim(e){const rect=canvas.getBoundingClientRect();if(rect.width)L.steer(run,(e.clientX-rect.left)*800/rect.width);}
  canvas.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0||!active)return;e.preventDefault();if(run.paused)return;if(run.phase==='idle')cast();aim(e);pointer=e.pointerId;canvas.setPointerCapture?.(e.pointerId);canvas.focus({preventScroll:true});});canvas.addEventListener('pointermove',e=>{if(!active||run.paused)return;if(e.pointerType!=='touch'||pointer===e.pointerId)aim(e);});
  for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>{pointer=null;});
  canvas.addEventListener('keydown',e=>{if(!active||!['Enter','Space','Escape','KeyP','KeyR','ArrowLeft','ArrowRight'].includes(e.code))return;e.preventDefault();if(e.repeat&&!['ArrowLeft','ArrowRight'].includes(e.code))return;if(e.code==='Escape'||e.code==='KeyP'){run.paused?resume():pause();return;}if(e.code==='Space'){reset();return;}if(run.paused)return;if(e.code==='Enter'){cast();return;}if(e.code==='KeyR'){L.reel(run);update();return;}held=e.code==='ArrowLeft'?-1:1;});canvas.addEventListener('keyup',e=>{if(['ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();held=0;}});canvas.addEventListener('blur',()=>{held=0;});
  for(const [id,direction]of [['fishing-left',-1],['fishing-right',1]]){const button=$('#'+id);button.addEventListener('pointerdown',e=>{if(button.disabled)return;e.preventDefault();held=direction;button.setPointerCapture?.(e.pointerId);});for(const name of ['pointerup','pointercancel','lostpointercapture','blur'])button.addEventListener(name,()=>{held=0;});button.addEventListener('click',()=>{if(!button.disabled)L.steer(run,run.x+direction*85);});}
  document.addEventListener('hub:selection',e=>{if(e.detail.kind!=='game')return;active=e.detail.name==='fishing';if(!active)pause();else{if(!entered){run.paused=false;entered=true;}update();render();startFrames();}});document.addEventListener('site:pagechange',e=>{if(e.detail.page!=='games'){active=false;pause();}});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);window.addEventListener('pagehide',pause);
  active=location.hash==='#games/fishing';update();render();startFrames();
})();
