(() => {
  'use strict';const $=s=>document.querySelector(s),L=window.FruitLogic,canvas=$('#fruit-canvas'),ctx=canvas.getContext('2d');
  const colors=['#d86162','#e78485','#937eaa','#eab05f','#e9925e','#d36b57','#bdca75','#e7a5a2','#d5b867','#b7cd7b','#65a77a'];
  let state=L.create(),phase='ready',frame=0,last=0,accumulator=0,x=210,current=0,next=1,best=0,bursts=[];
  try{const stored=Number(localStorage.getItem('xyxm-watermelon-best'));if(Number.isFinite(stored))best=Math.max(0,stored);}catch{}
  const active=()=>!$('#page-games').hidden&&!$('#game-watermelon').hidden&&!$('#games-workspace').hidden;
  function save(){best=Math.max(best,state.score);try{localStorage.setItem('xyxm-watermelon-best',String(best));}catch{}}
  function update(){best=Math.max(best,state.score);$('#fruit-score').textContent=state.score;$('#fruit-best').textContent=best;$('#fruit-next').textContent=L.names[next];$('#fruit-start').textContent=phase==='ready'?'开始游戏':phase==='paused'?'继续游戏':'重新开始';$('#fruit-pause').textContent=phase==='paused'?'继续':'暂停';$('#fruit-pause').disabled=!['running','paused'].includes(phase);$('#fruit-status').textContent=phase==='over'?'水果越过警戒线了，本局 '+state.score+' 分。':phase==='paused'?'已暂停，点击继续游戏。':phase==='ready'?'移动落点，点击投放水果。':state.won?'已经合成大西瓜，继续挑战最高分。':state.danger>0?'注意，水果堆积接近顶端。':'相同水果碰撞后会合成，下一颗是'+L.names[next]+'。';}
  function fruit(level,px,py,angle=0,alpha=1){const r=L.radii[level];ctx.save();ctx.translate(px,py);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.fillStyle=colors[level];ctx.strokeStyle='#243d3b55';ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.stroke();
    ctx.globalAlpha=alpha*.22;ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(-r*.3,-r*.3,r*.24,r*.13,-.6,0,Math.PI*2);ctx.fill();ctx.globalAlpha=alpha;
    if(level===10||level===9){ctx.strokeStyle='#285c3a66';ctx.lineWidth=r*.075;for(const k of [-.55,0,.55]){ctx.beginPath();ctx.ellipse(k*r,0,r*.16,r*.9,0,0,Math.PI*2);ctx.stroke();}}
    if(level===1||level===3||level===8){ctx.fillStyle=level===1?'#ffeac0':'#b68a4755';for(let i=0;i<10;i++){const t=i*2.4,rr=r*.65*Math.sqrt(i/10);ctx.beginPath();ctx.ellipse(Math.cos(t)*rr,Math.sin(t)*rr,1.5,2.5,t,0,Math.PI*2);ctx.fill();}}
    ctx.fillStyle='#51845b';ctx.beginPath();ctx.ellipse(r*.14,-r*.83,r*.24,r*.09,-.5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#596e43';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-r*.78);ctx.quadraticCurveTo(-r*.05,-r*1.05,r*.1,-r*1.1);ctx.stroke();
    if(r>=20){ctx.fillStyle='#263934';ctx.beginPath();ctx.arc(-r*.2,r*.12,Math.max(1.5,r*.035),0,Math.PI*2);ctx.arc(r*.2,r*.12,Math.max(1.5,r*.035),0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(0,r*.17,r*.1,.2,Math.PI-.2);ctx.stroke();}ctx.restore();}
  function draw(){ctx.clearRect(0,0,420,600);ctx.fillStyle='#f4efdf';ctx.fillRect(0,0,420,600);ctx.strokeStyle=state.danger>0?'#cf7763':'#b8b998';ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(0,82);ctx.lineTo(420,82);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#688274';ctx.font='11px "Microsoft YaHei",sans-serif';ctx.fillText('警戒线',13,75);
    for(const b of state.bodies)fruit(b.fruitLevel,b.position.x,b.position.y,b.angle);
    if(phase==='running'||phase==='ready'){const r=L.radii[current];x=Math.max(r+3,Math.min(417-r,x));ctx.strokeStyle='#5d847744';ctx.setLineDash([4,7]);ctx.beginPath();ctx.moveTo(x,50+r);ctx.lineTo(x,599);ctx.stroke();ctx.setLineDash([]);fruit(current,x,43,0,.85);}
    for(const p of bursts){const age=(state.time-p.time)/.4;if(age>1)continue;ctx.strokeStyle=colors[p.level];ctx.globalAlpha=1-age;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,L.radii[p.level]+age*20,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=1;
    if(phase!=='running'){ctx.fillStyle='#f4efdfdd';ctx.fillRect(36,230,348,95);ctx.fillStyle='#365a53';ctx.textAlign='center';ctx.font='21px "Microsoft YaHei",sans-serif';ctx.fillText(phase==='ready'?'今天，种一颗大西瓜。':phase==='paused'?'暂停一下，再继续。':'本局结束',210,270);ctx.font='13px "Microsoft YaHei",sans-serif';ctx.fillText(phase==='over'?'点击重新开始，再种一颗。':'点击开始，或按空格投放水果',210,300);ctx.textAlign='left';}}
  function resize(){const rect=canvas.getBoundingClientRect();if(rect.width<1)return;const scale=Math.min(devicePixelRatio||1,2)*rect.width/420;canvas.width=Math.round(420*scale);canvas.height=Math.round(600*scale);ctx.setTransform(scale,0,0,scale,0,0);draw();}
  function tick(now){frame=0;if(phase!=='running')return;if(!active()||document.hidden){pause();return;}accumulator+=Math.min(.08,Math.max(0,(now-last)/1000));last=now;while(accumulator>=1/120&&phase==='running'){L.step(state,1/120);accumulator-=1/120;bursts.push(...state.merges.map(p=>({...p,time:state.time})));bursts=bursts.filter(p=>state.time-p.time<.4);if(state.over){phase='over';save();}}update();draw();if(phase==='running')frame=requestAnimationFrame(tick);}
  function start(){if(!active())return;cancelAnimationFrame(frame);if(['ready','over','running'].includes(phase)){save();L.destroy(state);state=L.create();current=Math.floor(Math.random()*3);next=Math.floor(Math.random()*5);bursts=[];accumulator=0;}phase='running';last=performance.now();frame=requestAnimationFrame(tick);update();resize();canvas.focus({preventScroll:true});}
  function pause(){if(phase!=='running')return;phase='paused';cancelAnimationFrame(frame);frame=0;save();update();draw();}
  function drop(){if(!active())return;if(phase!=='running')start();if(L.drop(state,current,x)){current=next;next=Math.floor(Math.random()*5);update();draw();}}
  canvas.addEventListener('pointermove',e=>{if(phase==='running'||phase==='ready'){const rect=canvas.getBoundingClientRect();x=(e.clientX-rect.left)/rect.width*420;draw();}});canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();const rect=canvas.getBoundingClientRect();x=(e.clientX-rect.left)/rect.width*420;drop();});
  canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' ','p','P','Escape'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')x-=12;else if(e.key==='ArrowRight')x+=12;else if(e.key===' '&&!e.repeat)drop();else if(['p','P','Escape'].includes(e.key)&&!e.repeat)phase==='running'?pause():phase==='paused'&&start();draw();}});
  $('#fruit-start').onclick=start;$('#fruit-pause').onclick=()=>phase==='running'?pause():start();$('#fruit-drop').onclick=drop;$('#fruit-left').onclick=()=>{x-=20;draw();};$('#fruit-right').onclick=()=>{x+=20;draw();};
  for(let i=0;i<L.names.length;i++){const span=document.createElement('span');span.textContent=L.names[i];span.style.setProperty('--fruit-color',colors[i]);$('#fruit-chain').append(span);}
  document.addEventListener('hub:selection',e=>{if(e.detail.kind==='game'&&e.detail.name!=='watermelon')pause();});document.addEventListener('site:pagechange',e=>{if(e.detail.page!=='games'||e.detail.section!=='watermelon')pause();else resize();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);window.addEventListener('pagehide',save);new ResizeObserver(resize).observe(canvas);update();resize();
})();
