(() => {
  'use strict';const L=window.ExtraLogic,$=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
  let activeGame=(location.hash.split('/')[1]||'snake'),gomoku,ticTurn=1,gomokuThinking=false,gomokuTimer;
  function gomokuRender(){all('#gomoku-board button').forEach((b,i)=>{b.dataset.stone=gomoku[i];b.disabled=!!gomoku[i]||gomokuThinking||!!gomokuWinner;b.setAttribute('aria-label',`${Math.floor(i/15)+1} 行 ${i%15+1} 列，${gomoku[i]===1?'黑棋':gomoku[i]===2?'白棋':'空'}`);});$('#gomoku-status').textContent=gomokuWinner===3?'棋盘已满，平局。':gomokuWinner?`${gomokuWinner===1?'黑棋':'白棋'}连成五子，获胜！`:gomokuThinking?'电脑正在落子……':`轮到${ticTurn===1?'黑棋':'白棋'}。`;}
  let gomokuWinner=0;
  function gomokuPlace(i){gomoku[i]=ticTurn;if(L.gomokuWin(gomoku,i))gomokuWinner=ticTurn;else if(gomoku.every(Boolean))gomokuWinner=3;ticTurn=ticTurn===1?2:1;}
  function gomokuReset(){clearTimeout(gomokuTimer);gomoku=Array(225).fill(0);ticTurn=1;gomokuWinner=0;gomokuThinking=false;gomokuRender();}
  for(let i=0;i<225;i++){const b=document.createElement('button');b.addEventListener('click',()=>{if(gomoku[i]||gomokuWinner||gomokuThinking)return;gomokuPlace(i);if($('#gomoku-mode').value==='computer'&&!gomokuWinner){gomokuThinking=true;gomokuRender();gomokuTimer=setTimeout(()=>{const index=L.gomokuMove(gomoku);if(index>=0)gomokuPlace(index);gomokuThinking=false;gomokuRender();},180);}else gomokuRender();});$('#gomoku-board').append(b);}
  $('#gomoku-reset').onclick=gomokuReset;$('#gomoku-mode').onchange=gomokuReset;gomokuReset();

  let mineSize=9,mineCount=10,mineBoard,opened,flags,mineOver=false,flagMode=false;
  function minesRender(){all('#mines-board button').forEach((b,i)=>{b.className='mine-cell'+(opened[i]?' opened':'')+(mineOver&&mineBoard?.[i]===-1?' mine':'');b.textContent=opened[i]?mineBoard[i]===-1?'×':mineBoard[i]||'':flags[i]?'F':mineOver&&mineBoard?.[i]===-1?'×':'';b.dataset.number=opened[i]?mineBoard[i]:'';b.disabled=mineOver;b.setAttribute('aria-label',`${Math.floor(i/mineSize)+1} 行 ${i%mineSize+1} 列，${opened[i]?mineBoard[i]===-1?'地雷':mineBoard[i]+' 雷':flags[i]?'已标记':'未打开'}`);});$('#mines-count').textContent=`剩余标记 ${mineCount-flags.filter(Boolean).length}`;$('#mines-flag').textContent=`标记模式：${flagMode?'开':'关'}`;$('#mines-flag').setAttribute('aria-pressed',flagMode);}
  function mineAction(i,flag=false){if(mineOver||opened[i])return;if(flag||flagMode){if(!flags[i]&&flags.filter(Boolean).length>=mineCount)return;flags[i]=!flags[i];minesRender();return;}if(flags[i])return;if(!mineBoard)mineBoard=L.makeMines(mineSize,mineCount,i);L.revealMines(mineBoard,opened,flags,i,mineSize);if(mineBoard[i]===-1){mineOver=true;$('#mines-status').textContent='触雷了，可以再试一局。';}else if(opened.filter(Boolean).length===mineSize*mineSize-mineCount){mineOver=true;$('#mines-status').textContent='所有安全格已打开，获胜！';}else $('#mines-status').textContent='小心前进，数字是你的线索。';minesRender();}
  function minesReset(){[mineSize,mineCount]=({easy:[9,10],medium:[12,24],hard:[16,60]})[$('#mines-level').value]||[9,10];mineBoard=null;opened=Array(mineSize**2).fill(false);flags=opened.slice();mineOver=false;flagMode=false;const board=$('#mines-board');board.replaceChildren();board.style.setProperty('--size',mineSize);board.classList.toggle('hard',mineSize===16);for(let i=0;i<mineSize**2;i++){const b=document.createElement('button');b.onclick=()=>mineAction(i);b.oncontextmenu=e=>{e.preventDefault();mineAction(i,true);};board.append(b);}$('#mines-status').textContent=`${mineSize} × ${mineSize}，${mineCount} 雷。点击任意一格开始，首次打开安全。`;minesRender();}
  $('#mines-reset').onclick=minesReset;$('#mines-level').onchange=minesReset;$('#mines-flag').onclick=()=>{flagMode=!flagMode;minesRender();};minesReset();

  let sudoku,sudokuGiven,sudokuSolution,sudokuSelected=-1,sudokuDone=false;
  function sudokuRender(){const bad=L.sudokuConflicts(sudoku);all('#sudoku-board button').forEach((b,i)=>{b.textContent=sudoku[i]||'';b.className='sudoku-cell'+(sudokuGiven[i]?' given':'')+(i===sudokuSelected?' selected':'')+(bad.has(i)?' conflict':'');b.disabled=!!sudokuGiven[i]||sudokuDone;b.setAttribute('aria-label',`${Math.floor(i/9)+1} 行 ${i%9+1} 列，${sudoku[i]||'空'}${sudokuGiven[i]?'，给定数字':''}`);});}
  function sudokuInput(n){if(sudokuSelected<0||sudokuGiven[sudokuSelected]||sudokuDone)return;sudoku[sudokuSelected]=n;const conflicts=L.sudokuConflicts(sudoku);if(sudoku.every(Boolean)&&!conflicts.size){sudokuDone=true;$('#sudoku-status').textContent='全部填写正确，完成挑战！';}else $('#sudoku-status').textContent=conflicts.size?'红色格子存在重复数字，请调整。':'继续填入 1–9。';sudokuRender();}
  for(let i=0;i<81;i++){const b=document.createElement('button');b.onclick=()=>{sudokuSelected=i;sudokuRender();};b.onkeydown=e=>{if(/^[1-9]$/.test(e.key)||['Backspace','Delete','0'].includes(e.key)){e.preventDefault();sudokuInput(Number(e.key)||0);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();let next=i+({ArrowLeft:-1,ArrowRight:1,ArrowUp:-9,ArrowDown:9}[e.key]);const buttons=all('#sudoku-board button');while(next>=0&&next<81&&buttons[next].disabled)next+=({ArrowLeft:-1,ArrowRight:1,ArrowUp:-9,ArrowDown:9}[e.key]);if(next>=0&&next<81){sudokuSelected=next;sudokuRender();buttons[next].focus();}}};$('#sudoku-board').append(b);}
  function sudokuReset(){const level=$('#sudoku-level').value,removals=({easy:40,medium:50,hard:57})[level]||40;let p=L.newSudoku(removals);if(level==='hard')for(let i=0;i<7&&p.puzzle.filter(v=>!v).length<55;i++){const candidate=L.newSudoku(removals);if(candidate.puzzle.filter(v=>!v).length>p.puzzle.filter(v=>!v).length)p=candidate;}sudoku=p.puzzle.slice();sudokuGiven=p.puzzle;sudokuSolution=p.solution;sudokuSelected=-1;sudokuDone=false;$('#sudoku-status').textContent=`${level==='hard'?'困难 · ':''}${p.puzzle.filter(Boolean).length} 个已知数字，唯一解。选择空格，开始填写。`;sudokuRender();}
  all('#sudoku-pad [data-number]').forEach(b=>b.onclick=()=>sudokuInput(Number(b.dataset.number)));
  $('#sudoku-reset').onclick=sudokuReset;$('#sudoku-level').onchange=sudokuReset;
  $('#sudoku-check').onclick=()=>{const wrong=sudoku.filter((v,i)=>v&&v!==sudokuSolution[i]).length,empty=sudoku.filter(v=>!v).length;$('#sudoku-status').textContent=wrong?`有 ${wrong} 个数字需要调整。`:empty?`已填数字正确，还剩 ${empty} 格。`:'全部正确！';};
  $('#sudoku-hint').onclick=()=>{if(sudokuDone)return;let i=sudokuSelected>=0&&!sudokuGiven[sudokuSelected]&&sudoku[sudokuSelected]!==sudokuSolution[sudokuSelected]?sudokuSelected:sudoku.findIndex((v,i)=>v!==sudokuSolution[i]);if(i>=0){sudokuSelected=i;sudokuInput(sudokuSolution[i]);}};sudokuReset();

  const shapes={I:[[1,1,1,1]],J:[[1,0,0],[1,1,1]],L:[[0,0,1],[1,1,1]],O:[[1,1],[1,1]],S:[[0,1,1],[1,1,0]],T:[[0,1,0],[1,1,1]],Z:[[1,1,0],[0,1,1]]},colors=['','#b6dedc','#91bfc8','#dfc28d','#e5dca3','#8dbf9e','#dba987','#8bb2a9'];
  const tCanvas=$('#tetris-canvas'),tc=tCanvas.getContext('2d');let tBoard,tPiece,tx,ty,tScore=0,tLines=0,tState='ready',tClock,tNext,bag=[],tClear=null,tClearFrame;
  function takePiece(){if(!bag.length)bag=Object.keys(shapes).map(k=>({k,r:Math.random()})).sort((a,b)=>a.r-b.r).map(x=>x.k);return bag.pop();}
  function newPiece(){const key=tNext;tNext=takePiece();tPiece=shapes[key].map(row=>row.map(v=>v?Object.keys(shapes).indexOf(key)+1:0));tx=Math.floor((10-tPiece[0].length)/2);ty=0;if(L.collides(tBoard,tPiece,tx,ty)){tState='over';clearInterval(tClock);}$('#tetris-next').textContent=tNext;}
  function square(x,y,color,alpha=1){tc.globalAlpha=alpha;tc.fillStyle=color;tc.fillRect(x*30+1,y*30+1,28,28);tc.globalAlpha=1;}
  function tDraw(){
    tc.fillStyle='#153b49';tc.fillRect(0,0,300,600);
    tBoard.forEach((v,i)=>{if(v)square(i%10,Math.floor(i/10),colors[v]);});
    if(!tClear){let ghost=ty;while(!L.collides(tBoard,tPiece,tx,ghost+1))ghost++;tPiece.forEach((row,y)=>row.forEach((v,x)=>{if(v){square(tx+x,ghost+y,colors[v],.18);square(tx+x,ty+y,colors[v]);}}));}
    if(tClear){const progress=Math.min(tClear.elapsed/320,1);for(const row of tClear.result.clearedRows){tc.fillStyle=`rgba(234,246,221,${(1-progress)*.8})`;tc.fillRect(0,row*30,300,30);for(let x=0;x<10;x++){const shift=(x-4.5)*progress*14,fade=1-progress;tc.globalAlpha=fade;tc.fillStyle=colors[tBoard[row*10+x]];tc.fillRect(x*30+4+shift,row*30+4-progress*28,22*(1-progress*.7),22*(1-progress*.7));tc.globalAlpha=1;}}}
    if(!['running','clearing'].includes(tState)){tc.fillStyle='#102f43bb';tc.fillRect(0,0,300,600);tc.fillStyle='#f4f5eb';tc.font='20px Microsoft YaHei';tc.textAlign='center';tc.fillText({ready:'准备开始',paused:'已暂停',over:'游戏结束'}[tState],150,290);}
    $('#tetris-score').textContent=tScore;$('#tetris-lines').textContent=tLines;$('#tetris-start').textContent=['running','clearing'].includes(tState)?'暂停':tState==='paused'?'继续游戏':tState==='over'?'再来一局':'开始游戏';
    $('#tetris-status').textContent=tState==='over'?`游戏结束，本局 ${tScore} 分。`:tState==='clearing'?`消除 ${tClear.result.lines} 行！`:tState==='running'?'游戏中，空格落到底。':tState==='paused'?'已暂停。':'点击开始游戏。';
  }
  function tFinishClear(){const result=tClear.result;tBoard=result.board;tScore+=[0,100,300,500,800][result.lines]*(1+Math.floor(tLines/10));tLines+=result.lines;tClear=null;if(tState==='clearing')tState='running';newPiece();if(tState==='running')tRunClock();tDraw();}
  function tAnimateClear(now){if(tState!=='clearing'||!tClear)return;tClear.elapsed=now-tClear.start;tDraw();if(tClear.elapsed>=320)tFinishClear();else tClearFrame=requestAnimationFrame(tAnimateClear);}
  function tLock(){let top=false;tPiece.forEach((row,y)=>row.forEach((v,x)=>{if(v){if(ty+y<0)top=true;else tBoard[(ty+y)*10+tx+x]=v;}}));if(top){tState='over';clearInterval(tClock);return;}
    const cleared=L.clearLines(tBoard);
    if(cleared.lines){clearInterval(tClock);tClear={result:cleared,start:performance.now(),elapsed:0};tState='clearing';if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)tFinishClear();else tClearFrame=requestAnimationFrame(tAnimateClear);}
    else{newPiece();if(tState==='running')tRunClock();}
  }
  function tDown(){if(tState!=='running')return;if(!L.collides(tBoard,tPiece,tx,ty+1))ty++;else tLock();tDraw();}
  function tRunClock(){clearInterval(tClock);tClock=setInterval(tDown,Math.max(120,600-Math.floor(tLines/10)*60));}
  function tReset(){clearInterval(tClock);cancelAnimationFrame(tClearFrame);tClear=null;tBoard=Array(200).fill(0);tScore=tLines=0;tState='ready';bag=[];tNext=takePiece();newPiece();tDraw();}
  function tPause(){if(['running','clearing'].includes(tState)){clearInterval(tClock);cancelAnimationFrame(tClearFrame);if(tClear)tClear.elapsed=performance.now()-tClear.start;tState='paused';tDraw();}}
  function tStart(){if(['running','clearing'].includes(tState)){tPause();return;}if(tState==='over')tReset();if(tClear){tState='clearing';tClear.start=performance.now()-tClear.elapsed;tClearFrame=requestAnimationFrame(tAnimateClear);}else{tState='running';tRunClock();}tDraw();tCanvas.focus({preventScroll:true});}
  function tAction(action){if(tState!=='running')return;if(action==='left'||action==='right'){const x=tx+(action==='left'?-1:1);if(!L.collides(tBoard,tPiece,x,ty))tx=x;}else if(action==='rotate'){const candidate=L.rotate(tPiece);for(const dx of [0,-1,1,-2,2])if(!L.collides(tBoard,candidate,tx+dx,ty)){tPiece=candidate;tx+=dx;break;}}else if(action==='down'){tDown();return;}else if(action==='drop'){while(!L.collides(tBoard,tPiece,tx,ty+1)){ty++;tScore+=2;}tLock();}tDraw();}
  $('#tetris-start').onclick=tStart;$('#tetris-reset').onclick=()=>{tReset();tStart();};all('[data-tetris]').forEach(b=>b.onclick=()=>tAction(b.dataset.tetris));tCanvas.onkeydown=e=>{const action={ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down',ArrowUp:'rotate',' ':'drop'}[e.key];if(action){e.preventDefault();tAction(action);}if(e.key.toLowerCase()==='p'){e.preventDefault();tStart();}};tReset();

  const fCanvas=$('#flappy-canvas'),fc=fCanvas.getContext('2d');let fy=240,fv=0,pipes=[],fScore=0,fState='ready',fFrame,lastTime=0,spawnElapsed=0,fAngle=0;const bird=new Image();bird.src='assets/flappy-bird.png';bird.onload=()=>fDraw();let fBest=0;try{fBest=Number(localStorage.getItem('xyxm-flappy-best'))||0;}catch{}
  function fDraw(){fc.fillStyle='#193f50';fc.fillRect(0,0,360,520);fc.fillStyle='#8bb9ad';pipes.forEach(p=>{fc.fillRect(p.x,0,55,p.gap-78);fc.fillRect(p.x,p.gap+78,55,520-p.gap-78);fc.fillStyle='#b6dedc';fc.fillRect(p.x-3,p.gap-87,61,9);fc.fillRect(p.x-3,p.gap+78,61,9);fc.fillStyle='#8bb9ad';});fc.save();fc.translate(82,fy);fc.rotate(fAngle);if(bird.complete&&bird.naturalWidth)fc.drawImage(bird,-30,-22,60,44);fc.restore();if(fState!=='running'){fc.fillStyle='#102f43aa';fc.fillRect(0,0,360,520);fc.fillStyle='#f4f5eb';fc.textAlign='center';fc.font='20px Microsoft YaHei';fc.fillText({ready:'点击开始，轻触飞行',paused:'已暂停',over:'再飞一次吧'}[fState],180,300);}$('#flappy-score').textContent=fScore;$('#flappy-best').textContent=fBest;$('#flappy-start').textContent=fState==='paused'?'继续飞行':fState==='running'?'跳跃':'开始游戏';$('#flappy-pause').disabled=fState!=='running';}
  function fEnd(){fState='over';cancelAnimationFrame(fFrame);$('#flappy-status').textContent=`本局 ${fScore} 分，点击开始再试一次。`;fDraw();}
  function fTick(now){if(fState!=='running')return;const dt=Math.min((now-lastTime)/1000,.04);lastTime=now;fv+=820*dt;fy+=fv*dt;const target=Math.max(-.48,Math.min(1.25,fv/420));fAngle+=(target-fAngle)*Math.min(1,dt*10);spawnElapsed+=dt;if(spawnElapsed>=1.65){spawnElapsed=0;pipes.push({x:360,gap:130+Math.random()*260,passed:false});}for(const p of pipes){p.x-=125*dt;if(!p.passed&&p.x+55<69){p.passed=true;fScore++;if(fScore>fBest){fBest=fScore;try{localStorage.setItem('xyxm-flappy-best',String(fBest));}catch{}}}if(p.x<95&&p.x+55>69&&(fy-13<p.gap-78||fy+13>p.gap+78)){fEnd();return;}}pipes=pipes.filter(p=>p.x>-65);if(fy<13||fy>507){fEnd();return;}fDraw();fFrame=requestAnimationFrame(fTick);}
  function fStart(){if(fState==='running'){fv=-285;return;}if(fState!=='paused'){fy=240;fv=-285;fAngle=-.35;pipes=[{x:360,gap:260,passed:false}];fScore=0;spawnElapsed=0;}fState='running';lastTime=performance.now();$('#flappy-status').textContent='点击或按空格跳跃，避开管道。';fCanvas.focus({preventScroll:true});fFrame=requestAnimationFrame(fTick);fDraw();}
  function fPause(){if(fState==='running'){fState='paused';cancelAnimationFrame(fFrame);$('#flappy-status').textContent='已暂停，点击继续飞行。';fDraw();}}
  $('#flappy-start').onclick=fStart;$('#flappy-pause').onclick=fPause;fCanvas.onclick=fStart;fCanvas.onkeydown=e=>{if([' ','ArrowUp'].includes(e.key)){e.preventDefault();fStart();}if(e.key.toLowerCase()==='p'){e.preventDefault();fState==='running'?fPause():fStart();}};fDraw();$('#flappy-status').textContent='准备开始。';
  document.addEventListener('hub:selection',e=>{if(e.detail.kind==='game'){activeGame=e.detail.name;if(activeGame!=='tetris')tPause();if(activeGame!=='flappy')fPause();}});
  document.addEventListener('site:pagechange',e=>{if(e.detail.page!=='games'){tPause();fPause();}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){tPause();fPause();}});
})();
