(() => {
  'use strict';const $=s=>document.querySelector(s),L=ImageEditLogic,preview=$('#image-canvas'),surface=$('#image-surface');let work=null,original=null,fileName='edited',current=null,undo=[],redo=[],busy=false,serial=0,mode='crop',crop=null,drag=null,frame=0;
  const note=text=>$('#image-status').textContent=text,canvas=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c;};
  function controls(){for(const b of document.querySelectorAll('#tool-image [data-image-operation],#image-download,#image-crop-apply,#image-resize-apply,#image-adjust-apply,#image-reset'))b.disabled=busy||!work;$('#image-undo').disabled=busy||!undo.length;$('#image-redo').disabled=busy||!redo.length;$('#image-file').disabled=busy;surface.classList.toggle('cropping',mode==='crop'&&!!work&&!busy);}
  function filters(){return {brightness:Number($('#image-brightness').value),contrast:Number($('#image-contrast').value),saturation:Number($('#image-saturation').value)};}
  function resetFilters(){for(const id of ['brightness','contrast','saturation'])$('#image-'+id).value=100;}
  function cropFields(){if(!crop)return;for(const [id,key] of [['x','x'],['y','y'],['crop-w','w'],['crop-h','h']])$('#image-'+id).value=crop[key];}
  function resetFields(){crop={x:0,y:0,w:work.width,h:work.height};cropFields();$('#image-width').value=work.width;$('#image-height').value=work.height;$('#image-info').textContent='当前图片 '+work.width+' × '+work.height+' · '+fileName;resetFilters();}
  function overlay(){const box=$('#image-crop-box');box.hidden=!work||mode!=='crop';if(!box.hidden){box.style.left=crop.x/work.width*100+'%';box.style.top=crop.y/work.height*100+'%';box.style.width=crop.w/work.width*100+'%';box.style.height=crop.h/work.height*100+'%';}}
  function render(){frame=0;if(!work)return;const factor=Math.min(1,1200/Math.max(work.width,work.height));preview.width=Math.max(1,Math.round(work.width*factor));preview.height=Math.max(1,Math.round(work.height*factor));const ctx=preview.getContext('2d');ctx.drawImage(work,0,0,preview.width,preview.height);if(mode==='adjust'){const data=ctx.getImageData(0,0,preview.width,preview.height);L.adjustPixels(data.data,filters());ctx.putImageData(data,0,0);}for(const id of ['brightness','contrast','saturation'])$('#image-'+id+'-value').textContent=$('#image-'+id).value+'%';overlay();controls();}
  function schedule(){if(!frame)frame=requestAnimationFrame(render);}
  function blob(c,type='image/png',quality=1){return new Promise((resolve,reject)=>c.toBlob(b=>b&&b.type===type?resolve(b):reject(Error('浏览器不支持该导出格式或图片过大')),type,quality));}
  async function snapshot(c,label){return {blob:await blob(c),width:c.width,height:c.height,label};}
  function capHistory(){let bytes=undo.reduce((s,r)=>s+r.blob.size,0);while(undo.length>16||(bytes>40*1024*1024&&undo.length>1))bytes-=undo.shift().blob.size;}
  async function read(file){const url=URL.createObjectURL(file);try{const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=()=>rej(Error('图片无法读取'));img.src=url;});if(img.naturalWidth*img.naturalHeight>40000000)throw Error('请选择 4000 万像素以内的图片');const scale=Math.min(1,4096/Math.max(img.naturalWidth,img.naturalHeight)),c=canvas(Math.max(1,Math.round(img.naturalWidth*scale)),Math.max(1,Math.round(img.naturalHeight*scale)));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c;}finally{URL.revokeObjectURL(url);}}
  async function run(action){if(busy)return;busy=true;controls();try{await action();}catch(e){note(e.message);}finally{busy=false;controls();}}
  async function commit(next,label){const nextState=await snapshot(next,label);if(current)undo.push(current);capHistory();redo=[];const old=work;work=next;current=nextState;if(old&&old!==work){old.width=old.height=1;}resetFields();render();note(label+' · '+work.width+' × '+work.height+' · 可撤销');}
  async function load(file){if(!file)return;await run(async()=>{const id=++serial;if(file.size>20*1024*1024)throw Error('请选择不超过 20 MB 的图片');if(!/^image\//.test(file.type)&&!(/\.(png|jpe?g|webp|gif|bmp|avif)$/i.test(file.name)))throw Error('请选择图片文件');const next=await read(file);if(id!==serial)return;original=file;fileName=(file.name||'图片').replace(/\.[^.]+$/,'');undo=[];redo=[];current=null;await commit(next,'图片已打开');undo=[];});}
  $('#image-file').onchange=()=>load($('#image-file').files[0]);
  function cropFromFields(){return L.rect({x:$('#image-x').value,y:$('#image-y').value,w:$('#image-crop-w').value,h:$('#image-crop-h').value},work.width,work.height);}
  for(const id of ['image-x','image-y','image-crop-w','image-crop-h'])$('#'+id).oninput=()=>{if(!work||busy)return;try{crop=cropFromFields();overlay();note('裁剪范围已选择，点击“应用裁剪”确认。');}catch(e){note(e.message);}};
  $('#image-crop-ratio').onchange=()=>{if(!work||busy)return;const ratio=Number($('#image-crop-ratio').value);if(!ratio)return;const center={x:crop.x+crop.w/2,y:crop.y+crop.h/2};let w=Math.min(crop.w,work.width),h=Math.max(1,Math.round(w/ratio));if(h>work.height){h=work.height;w=Math.max(1,Math.round(h*ratio));}crop={x:Math.max(0,Math.min(work.width-w,Math.round(center.x-w/2))),y:Math.max(0,Math.min(work.height-h,Math.round(center.y-h/2))),w,h};cropFields();overlay();};
  $('#image-crop-apply').onclick=()=>run(async()=>{if(!work)return;crop=cropFromFields();const next=canvas(crop.w,crop.h);next.getContext('2d').drawImage(work,crop.x,crop.y,crop.w,crop.h,0,0,crop.w,crop.h);await commit(next,'已应用裁剪');});
  $('#image-width').oninput=()=>{if(work&&$('#image-lock').checked)$('#image-height').value=Math.max(1,Math.round(Number($('#image-width').value)*work.height/work.width));};$('#image-height').oninput=()=>{if(work&&$('#image-lock').checked)$('#image-width').value=Math.max(1,Math.round(Number($('#image-height').value)*work.width/work.height));};
  $('#image-lock').onchange=()=>{if(work&&$('#image-lock').checked)$('#image-height').value=Math.max(1,Math.round(Number($('#image-width').value)*work.height/work.width));};
  $('#image-resize-apply').onclick=()=>run(async()=>{if(!work)return;const {width,height}=L.dimensions($('#image-width').value,$('#image-height').value),next=canvas(width,height);const ctx=next.getContext('2d');ctx.imageSmoothingQuality='high';ctx.drawImage(work,0,0,width,height);await commit(next,'已调整尺寸');});
  for(const b of document.querySelectorAll('[data-image-operation]'))b.onclick=()=>run(async()=>{if(!work)return;const key=b.dataset.imageOperation,rotate=key==='rotate'||key==='rotate-left',next=canvas(rotate?work.height:work.width,rotate?work.width:work.height),ctx=next.getContext('2d');ctx.translate(next.width/2,next.height/2);if(rotate)ctx.rotate((key==='rotate'?1:-1)*Math.PI/2);else ctx.scale(key==='flip'?-1:1,key==='flip-vertical'?-1:1);ctx.drawImage(work,-work.width/2,-work.height/2);await commit(next,b.textContent.trim());});
  for(const id of ['brightness','contrast','saturation'])$('#image-'+id).oninput=schedule;
  $('#image-adjust-reset').onclick=()=>{resetFilters();render();};$('#image-adjust-apply').onclick=()=>run(async()=>{if(!work)return;const next=canvas(work.width,work.height),ctx=next.getContext('2d');ctx.drawImage(work,0,0);const pixels=ctx.getImageData(0,0,next.width,next.height);L.adjustPixels(pixels.data,filters());ctx.putImageData(pixels,0,0);await commit(next,'已应用色彩调整');});
  async function restore(direction){await run(async()=>{const source=direction==='undo'?undo:redo,destination=direction==='undo'?redo:undo;if(!source.length)return;const state=source[source.length-1],next=await read(state.blob);source.pop();destination.push(current);const old=work;work=next;current=state;old.width=old.height=1;resetFields();render();note((direction==='undo'?'已撤销':'已重做')+' · '+state.label);});}
  $('#image-undo').onclick=()=>restore('undo');$('#image-redo').onclick=()=>restore('redo');$('#image-reset').onclick=()=>run(async()=>{if(original)await commit(await read(original),'已恢复原图');});
  for(const b of document.querySelectorAll('[data-image-mode]'))b.onclick=()=>{mode=b.dataset.imageMode;for(const tab of document.querySelectorAll('[data-image-mode]'))tab.setAttribute('aria-pressed',String(tab===b));for(const panel of document.querySelectorAll('[data-image-panel]'))panel.hidden=panel.dataset.imagePanel!==mode;render();};
  function point(e){const r=preview.getBoundingClientRect();return {x:Math.round(Math.max(0,Math.min(work.width,(e.clientX-r.left)/r.width*work.width))),y:Math.round(Math.max(0,Math.min(work.height,(e.clientY-r.top)/r.height*work.height)))};}
  surface.onpointerdown=e=>{if(!work||busy||mode!=='crop'||e.button!==0)return;e.preventDefault();const p=point(e),handle=e.target.dataset.cropCorner;let start=p,key='new';if(handle){key='corner';start={x:handle.includes('w')?crop.x+crop.w:crop.x,y:handle.includes('n')?crop.y+crop.h:crop.y};}else if(e.target.closest('#image-crop-box'))key='move';drag={id:e.pointerId,key,start,p,original:{...crop}};surface.setPointerCapture(e.pointerId);};
  surface.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const p=point(e);if(drag.key==='move'){crop={...drag.original,x:Math.max(0,Math.min(work.width-drag.original.w,drag.original.x+p.x-drag.p.x)),y:Math.max(0,Math.min(work.height-drag.original.h,drag.original.y+p.y-drag.p.y))};}else crop=L.cropDrag(drag.start,p,work.width,work.height,Number($('#image-crop-ratio').value));cropFields();overlay();};surface.onpointerup=surface.onpointercancel=()=>{if(drag){drag=null;note('裁剪范围已选择，点击“应用裁剪”确认。');}};
  $('#image-type').onchange=()=>$('#image-quality-field').hidden=$('#image-type').value==='image/png';
  $('#image-download').onclick=()=>run(async()=>{if(!work)return;const type=$('#image-type').value;let output=work;if(type==='image/jpeg'){output=canvas(work.width,work.height);const ctx=output.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,output.width,output.height);ctx.drawImage(work,0,0);}const result=await blob(output,type,Number($('#image-quality').value)/100),url=URL.createObjectURL(result),a=document.createElement('a');a.href=url;a.download=fileName+'-edited.'+({'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[type]);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);if(output!==work)output.width=output.height=1;note('图片已导出 · '+work.width+' × '+work.height);});
  const panel=$('#tool-image');panel.addEventListener('dragover',e=>e.preventDefault());panel.addEventListener('drop',e=>{e.preventDefault();load(e.dataTransfer.files[0]);});document.addEventListener('paste',e=>{if(location.hash!=='#tools/image'||e.target.matches('input,textarea'))return;const file=[...e.clipboardData.items].find(item=>item.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();load(file);}});
  document.addEventListener('keydown',e=>{if(location.hash!=='#tools/image'||e.target.matches('input,textarea,select')||!(e.ctrlKey||e.metaKey))return;if(e.key.toLowerCase()==='z'){e.preventDefault();restore(e.shiftKey?'redo':'undo');}});window.addEventListener('hashchange',()=>{drag=null;});controls();
})();
