(() => {
  'use strict';const $=s=>document.querySelector(s),L=window.StudioLogic;
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  const player=$('#audio-player'),wave=$('#audio-wave'),ctx=wave.getContext('2d');let buffer=null,audioURL=null,audioContext=null,peaks=[],loadId=0,previewEnd=null,drag=null,audioName='音频';
  const status=text=>$('#audio-status').textContent=text;
  function range(){return {start:Number($('#audio-start').value),end:Number($('#audio-end').value)};}
  function setRange(start,end){if(!buffer)return;start=Math.max(0,Math.min(buffer.duration,start));end=Math.max(0,Math.min(buffer.duration,end));$('#audio-start').value=start.toFixed(2);$('#audio-end').value=end.toFixed(2);drawWave();}
  function drawWave(){ctx.clearRect(0,0,wave.width,wave.height);ctx.fillStyle='#102c39';ctx.fillRect(0,0,wave.width,wave.height);if(!buffer)return;const {start,end}=range(),w=wave.width,h=wave.height;ctx.fillStyle='#c8e8de20';ctx.fillRect(start/buffer.duration*w,0,(end-start)/buffer.duration*w,h);ctx.strokeStyle='#ccebdc';ctx.lineWidth=1.2;ctx.beginPath();peaks.forEach((p,i)=>{const x=i/peaks.length*w;ctx.moveTo(x,h/2-p.max*h*.43);ctx.lineTo(x,h/2-p.min*h*.43);});ctx.stroke();ctx.strokeStyle='#d9f3e0';ctx.lineWidth=2;for(const x of [start,end].map(s=>s/buffer.duration*w)){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}ctx.strokeStyle='#efcd8f';ctx.lineWidth=2;const play=player.currentTime/buffer.duration*w;ctx.beginPath();ctx.moveTo(play,0);ctx.lineTo(play,h);ctx.stroke();}
  function audioEnabled(enabled){['audio-start','audio-end','audio-preview','audio-full','audio-export'].forEach(id=>document.getElementById(id).disabled=!enabled);}
  $('#audio-file').addEventListener('change',async e=>{
    const file=e.target.files[0];if(!file)return;const id=++loadId;player.pause();previewEnd=null;audioEnabled(false);status('正在解码音频…');
    try{if(file.size>80*1024*1024)throw Error('文件超过 80 MB，请选择较小音频');const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw Error('当前浏览器不支持音频解码');if(!audioContext)audioContext=new Context();const decoded=await audioContext.decodeAudioData(await file.arrayBuffer());if(id!==loadId)return;if(decoded.length*decoded.numberOfChannels*4>180*1024*1024||decoded.duration>900)throw Error('音频过长或解码数据过大，请选择 15 分钟以内的片段');
      buffer=decoded;audioName=file.name.replace(/\.[^.]*$/,'');if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(file);player.src=audioURL;$('#audio-file-name').textContent=file.name;$('#audio-empty').hidden=true;
      const samples=buffer.getChannelData(0),bins=Math.min(1200,samples.length),step=samples.length/bins;peaks=Array.from({length:bins},(_,i)=>{let min=1,max=-1;for(let j=Math.floor(i*step);j<Math.floor((i+1)*step);j++){min=Math.min(min,samples[j]);max=Math.max(max,samples[j]);}return {min,max};});
      $('#audio-start').max=buffer.duration;$('#audio-end').max=buffer.duration;audioEnabled(true);setRange(0,buffer.duration);status('时长 '+buffer.duration.toFixed(2)+' 秒 · '+buffer.sampleRate+' Hz · '+buffer.numberOfChannels+' 声道。拖动波形选择片段。');
    }catch(err){if(id!==loadId)return;buffer=null;peaks=[];if(audioURL)URL.revokeObjectURL(audioURL);audioURL=null;player.removeAttribute('src');player.load();$('#audio-empty').hidden=false;$('#audio-file-name').textContent='解码失败';drawWave();status(err.message||'无法解码此音频格式');}
  });
  ['audio-start','audio-end'].forEach(id=>document.getElementById(id).addEventListener('input',()=>{previewEnd=null;drawWave();}));
  $('#audio-full').onclick=()=>{previewEnd=null;setRange(0,buffer.duration);};
  $('#audio-preview').onclick=async()=>{const {start,end}=range();if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end>buffer.duration+.01){status('请设置有效的开始和结束时间');return;}try{player.currentTime=start;previewEnd=Math.min(end,buffer.duration);await player.play();status('正在播放选区');}catch{status('无法播放，请使用播放器的播放按钮');}};
  player.addEventListener('timeupdate',()=>{if(previewEnd!=null&&player.currentTime>=previewEnd){player.pause();player.currentTime=previewEnd;previewEnd=null;status('选区播放完成');}drawWave();});
  player.addEventListener('seeked',drawWave);player.addEventListener('ended',()=>previewEnd=null);
  function timeAt(event){const rect=wave.getBoundingClientRect();return Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width))*buffer.duration;}
  wave.addEventListener('pointerdown',e=>{if(!buffer||e.button!==0)return;wave.focus();drag={anchor:timeAt(e),x:e.clientX,moved:false};previewEnd=null;wave.setPointerCapture(e.pointerId);});
  wave.addEventListener('pointermove',e=>{if(!drag||!buffer)return;if(Math.abs(e.clientX-drag.x)>3)drag.moved=true;if(drag.moved){const time=timeAt(e);setRange(Math.min(drag.anchor,time),Math.max(drag.anchor,time));}});
  wave.addEventListener('pointerup',e=>{if(!drag||!buffer)return;if(!drag.moved)player.currentTime=timeAt(e);else status('选区 '+range().start.toFixed(2)+'–'+range().end.toFixed(2)+' 秒');drag=null;drawWave();});wave.addEventListener('pointercancel',()=>drag=null);
  wave.addEventListener('keydown',e=>{if(!buffer)return;if(['ArrowLeft','ArrowRight','Home','End',' '].includes(e.key)){e.preventDefault();previewEnd=null;if(e.key===' ')player.paused?player.play().catch(()=>status('请用播放器按钮播放')):player.pause();else player.currentTime=e.key==='Home'?0:e.key==='End'?buffer.duration:Math.max(0,Math.min(buffer.duration,player.currentTime+(e.key==='ArrowRight'?1:-1)));drawWave();}});
  $('#audio-export').onclick=()=>{try{const {start,end}=range();if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end>buffer.duration+.01)throw Error('选区超出音频时长');const channels=Array.from({length:buffer.numberOfChannels},(_,i)=>buffer.getChannelData(i));const wav=L.wav(channels,buffer.sampleRate,start*buffer.sampleRate,end*buffer.sampleRate);download(new Blob([wav],{type:'audio/wav'}),audioName+'-裁剪.wav');status('已导出 '+(end-start).toFixed(2)+' 秒 WAV 片段');}catch(err){status(err.message);}};
  document.addEventListener('hub:selection',e=>{if(e.detail.kind==='tool'&&e.detail.name!=='audio'){player.pause();previewEnd=null;}});
  document.addEventListener('site:pagechange',e=>{if(e.detail.page!=='tools'){player.pause();previewEnd=null;stopGifPreview();}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){player.pause();stopGifPreview();}});
  // GIF encoder: local images, sequential quantization, bounded frames and canvas.
  let frames=[],previewTimer=null,previewIndex=0,gifURL=null,gifBusy=false,gifRevision=0;const gifCanvas=$('#gif-preview'),gctx=gifCanvas.getContext('2d');
  const gifStatus=text=>$('#gif-status').textContent=text;
  function stopGifPreview(){clearInterval(previewTimer);clearTimeout(previewTimer);previewTimer=null;$('#gif-preview-button').textContent='预览动画';}
  function invalidateGif(){stopGifPreview();gifRevision++;if(gifURL)URL.revokeObjectURL(gifURL);gifURL=null;$('#gif-download').hidden=true;$('#gif-result').hidden=true;$('#gif-result').removeAttribute('src');}
  function validSize(){const w=Number($('#gif-width').value),h=Number($('#gif-height').value);if(!Number.isInteger(w)||!Number.isInteger(h)||w<16||h<16||w>640||h>640)throw Error('画布宽高需为 16–640 的整数');return {w,h};}
  function paintFrame(frame,canvas,context){context.fillStyle=$('#gif-background').value;context.fillRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/frame.image.width,canvas.height/frame.image.height),w=frame.image.width*scale,h=frame.image.height*scale;context.drawImage(frame.image,(canvas.width-w)/2,(canvas.height-h)/2,w,h);}
  function buttons(){const available=frames.length>0&&!gifBusy;$('#gif-make').disabled=!available;$('#gif-preview-button').disabled=!available;$('#gif-files').disabled=gifBusy;$('#gif-demo').disabled=gifBusy;$('#gif-clear').disabled=gifBusy;}
  function frameList(){
    const container=$('#gif-frames');container.replaceChildren();frames.forEach((frame,i)=>{
      const card=document.createElement('article');card.className='gif-frame';const img=document.createElement('img');img.src=frame.url;img.alt='第 '+(i+1)+' 帧';const name=document.createElement('p');name.textContent=(i+1)+'. '+frame.name;const label=document.createElement('label');label.textContent='时长（毫秒）';const input=document.createElement('input');input.type='number';input.min=20;input.max=10000;input.step=10;input.value=frame.delay;input.disabled=gifBusy;input.addEventListener('change',()=>{const value=Number(input.value);if(!Number.isFinite(value)||value<20||value>10000){input.value=frame.delay;gifStatus('帧时长应在 20–10000 毫秒之间');return;}frame.delay=Math.round(value/10)*10;input.value=frame.delay;invalidateGif();});label.append(input);
      const actions=document.createElement('div');actions.className='gif-frame-actions';for(const [text,delta] of [['前移',-1],['后移',1],['删除',0]]){const b=document.createElement('button');b.type='button';b.textContent=text;b.setAttribute('aria-label',text+'第 '+(i+1)+' 帧');b.disabled=gifBusy||(delta&&(i+delta<0||i+delta>=frames.length));b.onclick=()=>{invalidateGif();if(delta)[frames[i],frames[i+delta]]=[frames[i+delta],frames[i]];else{URL.revokeObjectURL(frame.url);frames.splice(i,1);}frameList();};actions.append(b);}card.append(img,name,label,actions);container.append(card);
    });buttons();
  }
  async function imageFromFile(file){if(file.size>20*1024*1024)throw Error('单张图片不能超过 20 MB');const url=URL.createObjectURL(file),image=new Image();try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('无法打开图片 '+file.name));image.src=url;});if(image.width*image.height>40000000)throw Error('图片尺寸过大');return {image,url,name:file.name,delay:Math.max(20,Math.min(10000,Number($('#gif-delay').value)||200))};}catch(err){URL.revokeObjectURL(url);throw err;}}
  $('#gif-files').addEventListener('change',async e=>{if(gifBusy)return;const files=[...e.target.files];if(frames.length+files.length>60){gifStatus('最多 60 帧，请减少图片数量');return;}invalidateGif();gifBusy=true;buttons();const errors=[];for(const file of files){try{frames.push(await imageFromFile(file));}catch(err){errors.push(err.message);}}gifBusy=false;frameList();gifStatus(errors.length?errors.join('；'):'已添加 '+files.length+' 帧，共 '+frames.length+' 帧');e.target.value='';});
  $('#gif-demo').onclick=async()=>{if(gifBusy)return;invalidateGif();frames.forEach(f=>URL.revokeObjectURL(f.url));frames=[];gifBusy=true;buttons();for(let i=0;i<4;i++){const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;const context=canvas.getContext('2d');context.fillStyle=['#1a4558','#235c63','#356d67','#42746b'][i];context.fillRect(0,0,320,240);context.fillStyle='#d9ecdc';context.fillRect(40+i*45,80,50,50);context.font='20px sans-serif';context.fillText('FRAME 0'+(i+1),35,195);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));frames.push(await imageFromFile(new File([blob],'演示帧-'+(i+1)+'.png',{type:'image/png'})));}gifBusy=false;frameList();gifStatus('已加载 4 张演示帧，可以调整顺序或生成 GIF');};
  $('#gif-clear').onclick=()=>{invalidateGif();frames.forEach(f=>URL.revokeObjectURL(f.url));frames=[];$('#gif-preview').hidden=true;frameList();gifStatus('帧列表已清空');};
  for(const id of ['gif-width','gif-height','gif-background','gif-loop'])document.getElementById(id).addEventListener('change',invalidateGif);
  $('#gif-delay').addEventListener('change',()=>{const v=Number($('#gif-delay').value);if(!Number.isFinite(v)||v<20||v>10000){gifStatus('默认帧时长应在 20–10000 毫秒之间');return;}});
  $('#gif-preview-button').onclick=()=>{if(previewTimer){stopGifPreview();return;}try{const {w,h}=validSize();gifCanvas.width=w;gifCanvas.height=h;gifCanvas.hidden=false;$('#gif-result').hidden=true;previewIndex=0;$('#gif-preview-button').textContent='停止预览';function tick(){if(!frames.length)return;paintFrame(frames[previewIndex],gifCanvas,gctx);const delay=frames[previewIndex].delay;previewIndex++;if(previewIndex>=frames.length){if(!$('#gif-loop').checked){stopGifPreview();return;}previewIndex=0;}previewTimer=setTimeout(tick,delay);}tick();}catch(err){gifStatus(err.message);}};
  $('#gif-make').onclick=async()=>{
    if(gifBusy||!frames.length)return;let dimensions;try{dimensions=validSize();}catch(err){gifStatus(err.message);return;}invalidateGif();gifBusy=true;buttons();frameList();const revision=gifRevision,{w,h}=dimensions,canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const context=canvas.getContext('2d',{willReadFrequently:true});
    try{const {GIFEncoder,quantize,applyPalette}=window.GIFCodec,encoder=GIFEncoder();for(let i=0;i<frames.length;i++){gifStatus('正在编码第 '+(i+1)+' / '+frames.length+' 帧…');await new Promise(resolve=>setTimeout(resolve,0));if(revision!==gifRevision)throw Error('设置已改变，请重新生成');paintFrame(frames[i],canvas,context);const data=context.getImageData(0,0,w,h).data,palette=quantize(data,256),index=applyPalette(data,palette);encoder.writeFrame(index,w,h,{palette,delay:frames[i].delay,repeat:$('#gif-loop').checked?0:-1,dispose:1});}encoder.finish();const blob=new Blob([encoder.bytes()],{type:'image/gif'});gifURL=URL.createObjectURL(blob);$('#gif-download').href=gifURL;$('#gif-download').hidden=false;$('#gif-result').src=gifURL;$('#gif-result').hidden=false;gifCanvas.hidden=true;gifStatus('GIF 已生成 · '+frames.length+' 帧 · '+(blob.size/1024).toFixed(1)+' KB');}
    catch(err){gifStatus(err.message||'GIF 生成失败');}finally{gifBusy=false;frameList();}
  };
  document.addEventListener('hub:selection',e=>{if(e.detail.kind==='tool'&&e.detail.name!=='gif')stopGifPreview();});
  window.addEventListener('pagehide',()=>{player.pause();stopGifPreview();if(audioURL)URL.revokeObjectURL(audioURL);if(gifURL)URL.revokeObjectURL(gifURL);frames.forEach(f=>URL.revokeObjectURL(f.url));audioContext?.close();});
  drawWave();buttons();
})();
