(() => {const $=s=>document.querySelector(s),host=$('#model-stage'),status=text=>{const note=$('#model-status');note.textContent=text;note.hidden=!text;};let viewer=null,loading=null,spin=true,wire=false;
  const active=()=>location.hash==='#tools/model'&&!document.hidden;
  async function ensure(){if(viewer)return viewer;if(loading)return loading;$('#model-loading').hidden=false;loading=import('./model-viewer-runtime.js?v=cdc577195055').then(module=>{viewer=module.createViewer(host,status);$('#model-loading').hidden=true;viewer.setSpin(spin);viewer.setWire(wire);viewer.setActive(active());return viewer;}).catch(error=>{status('无法启动 3D 预览：'+error.message);$('#model-loading').textContent='需要支持 WebGL 2 的浏览器与硬件加速';loading=null;throw error;});return loading;}
  function route(){if(active())ensure().catch(()=>{});else viewer?.setActive(false);if(viewer&&active())viewer.setActive(true);}
  async function files(list){if(!list.length)return;status('正在读取模型与配套资源…');try{const v=await ensure();await v.load(list);$('#model-black-options').hidden=true;}catch(error){status('导入失败：'+error.message);}}
  $('#model-files').onchange=e=>files(e.target.files);host.addEventListener('dragover',e=>e.preventDefault());host.addEventListener('drop',e=>{e.preventDefault();files(e.dataTransfer.files);});
  const featureLabels={lens:'引力透镜',dop:'多普勒束射',disk:'吸积盘'};for(const b of document.querySelectorAll('[data-black-feature]'))b.onclick=()=>{const on=b.getAttribute('aria-pressed')!=='true';viewer?.setBlackFeature(b.dataset.blackFeature,on);b.setAttribute('aria-pressed',String(on));b.textContent=featureLabels[b.dataset.blackFeature]+(on?'：开':'：关');};
  $('#model-example').onclick=()=>ensure().then(v=>{v.blackHole();$('#model-black-options').hidden=false;for(const b of document.querySelectorAll('[data-black-feature]')){b.setAttribute('aria-pressed','true');b.textContent=featureLabels[b.dataset.blackFeature]+'：开';}}).catch(()=>{});$('#model-frame').onclick=()=>viewer?.frame();$('#model-spin').onclick=()=>{spin=!spin;viewer?.setSpin(spin);$('#model-spin').textContent='自动旋转：'+(spin?'开':'关');$('#model-spin').setAttribute('aria-pressed',String(spin));};$('#model-wire').onclick=()=>{wire=!wire;viewer?.setWire(wire);$('#model-wire').textContent='线框：'+(wire?'开':'关');$('#model-wire').setAttribute('aria-pressed',String(wire));};$('#model-shot').onclick=()=>viewer?.screenshot();window.addEventListener('hashchange',route);document.addEventListener('visibilitychange',route);window.addEventListener('pagehide',()=>viewer?.setActive(false));route();
})();
