(() => {
  'use strict';const $=s=>document.querySelector(s),P=window.PDFLib,L=window.PlusLogic;let files=[],busy=false,revision=0,pdfjs=null,viewDoc=null,viewTask=null,viewKey=null,renderTask=null,viewRevision=0,previewReady=false,queue=Promise.resolve();
  const ids=['pdf-merge','pdf-source','pdf-extract','pdf-split','pdf-rotate','pdf-preview-button','pdf-text'];
  function controls(){for(const id of ids)$('#'+id).disabled=busy||!files.length;$('#pdf-files').disabled=busy;$('#pdf-clear').disabled=busy;$('#pdf-images-export').disabled=busy;$('#pdf-images').disabled=busy;$('#pdf-image').disabled=busy||!previewReady;for(const b of $('#pdf-list').querySelectorAll('button'))b.disabled=busy||b.dataset.edge==='true';}
  function message(text){$('#pdf-status').textContent=text;}
  function download(bytes,type,name){const blob=bytes instanceof Blob?bytes:new Blob([bytes],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
  const selected=()=>files[Number($('#pdf-source').value)||0];
  async function run(fn){if(busy)return;busy=true;controls();try{await fn();}catch(e){message(e.message||'处理失败，请检查文件。');}finally{busy=false;controls();}}
  function invalidateView(){viewRevision++;renderTask?.cancel();renderTask=null;previewReady=false;$('#pdf-preview').hidden=true;$('#pdf-empty').hidden=false;const task=viewTask;queue=queue.then(()=>task?.destroy()).catch(()=>{});viewTask=null;viewDoc=null;viewKey=null;controls();}
  function list(){const select=$('#pdf-source'),current=selected()?.id;select.replaceChildren();$('#pdf-list').replaceChildren();files.forEach((f,i)=>{const option=document.createElement('option');option.value=i;option.textContent=f.name+' · '+f.count+' 页';select.append(option);if(f.id===current)select.value=i;const row=document.createElement('div'),label=document.createElement('span');label.textContent=(i+1)+'. '+f.name+' · '+f.count+' 页';row.append(label);for(const [name,delta] of [['上移',-1],['下移',1],['移除',0]]){const b=document.createElement('button');b.className='button secondary';b.textContent=name;b.setAttribute('aria-label',name+' '+f.name);b.dataset.edge=String(!!delta&&(i+delta<0||i+delta>=files.length));b.disabled=busy||b.dataset.edge==='true';b.onclick=()=>{if(delta&&(i+delta<0||i+delta>=files.length))return;invalidateView();if(delta)[files[i],files[i+delta]]=[files[i+delta],files[i]];else files.splice(i,1);list();message(files.length?'文件列表已更新。':'文件已清空。');};row.append(b);}$('#pdf-list').append(row);});controls();}
  async function load(bytes){try{const doc=await P.PDFDocument.load(bytes);if(doc.getPageCount()>2000)throw Error('单个 PDF 不超过 2000 页');return doc;}catch(e){if(/encrypt|password/i.test(e.message))throw Error('此 PDF 有加密保护，请先用有权限的工具解密后再导入。');throw Error('PDF 无法读取：'+e.message);}}
  $('#pdf-files').onchange=()=>run(async()=>{const input=[...$('#pdf-files').files];if(!input.length)return;const total=input.reduce((n,f)=>n+f.size,0)+files.reduce((n,f)=>n+f.bytes.length,0);if(input.length+files.length>30||total>100*1024*1024)throw Error('最多 30 个文件，总大小不超过 100 MB');const loaded=[];for(const f of input){message('正在读取 '+f.name+'……');const bytes=new Uint8Array(await f.arrayBuffer()),doc=await load(bytes);loaded.push({id:++revision,name:f.name,bytes,count:doc.getPageCount()});}invalidateView();files.push(...loaded);list();message('已加载 '+files.length+' 个 PDF，共 '+files.reduce((n,f)=>n+f.count,0)+' 页。');$('#pdf-files').value='';});
  $('#pdf-source').onchange=()=>{invalidateView();$('#pdf-page').value=1;$('#pdf-range').value='';message('当前文件：'+selected().name);};$('#pdf-clear').onclick=()=>{invalidateView();files=[];list();message('文件已清空。');};
  async function exportDocument(doc,name){download(await doc.save(),'application/pdf',name);}
  $('#pdf-merge').onclick=()=>run(async()=>{if(!files.length)throw Error('请先选择 PDF');const out=await P.PDFDocument.create();let total=0;for(const f of files){total+=f.count;if(total>2000)throw Error('合并结果最多 2000 页');message('正在合并 '+f.name+'……');const doc=await load(f.bytes);for(const page of await out.copyPages(doc,doc.getPageIndices()))out.addPage(page);}await exportDocument(out,'merged.pdf');message('已合并 '+files.length+' 个文件，共 '+total+' 页。');});
  $('#pdf-extract').onclick=()=>run(async()=>{const f=selected();if(!f)throw Error('请先选择 PDF');const indexes=L.pageRange($('#pdf-range').value,f.count),doc=await load(f.bytes),out=await P.PDFDocument.create();for(const page of await out.copyPages(doc,indexes))out.addPage(page);await exportDocument(out,'extracted.pdf');message('已提取 '+indexes.length+' 页，按输入页码顺序输出。');});
  $('#pdf-rotate').onclick=()=>run(async()=>{const f=selected();if(!f)throw Error('请先选择 PDF');const indexes=new Set(L.pageRange($('#pdf-range').value,f.count)),doc=await load(f.bytes),angle=Number($('#pdf-angle').value);for(const index of indexes){const page=doc.getPage(index);page.setRotation(P.degrees((page.getRotation().angle+angle)%360));}await exportDocument(doc,'rotated.pdf');message('已旋转 '+indexes.size+' 页。');});
  $('#pdf-split').onclick=()=>run(async()=>{const f=selected();if(!f)throw Error('请先选择 PDF');const indexes=L.pageRange($('#pdf-range').value,f.count);if(indexes.length>200)throw Error('单次拆分最多 200 页，请分批处理');const doc=await load(f.bytes),zip={};for(let i=0;i<indexes.length;i++){const out=await P.PDFDocument.create();out.addPage((await out.copyPages(doc,[indexes[i]]))[0]);zip[String(i+1).padStart(3,'0')+'-page-'+(indexes[i]+1)+'.pdf']=await out.save();message('正在拆分 '+(i+1)+' / '+indexes.length);await new Promise(resolve=>setTimeout(resolve,0));}download(window.fflate.zipSync(zip,{level:1}),'application/zip','pages.zip');message('已逐页拆分为 ZIP。');});
  async function viewer(){if(!pdfjs){pdfjs=await import('./vendor/pdfjs/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('vendor/pdfjs/build/pdf.worker.mjs',document.baseURI).href;}return pdfjs;}
  async function getView(f){if(viewDoc&&viewKey===f.id)return viewDoc;const token=viewRevision,lib=await viewer();await queue;if(token!==viewRevision)throw Error('页面预览已取消。');const task=lib.getDocument({data:f.bytes.slice(),cMapUrl:new URL('vendor/pdfjs/cmaps/',document.baseURI).href,cMapPacked:true,standardFontDataUrl:new URL('vendor/pdfjs/standard_fonts/',document.baseURI).href,wasmUrl:new URL('vendor/pdfjs/wasm/',document.baseURI).href,isEvalSupported:false});viewTask=task;try{const doc=await task.promise;if(token!==viewRevision)throw Error('页面预览已取消。');viewDoc=doc;viewKey=f.id;return doc;}catch(e){if(viewTask===task)invalidateView();throw e;}}
  function preview(){return run(async()=>{const f=selected();if(!f)throw Error('请先选择 PDF');const number=Number($('#pdf-page').value),scale=Number($('#pdf-scale').value);if(!Number.isInteger(number)||number<1||number>f.count)throw Error('页码范围：1–'+f.count);previewReady=false;renderTask?.cancel();const token=++viewRevision;message('正在生成第 '+number+' 页预览……');const doc=await getView(f);if(token!==viewRevision)return;const page=await doc.getPage(number),viewport=page.getViewport({scale});if(viewport.width*viewport.height>24000000)throw Error('页面尺寸过大，请降低输出分辨率');const canvas=$('#pdf-preview');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport});await renderTask.promise;renderTask=null;if(token!==viewRevision)return;previewReady=true;canvas.hidden=false;$('#pdf-empty').hidden=true;message('第 '+number+' / '+f.count+' 页 · '+Math.round(scale*72)+' DPI。');});}
  $('#pdf-preview-button').onclick=preview;for(const id of ['pdf-page','pdf-scale'])$('#'+id).onchange=()=>{previewReady=false;controls();};
  $('#pdf-image').onclick=()=>run(async()=>{if(!previewReady)throw Error('请先预览当前页');const blob=await new Promise(resolve=>$('#pdf-preview').toBlob(resolve,'image/png'));if(!blob)throw Error('页面图片导出失败');download(blob,'image/png','page-'+$('#pdf-page').value+'.png');message('页面已导出为 PNG。');});
  $('#pdf-text').onclick=()=>run(async()=>{const f=selected();if(!f)throw Error('请先选择 PDF');if(f.count>500)throw Error('全文提取单次最多 500 页');const doc=await getView(f),parts=[];for(let i=1;i<=doc.numPages;i++){message('正在提取 '+i+' / '+doc.numPages+' 页文本……');const page=await doc.getPage(i),data=await page.getTextContent();parts.push('--- 第 '+i+' 页 ---\n'+data.items.map(item=>item.str+(item.hasEOL?'\n':' ')).join(''));}download(parts.join('\n\n'),'text/plain;charset=utf-8','pdf-text.txt');message('已提取文本。扫描件需要 OCR，此工具不会识别图片中的文字。');});
  $('#pdf-images-export').onclick=()=>run(async()=>{const input=[...$('#pdf-images').files];if(!input.length)throw Error('请选择图片');if(input.length>50||input.reduce((n,f)=>n+f.size,0)>80*1024*1024)throw Error('最多 50 张图片，总大小不超过 80 MB');const out=await P.PDFDocument.create();for(const file of input){message('正在加入 '+file.name+'……');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('只支持 PNG、JPEG 或 WebP');const url=URL.createObjectURL(file),image=new Image();try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('无法读取图片 '+file.name));image.src=url;});if(image.width*image.height>24000000)throw Error('图片过大，请控制在 2400 万像素以内');const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d').drawImage(image,0,0);const data=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!data)throw Error('图片转换失败');const embedded=await out.embedPng(await data.arrayBuffer());let w=image.width*.75,h=image.height*.75;if($('#pdf-paper').value==='a4'){[w,h]=image.width>image.height?[841.89,595.28]:[595.28,841.89];}const page=out.addPage([w,h]),margin=$('#pdf-paper').value==='a4'?24:0,scale=Math.min((w-margin*2)/image.width,(h-margin*2)/image.height),dw=image.width*scale,dh=image.height*scale;page.drawImage(embedded,{x:(w-dw)/2,y:(h-dh)/2,width:dw,height:dh});}finally{URL.revokeObjectURL(url);}}await exportDocument(out,'images.pdf');message('已将 '+input.length+' 张图片生成 PDF，顺序与选择文件一致。');});
  document.addEventListener('site:pagechange',e=>{if(e.detail.page!=='tools'||e.detail.section!=='pdf')invalidateView();});window.addEventListener('pagehide',invalidateView);controls();
})();
