(() => {
  'use strict';const $=s=>document.querySelector(s),L=window.PlusLogic;
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
  async function copy(input,status){try{if(!input.value)throw Error('没有可复制的内容');await navigator.clipboard.writeText(input.value);status.textContent='已复制。';}catch{input.focus();input.select();status.textContent='请手动复制选中的内容。';}}
  function convertRadix(){try{const result=L.radix($('#radix-input').value,$('#radix-from').value,$('#radix-to').value);$('#radix-output').value=result.value;$('#radix-status').textContent=result.approximate?'小数已截取为 20 位，结果为近似值。':'转换完成，结果精确。';}catch(e){$('#radix-output').value='';$('#radix-status').textContent=e.message;}}
  $('#radix-convert').onclick=convertRadix;for(const id of ['radix-input','radix-from','radix-to'])$('#'+id).oninput=convertRadix;
  $('#radix-swap').onclick=()=>{if(!$('#radix-output').value)return;const from=$('#radix-from'),to=$('#radix-to');[from.value,to.value]=[to.value,from.value];$('#radix-input').value=$('#radix-output').value;convertRadix();};$('#radix-copy').onclick=()=>copy($('#radix-output'),$('#radix-status'));convertRadix();

  function xmlRead(text){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length||/<!DOCTYPE/i.test(text))throw Error('XML 格式错误或包含不支持的 DOCTYPE');function walk(node){return {name:node.nodeName,attributes:Object.fromEntries([...node.attributes].map(a=>[a.name,a.value])),content:[...node.childNodes].filter(n=>n.nodeType===1||n.nodeType===3&&n.nodeValue.trim()||n.nodeType===4).map(n=>n.nodeType===1?walk(n):n.nodeValue)};}return walk(doc.documentElement);}
  function xmlWrite(value){const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');let nodes=0;function write(node,depth=0){if(++nodes>100000||depth>100)throw Error('XML 节点过多或嵌套过深');if(!node||typeof node!=='object'||!/^[:A-Z_a-z][:A-Z_a-z0-9.\-]*$/.test(node.name)||!Array.isArray(node.content))throw Error('XML 需要节点结构：{"name":"root","attributes":{},"content":["文本"]}');const attributes=Object.entries(node.attributes||{}).map(([k,v])=>{if(!/^[:A-Z_a-z][:A-Z_a-z0-9.\-]*$/.test(k))throw Error('XML 属性名称无效');return ' '+k+'="'+esc(v)+'"';}).join('');return '<'+node.name+attributes+'>'+node.content.map(c=>typeof c==='object'?write(c,depth+1):esc(c)).join('')+'</'+node.name+'>';}
    const out='<?xml version="1.0" encoding="UTF-8"?>\n'+write(value);xmlRead(out);return out;}
  let converted=null;
  function boundedData(value){let nodes=0;const ancestors=new Set();function visit(node,depth){if(++nodes>100000||depth>100)throw Error('数据节点过多或嵌套超过 100 层');if(node===null||typeof node!=='object')return;if(ancestors.has(node))throw Error('数据包含循环引用，请展开或移除 YAML 别名');ancestors.add(node);for(const child of Object.values(node))visit(child,depth+1);ancestors.delete(node);}visit(value,0);}
  function invalidate(){converted=null;$('#data-download').disabled=true;$('#data-output').value='';$('#data-status').textContent='输入已改变，请重新转换。';}
  for(const id of ['data-input','data-from','data-to'])$('#'+id).oninput=invalidate;
  function dataConvert(){try{const text=$('#data-input').value;if(!text.trim()||text.length>2000000)throw Error('请输入 200 万字符以内的内容');let data;const from=$('#data-from').value,to=$('#data-to').value;
      if(from==='json')data=JSON.parse(text);else if(from==='yaml')data=window.jsyaml.load(text,{schema:window.jsyaml.JSON_SCHEMA});else if(from==='xml')data=xmlRead(text);else data=L.csvParse(text,from==='csv'?',':'\t');
      boundedData(data);let output;if(to==='json')output=JSON.stringify(data,null,2);else if(to==='yaml')output=window.jsyaml.dump(data,{noRefs:true,lineWidth:100});else if(to==='xml')output=xmlWrite(data);else output=L.csvWrite(data,to==='csv'?',':'\t');
      if(typeof output!=='string'||output.length>5000000)throw Error('输出为空或超过大小限制');converted={text:output,type:to};$('#data-output').value=output;$('#data-download').disabled=false;$('#data-status').textContent='转换完成。';
    }catch(e){converted=null;$('#data-output').value='';$('#data-download').disabled=true;$('#data-status').textContent='无法转换：'+e.message;}}
  $('#data-convert').onclick=dataConvert;$('#data-copy').onclick=()=>copy($('#data-output'),$('#data-status'));
  $('#data-download').onclick=()=>{if(converted)download(new Blob([converted.text],{type:'text/plain;charset=utf-8'}),'converted.'+converted.type);};
  $('#data-swap').onclick=()=>{if(!converted)return;const from=$('#data-from'),to=$('#data-to');[from.value,to.value]=[to.value,from.value];$('#data-input').value=converted.text;invalidate();};
  $('#data-file').onchange=async()=>{const file=$('#data-file').files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('文本文件须小于 2 MB');const ext=file.name.split('.').pop().toLowerCase(),type=ext==='yml'?'yaml':ext;if(['json','yaml','csv','tsv','xml'].includes(type))$('#data-from').value=type;$('#data-input').value=await file.text();invalidate();}catch(e){$('#data-status').textContent=e.message;}};

  // Browser microphone levels. Sampling and statistical intervals do not cap rendering.
  let stream=null,audio=null,analyser=null,samples=null,frame=0,serial=0,lastSample=0,current=-100,averageEnergy=0,count=0,max=-100,offset=null,records=[],history=[];
  const active=()=>!$('#page-tools').hidden&&!$('#tool-decibel').hidden&&!$('#tools-workspace').hidden;
  let soundMode='estimate';$('#sound-mode').value=soundMode;
  const defaultOffset=100,estimatedMode=()=>soundMode==='estimate',effectiveOffset=()=>offset??defaultOffset;
  const value=db=>Math.max(-100,db)+(estimatedMode()?effectiveOffset():0),unit=()=>!estimatedMode()?'dBFS':offset===null?'dB（未校准估算）':'dB SPL（估算）';
  const measurementMessage=()=>!estimatedMode()?'测量中：显示麦克风数字电平 dBFS，负数正常。':offset===null?'测量中：使用默认 +100 dB 补偿，显示未校准估算值。':'测量中：显示参考读数校准后的估算环境分贝。';
  function soundStats(){const avg=count?10*Math.log10(Math.max(1e-10,averageEnergy/count)):-100;$('#sound-average').textContent=count?value(avg).toFixed(1)+' '+unit():'—';$('#sound-max').textContent=count?value(max).toFixed(1)+' '+unit():'—';$('#sound-time').textContent=(count/10).toFixed(1)+' 秒';$('#sound-csv').disabled=!records.length;}
  function chart(){const canvas=$('#sound-chart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#7da7ab44';ctx.lineWidth=1;for(let db=-80;db<=0;db+=20){const y=h-15+(db/100)*(h-30);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}if(!history.length)return;ctx.strokeStyle='#a7d8bf';ctx.lineWidth=2;ctx.beginPath();history.forEach((db,i)=>{const x=i/599*w,y=h-15+(Math.max(-100,Math.min(0,db))/100)*(h-30);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}
  function display(){const v=value(current);$('#sound-value').textContent=stream?v.toFixed(1):'—';$('#sound-unit').textContent=unit();$('#sound-label').textContent=!estimatedMode()?'麦克风数字电平':offset===null?'环境分贝估算 · 未校准':'环境分贝 · 已校准估算';$('#sound-help').textContent=!estimatedMode()?'负数正常：数字电平越接近 0 声音越强。可切换到环境分贝估算模式；参考校准设置会保留。':offset===null?'使用默认 +100 dB 补偿，仅作相对参考，不能当作真实环境声压级。填写参考声级计读数并校准后，可改善估算。':(stream?'当前麦克风数字电平 '+current.toFixed(1)+' dBFS。':'')+'环境分贝根据本次参考读数校准估算；请保持麦克风位置和输入音量设置不变。';$('#sound-uncalibrate').disabled=offset===null;$('#sound-calibrate').textContent=offset===null?'校准为环境分贝':'重新校准环境分贝';$('#sound-fill').style.width=Math.min(100,Math.max(0,100+current))+'%';$('#sound-meter').setAttribute('aria-valuenow',current.toFixed(1));soundStats();chart();}
  function tick(now){frame=0;if(!stream||!active()||document.hidden){stop();return;}analyser.getFloatTimeDomainData(samples);const raw=L.soundLevel(samples);current=current*.7+raw*.3;
    if(now-lastSample>=100){lastSample=now;count++;averageEnergy+=10**(raw/10);max=Math.max(max,raw);history.push(raw);if(history.length>600)history.shift();records.push({seconds:count/10,dbfs:raw});if(records.length>36000){stop('已测量一小时，请导出数据后重新开始。');return;}display();}
    chart();frame=requestAnimationFrame(tick);}
  function stop(message='麦克风已关闭。'){serial++;cancelAnimationFrame(frame);frame=0;stream?.getTracks().forEach(t=>t.stop());stream=null;analyser=null;samples=null;const old=audio;audio=null;old?.close().catch(()=>{});$('#sound-start').disabled=false;$('#sound-stop').disabled=true;$('#sound-calibrate').disabled=true;$('#sound-status').textContent=message;display();}
  $('#sound-start').onclick=async()=>{if(!active())return;stop('等待麦克风授权……');const token=++serial;$('#sound-start').disabled=true;
    try{if(!navigator.mediaDevices?.getUserMedia)throw Error('需要 HTTPS 或 localhost，并使用支持麦克风的浏览器');const input=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});if(token!==serial||!active()||document.hidden){input.getTracks().forEach(t=>t.stop());return;}stream=input;audio=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();if(token!==serial)return;analyser=audio.createAnalyser();analyser.fftSize=2048;audio.createMediaStreamSource(stream).connect(analyser);samples=new Float32Array(analyser.fftSize);$('#sound-stop').disabled=false;$('#sound-calibrate').disabled=false;$('#sound-status').textContent=measurementMessage();lastSample=performance.now();frame=requestAnimationFrame(tick);
    }catch(e){if(token===serial)stop(e.name==='NotAllowedError'?'麦克风权限未获允许。':e.name==='NotFoundError'?'未找到麦克风。':e.message||'麦克风无法开启。');}};
  $('#sound-stop').onclick=()=>stop();$('#sound-reset').onclick=()=>{count=0;averageEnergy=0;max=-100;records=[];history=[];display();};
  $('#sound-mode').onchange=()=>{soundMode=$('#sound-mode').value==='digital'?'digital':'estimate';display();if(stream)$('#sound-status').textContent=measurementMessage();};
  function setSoundMode(mode){soundMode=mode;$('#sound-mode').value=mode;$('#sound-mode').dispatchEvent(new Event('change',{bubbles:true}));}
  window.addEventListener('pageshow',()=>setSoundMode(soundMode));
  $('#sound-calibrate').onclick=()=>{try{if(!stream||!count||current<=-90)throw Error('请先测量稳定且可辨识的声音，再填写参考仪器读数');if(!$('#sound-reference').value.trim())throw Error('请填写参考读数');offset=L.calibration(current,Number($('#sound-reference').value));setSoundMode('estimate');$('#sound-status').textContent='本次页面已校准；结果为估算声压级。';}catch(e){$('#sound-status').textContent=e.message;}};
  $('#sound-uncalibrate').onclick=()=>{offset=null;setSoundMode('estimate');$('#sound-status').textContent='已恢复默认 +100 dB 补偿；显示未校准估算值。';};
  $('#sound-csv').onclick=()=>{if(records.length)download(new Blob([L.csvWrite(records.map(r=>({seconds:r.seconds,dbfs:r.dbfs,estimated:r.dbfs+effectiveOffset(),offset_db:effectiveOffset(),calibration:offset===null?'default_uncalibrated':'reference_calibrated'})))],{type:'text/csv;charset=utf-8'}),'sound-levels.csv');};
  document.addEventListener('hub:selection',e=>{if(e.detail.kind==='tool'&&e.detail.name!=='decibel')stop();});document.addEventListener('site:pagechange',e=>{if(e.detail.page!=='tools'||e.detail.section!=='decibel')stop();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',()=>stop());display();
})();
