(() => {
  const $=s=>document.querySelector(s),dialog=$('#site-search-dialog'),input=$('#site-search-input'),results=$('#site-search-results');let category='all',previous=null;
  const aliases={model:'3d 模型 glb gltf obj stl ply fbx 黑洞',bpm:'bpm 节拍 节奏 音乐 速度 测速 节拍器',garden:'羊了个羊 羊羊 三消 消除 叠牌',tower:'魔塔 冒险 rpg',scratch:'刮刮乐 彩票 金币 兑换',fishing:'钓鱼 捕鱼 海洋',coral:'珊瑚 气泡 救援',dino:'恐龙 google 谷歌',calculator:'计算器 单位 贷款 bmi 进制 汇率',crypto:'编码 加密 base64 摩斯',pdf:'pdf 合并 拆分 文档',qr:'二维码 扫码'};
  const entries=[...document.querySelectorAll('#games-directory .directory-card,#tools-directory .directory-card')].map(card=>{const href=card.getAttribute('href'),id=href.split('/')[1],kind=href.startsWith('#games')?'games':'tools',title=card.querySelector('h2').textContent,description=card.querySelector('p')?.textContent||'';return {href,id,kind,title,description,terms:(title+' '+description+' '+id+' '+(aliases[id]||'')).toLowerCase()};});
  function render(){const terms=input.value.trim().toLowerCase().split(/\s+/).filter(Boolean),list=entries.filter(e=>(category==='all'||e.kind===category)&&terms.every(t=>e.terms.includes(t))).sort((a,b)=>Number(b.title.toLowerCase().includes(input.value.toLowerCase()))-Number(a.title.toLowerCase().includes(input.value.toLowerCase())));results.replaceChildren();$('#site-search-count').textContent=list.length?'找到 '+list.length+' 个入口':'没有找到结果，试试名称、格式或功能关键词。';for(const entry of list){const a=document.createElement('a');a.href=entry.href;a.textContent=entry.title;const small=document.createElement('small');small.textContent=(entry.kind==='games'?'游戏':'工具')+' · '+entry.description;a.append(small);a.onclick=()=>close(false);results.append(a);}}
  let scrollLock=null,restoreFocus=true;
  function unlock(){if(!scrollLock)return;for(const [element,css] of scrollLock)element.style.cssText=css;scrollLock=null;}
  function open(){if(dialog.open)return;previous=document.activeElement;restoreFocus=true;dialog.showModal();scrollLock=[document.documentElement,document.body].map(el=>[el,el.style.cssText]);document.documentElement.style.overflow='hidden';document.documentElement.style.scrollbarGutter='stable';document.body.style.overflow='hidden';render();input.focus({preventScroll:true});input.select();}
  function close(restore=true){restoreFocus=restore;dialog.close();unlock();if(restore)previous?.focus({preventScroll:true});}
  // Native modal dialogs isolate focus, but do not automatically lock document scrolling.
  document.addEventListener('wheel',event=>{if(!dialog.open)return;const area=event.target.closest?.('#site-search-results');if(!area||event.deltaY<0&&area.scrollTop<=0||event.deltaY>0&&area.scrollTop+area.clientHeight>=area.scrollHeight-1)event.preventDefault();},{capture:true,passive:false});
  document.addEventListener('touchmove',event=>{if(dialog.open&&!event.target.closest?.('#site-search-results'))event.preventDefault();},{capture:true,passive:false});
  dialog.addEventListener('close',()=>{if(dialog.open)return;unlock();if(restoreFocus)previous?.focus({preventScroll:true});});
  $('#site-search-open').onclick=open;$('#site-search-close').onclick=()=>close();dialog.addEventListener('cancel',()=>{restoreFocus=true;});input.addEventListener('input',render);document.querySelectorAll('[data-search-kind]').forEach(b=>b.onclick=()=>{category=b.dataset.searchKind;document.querySelectorAll('[data-search-kind]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));render();input.focus();});
  dialog.addEventListener('keydown',e=>{if(e.isComposing)return;const links=[...results.querySelectorAll('a')],index=links.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();links[Math.max(0,Math.min(links.length-1,index+(e.key==='ArrowDown'?1:-1)))]?.focus();}if(e.key==='Enter'&&document.activeElement===input){e.preventDefault();links[0]?.click();}});
})();
