(() => {
  'use strict';const L=window.ExtraLogic,$=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
  let mode='basic';all('[data-calc]').forEach(b=>{b.onclick=()=>{mode=b.dataset.calc;all('[data-calc]').forEach(x=>{x.setAttribute('aria-selected',x===b);x.tabIndex=x===b?0:-1;});all('.calc-panel').forEach(p=>p.hidden=p.id!==`calc-${mode}`);};b.onkeydown=e=>{const buttons=all('[data-calc]'),index=buttons.indexOf(b);if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[n].click();buttons[n].focus();}};});
  const number=id=>{const input=$('#'+id);if(!input.value.trim())throw Error('请填写所有数值');const n=Number(input.value);if(!Number.isFinite(n))throw Error('请输入有效数值');return n;};
  function output(id,fn){const out=$('#'+id);try{out.textContent=fn();out.classList.remove('error');}catch(e){out.textContent=e.message;out.classList.add('error');}}
  const money=n=>new Intl.NumberFormat('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
  function bmi(){output('bmi-result',()=>L.bmi(number('bmi-height'),number('bmi-weight')).toFixed(2));}
  function loan(){output('loan-result',()=>{const r=L.loan(number('loan-amount'),number('loan-rate'),number('loan-months'),$('#loan-method').value);return ($('#loan-method').value==='annuity'?`每月 ${money(r.first)} 元`:`首月 ${money(r.first)} 元 / 末月 ${money(r.last)} 元`)+`\n总利息 ${money(r.interest)} 元\n还款总额 ${money(r.total)} 元`;});}
  function exchange(){output('exchange-result',()=>{const amount=number('exchange-amount'),rate=number('exchange-rate');if(amount<0||amount>1e15||rate<=0||rate>1e9)throw Error('金额须非负，汇率须大于零');const result=amount*rate;if(!Number.isFinite(result))throw Error('结果超出范围');return `${money(amount)} ${$('#exchange-from').value} = ${money(result)} ${$('#exchange-to').value}`;});}
  ['bmi-height','bmi-weight'].forEach(id=>$('#'+id).oninput=bmi);['loan-amount','loan-rate','loan-months','loan-method'].forEach(id=>$('#'+id).oninput=loan);['exchange-amount','exchange-rate','exchange-from','exchange-to'].forEach(id=>$('#'+id).oninput=exchange);
  $('#exchange-from').value='USD';$('#exchange-to').value='CNY';$('#exchange-rate').value='';$('#exchange-rate').placeholder='填写你要使用的汇率';
  $('#exchange-swap').onclick=()=>{try{const rate=number('exchange-rate');if(rate<=0)throw Error('先填写大于零的汇率');const from=$('#exchange-from');[from.value,$('#exchange-to').value]=[$('#exchange-to').value,from.value];$('#exchange-rate').value=String(1/rate);exchange();}catch(e){$('#exchange-result').textContent=e.message;}};bmi();loan();exchange();
  function color(){try{const value=L.color($('#color-input').value);$('#color-status').textContent='';$('#color-swatch').style.background=value.hex;$('#color-picker').value=value.hex;$('#color-values').replaceChildren();Object.entries(value).forEach(([label,text])=>{const row=document.createElement('div'),name=document.createElement('span'),code=document.createElement('code'),button=document.createElement('button');name.textContent=label.toUpperCase();code.textContent=text;button.className='button secondary';button.textContent='复制';button.setAttribute('aria-label',`复制 ${label.toUpperCase()}`);button.onclick=async()=>{try{await navigator.clipboard.writeText(text);$('#color-status').textContent=`已复制 ${label.toUpperCase()}`;}catch{$('#color-status').textContent='请选中颜色值手动复制。';}};row.append(name,code,button);$('#color-values').append(row);});}catch(e){$('#color-status').textContent=e.message;}}
  $('#color-input').oninput=color;$('#color-picker').oninput=()=>{$('#color-input').value=$('#color-picker').value;color();};color();

  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
  function canvasBlob(canvas,type){return new Promise((resolve,reject)=>canvas.toBlob(blob=>{if(!blob)reject(Error('导出失败，请缩小图片'));else if(blob.type!==type)reject(Error('当前浏览器不支持此导出格式'));else resolve(blob);},type,.92));}
  async function readImage(file){if(!file)throw Error('请选择图片');if(!['image/png','image/jpeg','image/webp','image/gif','image/bmp','image/avif','image/x-ms-bmp'].includes(file.type))throw Error('请选择浏览器支持的 PNG、JPEG、WebP、GIF、BMP 或 AVIF 图片');if(file.size>20*1024*1024)throw Error('请选择小于 20 MB 的图片');const url=URL.createObjectURL(file),img=new Image();try{await new Promise((res,rej)=>{img.onload=res;img.onerror=()=>rej(Error('图片无法读取'));img.src=url;});if(img.width*img.height>40000000)throw Error('图片像素过大，请选择小于 4000 万像素的图片');return img;}finally{URL.revokeObjectURL(url);}}
  const extension=type=>({ 'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/bmp':'bmp','image/avif':'avif'}[type]);
  let formatImage=null,formatSerial=0;$('#format-download').disabled=true;
  $('#format-file').onchange=async()=>{const serial=++formatSerial;formatImage=null;$('#format-download').disabled=true;try{const img=await readImage($('#format-file').files[0]);if(serial!==formatSerial)return;formatImage=img;$('#format-status').textContent=`${img.width} × ${img.height}，已准备转换。`;$('#format-download').disabled=false;}catch(e){if(serial===formatSerial)$('#format-status').textContent=e.message;}};
  $('#format-download').onclick=async()=>{if(!formatImage)return;const button=$('#format-download');button.disabled=true;try{const canvas=document.createElement('canvas');canvas.width=formatImage.width;canvas.height=formatImage.height;const ctx=canvas.getContext('2d'),type=$('#format-type').value;if(type==='image/jpeg'||type==='image/bmp'){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);}ctx.drawImage(formatImage,0,0);download(type==='image/bmp'?new Blob([window.PlusLogic.bmp(ctx.getImageData(0,0,canvas.width,canvas.height))],{type:'image/bmp'}):await canvasBlob(canvas,type),'converted.'+extension(type));$('#format-status').textContent='转换完成，已下载。';}catch(e){$('#format-status').textContent=e.message;}finally{button.disabled=!formatImage;}};
  function jsonFormat(pretty){try{const input=$('#format-json');if(!input.value.trim())throw Error('请先输入 JSON');if(input.value.length>2000000)throw Error('JSON 太大，请控制在 200 万字符以内');input.value=JSON.stringify(JSON.parse(input.value),null,pretty?2:0);$('#json-status').textContent=pretty?'已格式化。':'已压缩。';}catch(e){$('#json-status').textContent='无法处理：'+e.message;}}
  $('#json-pretty').onclick=()=>jsonFormat(true);$('#json-compact').onclick=()=>jsonFormat(false);$('#json-download').onclick=()=>{try{const text=$('#format-json').value;JSON.parse(text);download(new Blob([text],{type:'application/json'}),'formatted.json');$('#json-status').textContent='已下载 JSON。';}catch{$('#json-status').textContent='请输入有效的 JSON 后再下载。';}};

  let image=null,imageAngle=0,imageFlip=false,imageSerial=0;const canvas=$('#image-canvas');$('#image-download').disabled=true;
  function imageRender(){if(!image)return false;try{const x=number('image-x'),y=number('image-y'),w=number('image-crop-w'),h=number('image-crop-h'),width=number('image-width'),height=number('image-height');if(![x,y,w,h,width,height].every(Number.isInteger)||x<0||y<0||w<1||h<1||x+w>image.width||y+h>image.height)throw Error('裁剪区域须在原图内，坐标和尺寸须为整数');if(width<1||height<1||width>4096||height>4096)throw Error('导出尺寸范围为 1–4096 像素');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if($('#image-type').value==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);}ctx.save();ctx.translate(width/2,height/2);ctx.rotate(imageAngle*Math.PI/180);ctx.scale(imageFlip?-1:1,1);const rotated=imageAngle%180!==0;ctx.drawImage(image,x,y,w,h,-(rotated?height:width)/2,-(rotated?width:height)/2,rotated?height:width,rotated?width:height);ctx.restore();$('#image-status').textContent=`预览 ${width} × ${height}`;$('#image-download').disabled=false;return true;}catch(e){$('#image-status').textContent=e.message;$('#image-download').disabled=true;return false;}}
  function imageReset(){if(!image)return;imageAngle=0;imageFlip=false;$('#image-x').value=$('#image-y').value=0;$('#image-crop-w').value=image.width;$('#image-crop-h').value=image.height;const scale=Math.min(1,4096/Math.max(image.width,image.height));$('#image-width').value=Math.max(1,Math.round(image.width*scale));$('#image-height').value=Math.max(1,Math.round(image.height*scale));imageRender();}
  $('#image-file').onchange=async()=>{const serial=++imageSerial;image=null;$('#image-download').disabled=true;canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);try{const img=await readImage($('#image-file').files[0]);if(serial!==imageSerial)return;image=img;$('#image-info').textContent=`原图 ${img.width} × ${img.height}`;imageReset();}catch(e){if(serial===imageSerial)$('#image-status').textContent=e.message;}};
  ['image-x','image-y','image-crop-w','image-crop-h','image-width','image-height','image-type'].forEach(id=>$('#'+id).oninput=imageRender);
  $('#image-rotate').onclick=()=>{if(!image)return;imageAngle=(imageAngle+90)%360;const w=$('#image-width');[w.value,$('#image-height').value]=[$('#image-height').value,w.value];imageRender();};$('#image-flip').onclick=()=>{imageFlip=!imageFlip;imageRender();};$('#image-reset').onclick=imageReset;
  $('#image-download').onclick=async()=>{if(!imageRender())return;try{const type=$('#image-type').value;download(await canvasBlob(canvas,type),'edited.'+extension(type));$('#image-status').textContent='图片已下载。';}catch(e){$('#image-status').textContent=e.message;}};
  $('#image-status').textContent='选择图片后开始编辑。';

  let qrReady=false;const qrCanvas=$('#qr-canvas');window.qrcode.stringToBytes=text=>Array.from(new TextEncoder().encode(text));
  function qrGenerate(){qrReady=false;$('#qr-download').disabled=true;const ctx=qrCanvas.getContext('2d');ctx.clearRect(0,0,qrCanvas.width,qrCanvas.height);try{const text=$('#qr-input').value;if(!text.trim())throw Error('请输入二维码内容');if(new TextEncoder().encode(text).length>1500)throw Error('内容过长，请控制在 1500 字节以内');const qr=window.qrcode(0,'M');qr.addData(text);qr.make();const count=qr.getModuleCount(),scale=Math.max(4,Math.ceil(360/(count+8)));qrCanvas.width=qrCanvas.height=(count+8)*scale;ctx.fillStyle='#fff';ctx.fillRect(0,0,qrCanvas.width,qrCanvas.height);ctx.fillStyle='#112f3f';for(let y=0;y<count;y++)for(let x=0;x<count;x++)if(qr.isDark(y,x))ctx.fillRect((x+4)*scale,(y+4)*scale,scale,scale);qrReady=true;$('#qr-download').disabled=false;$('#qr-status').textContent='二维码已生成。';}catch(e){$('#qr-status').textContent=e.message;}}
  $('#qr-generate').onclick=qrGenerate;$('#qr-input').oninput=()=>{qrReady=false;$('#qr-download').disabled=true;$('#qr-status').textContent='内容已修改，请重新生成。';};$('#qr-download').onclick=async()=>{if(!qrReady)return;try{download(await canvasBlob(qrCanvas,'image/png'),'qrcode.png');}catch(e){$('#qr-status').textContent=e.message;}};qrGenerate();
})();
