(() => {
  'use strict';const T=window.TowerLogic,$=s=>document.querySelector(s);let state=T.fresh(),saved=null,walk=0,active=false;
  const grid=$('#tower-board'),status=$('#tower-status'),directions={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]};
  const shapes={hero:'M10 11V6h12v5M8 12h16v11H8zM6 30v-6h20v6M13 16h1m4 0h1M16 21v8',key:'M4 10a6 6 0 1 0 12 0 6 6 0 1 0-12 0M14 15l14 14m-6-6 4-4m-9-1 4-4',door:'M7 29V3h18v26M18 17h3M12 3v26',gem:'m5 10 6-6h10l6 6-11 18zM5 10h22M11 4l5 24L21 4',potion:'M12 3h8v8c15 16 1 22-8 17-9-5 0-12 0-17zM9 19h16',up:'M4 28h8v-8h8v-8h8V4M3 11l7-7 7 7M10 4v13',down:'M4 4h8v8h8v8h8v8M3 20l7 7 7-7M10 27V14',sword:'m7 27 16-19 4-5-5 1-19 20M6 19l8 8',shield:'m5 5 11-2 11 2v12c-2 7-7 11-11 13-4-2-9-6-11-13zM16 4v24',book:'M3 5c4-2 8-1 13 2 5-3 9-4 13-2v23c-5-2-9-2-13 1-4-3-8-3-13-1zM16 7v22',star:'m16 3 4 8 9 2-7 6 2 10-8-5-8 5 2-10-7-6 9-2z',feather:'M5 28 25 5M7 24C0 13 14 1 28 3c-1 15-9 22-21 21M14 17V8m0 9h10',wand:'M5 29 20 10m-6-5 7-3 7 3-7 9z',gold:'M5 16a11 11 0 1 0 22 0 11 11 0 1 0-22 0M12 12h8v8h-8z',npc:'M11 8a5 5 0 1 0 10 0 5 5 0 1 0-10 0M6 29l4-13h12l4 13zM16 16v13',shop:'m3 12 13-9 13 9zM7 14v13m9-13v13m9-13v13M3 29h26',monster:'M5 26V12l5-7 6 5 6-5 5 7v14zM10 15v3m12-3v3M11 23h10',slime:'M3 26c0-24 26-24 26 0zM10 19h1m10 0h1M13 24h6',bat:'M2 10 10 16 16 5 22 16 30 10 28 25 20 21 16 29 12 21 4 25zM12 16h1m6 0h1',skeleton:'M8 18V8c0-7 16-7 16 0v10l-5 3v8m-6-8v8M10 10h3v4h-3zm9 0h3v4h-3zM6 27h20',wizard:'m5 15 11-13 11 13zM10 17h12l5 13H5zM13 20h1m4 0h1',boss:'m4 8 6 4 6-8 6 8 6-4-3 19H7zM10 18h3m6 0h3'};
  Object.assign(shapes,{cross:'M12 3h8v9h9v8h-9v9h-8v-9H3v-8h9z',compass:'M3 16a13 13 0 1 0 26 0 13 13 0 1 0-26 0M12 12l11-3-3 11-11 3z',snow:'M16 2v28M4 9l24 14M4 23 28 9M12 5l4 4 4-4M12 27l4-4 4 4M5 14l5-1-1-5M27 18l-5 1 1 5'});
  const svg=n=>'<svg viewBox="0 0 32 32" aria-hidden="true"><path d="'+(shapes[n]||shapes.star)+'"/></svg>';
  const battleDialog=$('#tower-battle');let duel=null,battleTimer=0,battleSpeed=1;
  function appearance(t){
    if([0,97,98,99].includes(t))return ['floor',''];if(T.blocked(t))return [t===1?'wall':t===20?'void':t===19?'lava':'seal',''];
    if([2,3,4].includes(t))return ['door '+['yellow','blue','red'][t-2],'door'];if(t===115)return ['door seal','door'];
    if([6,7,8].includes(t))return ['key '+['yellow','blue','red'][t-6],'key'];if(t===9||t===10)return ['gem '+(t===9?'blue':'red'),'gem'];
    if(t===11||t===12||t===33)return ['potion '+(t===11?'red':'blue'),'potion'];if(t===13||t===14)return [t===13?'up':'down',t===13?'up':'down'];
    if(t>=71&&t<=75)return ['equipment','sword'];if(t>=76&&t<=80)return ['equipment','shield'];if(t===34)return ['item','book'];if(t===30||t===31)return ['item','feather'];if(t===39)return ['item','gold'];if(t>=201&&t<=203)return ['item','wand'];
    if((t>=40&&t<=70)||t===188||t===198){const e=T.enemy(state,t),id=e.id;return ['monster species-'+id,[0,1,3,11].includes(id)?'slime':[2,8,9].includes(id)?'bat':[4,5,16,22].includes(id)?'skeleton':[12,17,20,23,24].includes(id)?'wizard':[13,19,31,32].includes(id)?'boss':'monster'];}
    if(t===22)return ['shop','shop'];if([24,25,26,27,28,119,129].includes(t))return ['npc','npc'];return ['item','star'];
  }
  function stop(){clearTimeout(walk);walk=0;}
  function stepMove(dx,dy){if(duel)return false;const moved=T.move(state,dx,dy,Math.random,Date.now(),true);if(state.battle)startDuel();draw();return moved;}
  function move(dx,dy){stop();stepMove(dx,dy);}
  function go(x,y){stop();if(duel||state.battle)return;const steps=T.path(state,x,y);if(!steps){state.notice='先打开通路，或靠近要交互的格子。';draw();return;}const floor=state.floor;function step(){walk=0;if(location.hash!=='#games/tower'||document.hidden||state.won||state.lost||state.shop||state.floor!==floor||duel)return;const d=steps.shift();if(!d)return;stepMove(...d);if(steps.length&&state.floor===floor&&!duel)walk=setTimeout(step,60);}step();}
  function paintDuel(){if(!duel)return;$('#tower-duel-enemy-hp').textContent=String(duel.enemyHP);$('#tower-duel-hero-hp').textContent=String(state.hp);$('#tower-duel-enemy-bar').style.transform='scaleX('+Math.max(0,duel.enemyHP/duel.enemy.hp)+')';$('#tower-duel-hero-bar').style.transform='scaleX('+Math.max(0,Math.min(1,state.hp/Math.max(1,duel.startHP)))+')';$('#tower-battle-round').textContent=duel.rounds?'第 '+duel.rounds+' 回合':'准备交战';}
  function clearBattleEffects(){for(const n of ['enemy','hero']){$('#tower-duel-'+n).classList.remove('attacking','hurt','critical-hit');$('#tower-duel-'+n+'-damage').classList.remove('show','critical');}battleDialog.classList.remove('hero-strike','enemy-strike','magic-strike');}
  function animateHit(event){
    clearBattleEffects();void battleDialog.offsetWidth;const target=event.actor==='hero'?'enemy':'hero',label=$('#tower-duel-'+target+'-damage');label.textContent=(event.critical?'暴击 ':'')+(event.damage?'−'+event.damage:'防御');label.classList.toggle('critical',!!event.critical);label.classList.add('show');$('#tower-duel-'+target).classList.add('hurt');
    if(event.actor==='special')battleDialog.classList.add('magic-strike');else{$('#tower-duel-'+event.actor).classList.add('attacking');battleDialog.classList.add(event.actor+'-strike');}if(event.critical)$('#tower-duel-enemy').classList.add('critical-hit');
    $('#tower-battle-message').textContent=event.actor==='special'?(event.kind==='vampire'?'吸血':'魔法攻击')+'，勇者生命 −'+event.damage:event.actor==='hero'?(event.critical?'勇者暴击':'勇者攻击')+'，'+duel.enemy.name+'生命 −'+event.damage:event.damage?duel.enemy.name+'反击，勇者生命 −'+event.damage:'勇者完全防御了这次反击。';
  }
  function showBattleResult(){paintDuel();$('#tower-battle-title').textContent='战斗胜利';$('#tower-battle-message').textContent='击败'+duel.enemy.name+' · 损失 '+duel.loss+' 生命 · '+duel.critical+' 次暴击';const reward=$('#tower-battle-reward');reward.hidden=false;reward.textContent='金币 +'+duel.enemy.gold+' · 经验 +'+duel.enemy.exp;$('#tower-battle-next').textContent='继续探索';$('#tower-battle-speed').disabled=true;$('#tower-battle-next').focus({preventScroll:true});}
  function scheduleBattle(delay=380){clearTimeout(battleTimer);battleTimer=0;if(!state.battle||!duel||document.hidden||location.hash!=='#games/tower')return;battleTimer=setTimeout(battleFrame,delay/battleSpeed);}
  function battleFrame(){battleTimer=0;if(!duel||!state.battle||document.hidden||location.hash!=='#games/tower')return;const event=T.advanceBattle(state);animateHit(event);paintDuel();draw();if(event.done)showBattleResult();else scheduleBattle();}
  function startDuel(){
    stop();duel=state.battle;battleSpeed=1;clearBattleEffects();$('#tower-battle-title').textContent='战斗';$('#tower-duel-enemy-name').textContent=duel.enemy.name;$('#tower-duel-enemy-art').innerHTML=svg(appearance(duel.tile)[1]);$('#tower-duel-hero-art').innerHTML=svg('hero');$('#tower-duel-enemy-stats').textContent='攻击 '+duel.enemy.atk+' · 防御 '+duel.enemy.def;$('#tower-duel-hero-stats').textContent='攻击 '+duel.hero.atk+' · 防御 '+duel.hero.def;$('#tower-battle-message').textContent=duel.initial?'敌人正在施展特殊攻击。':'勇者先攻击，双方轮流出手。';$('#tower-battle-reward').hidden=true;$('#tower-battle-speed').disabled=false;$('#tower-battle-speed').textContent='加速 ×3';$('#tower-battle-speed').setAttribute('aria-pressed','false');$('#tower-battle-next').textContent='快速结算';paintDuel();battleDialog.showModal();scheduleBattle(450);
  }
  function finishFast(){clearTimeout(battleTimer);battleTimer=0;if(!duel)return;while(state.battle)T.advanceBattle(state);clearBattleEffects();showBattleResult();draw();}
  function closeDuel(settle=true,focus=true){clearTimeout(battleTimer);battleTimer=0;if(settle&&state.battle)while(state.battle)T.advanceBattle(state);duel=null;clearBattleEffects();if(battleDialog.open)battleDialog.close();draw();if(focus&&location.hash==='#games/tower')grid.focus({preventScroll:true});}
  $('#tower-battle-next').onclick=()=>{if(state.battle)finishFast();else closeDuel();};$('#tower-battle-speed').onclick=()=>{if(!state.battle)return;battleSpeed=battleSpeed===1?3:1;$('#tower-battle-speed').textContent=battleSpeed===3?'恢复速度':'加速 ×3';$('#tower-battle-speed').setAttribute('aria-pressed',String(battleSpeed===3));scheduleBattle();};
  battleDialog.addEventListener('cancel',e=>{e.preventDefault();closeDuel();});battleDialog.addEventListener('close',()=>{if(duel)closeDuel();});battleDialog.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target===battleDialog){e.preventDefault();$('#tower-battle-next').click();}});
  function draw(){
    $('#tower-stats').replaceChildren(...[T.title(state.floor),'等级 '+state.lv,'生命 '+state.hp,'攻击 '+state.atk,'防御 '+state.def,'金币 '+state.gold,'经验 '+state.exp,'黄钥匙 '+state.keys.yellow,'蓝钥匙 '+state.keys.blue,'红钥匙 '+state.keys.red].map(text=>{const s=document.createElement('span');s.textContent=text;return s;}));
    if(!grid.children.length)for(let i=0;i<121;i++){const b=document.createElement('button');b.type='button';b.dataset.cell=String(i);b.tabIndex=-1;b.onclick=()=>{grid.focus({preventScroll:true});go(i%11,Math.floor(i/11));};grid.append(b);}
    const locked=!!duel||!!state.battle,book=!!state.items.book;state.floors[state.floor].forEach((t,i)=>{const hero=i===T.index(state.x,state.y),b=grid.children[i],[cls,shape]=hero?['hero','hero']:appearance(t),art=shape?svg(shape):'';b.className='tower-tile '+cls;b.disabled=locked||T.blocked(t)||state.won||state.lost;const e=(t>=40&&t<=70)||t===188||t===198?T.enemy(state,t):null;b.title=hero?'勇者':e?e.name+(book?' · 生命 '+e.hp+' · 攻 '+e.atk+' · 防 '+e.def+' · 手册损失 '+(Number.isFinite(T.damage(state,e))?T.damage(state,e):'无法破防'):''):T.names[t]||'封印';b.setAttribute('aria-label',b.title+'，第 '+(Math.floor(i/11)+1)+' 行 '+(i%11+1)+' 列');if(b.dataset.art!==art){b.innerHTML=art;b.dataset.art=art;}});
    status.textContent=state.notice;$('#tower-shop').hidden=!state.shop;$('#tower-shop-options').replaceChildren(...T.offers(state).map((o,i)=>{const b=document.createElement('button');b.className='button secondary';b.textContent=o.text+' · '+o.amount+' '+({gold:'金币',exp:'经验',yellow:'黄钥匙',blue:'蓝钥匙',red:'红钥匙'}[o.cost]);b.disabled=!T.afford(state,o);b.onclick=()=>{T.buy(state,i);draw();};return b;}));
    const inventory=T.inventoryEntries(state),bag=$('#tower-inventory');bag.classList.toggle('empty',!inventory.length);bag.replaceChildren(...inventory.map(item=>{const row=document.createElement('span');row.className='tower-inventory-item '+item.id;row.dataset.item=item.id;row.title=item.description;row.innerHTML=svg(item.icon);const name=document.createElement('span');name.textContent=item.name;row.append(name);if(item.count>1){const count=document.createElement('small');count.textContent='×'+item.count;row.append(count);}return row;}));if(!inventory.length)bag.textContent='尚未获得特殊道具';
    $('#tower-enemies').replaceChildren(...(!book?[]:[...new Set(state.floors[state.floor].filter(t=>(t>=40&&t<=70)||t===188||t===198))].map(t=>{const e=T.enemy(state,t),row=document.createElement('div'),loss=T.damage(state,e);row.className='tower-enemy';row.innerHTML=svg(appearance(t)[1]);const p=document.createElement('p');p.textContent=e.name+' · 生命 '+e.hp+' · 攻 '+e.atk+' · 防 '+e.def;const note=document.createElement('small');note.textContent=Number.isFinite(loss)?'手册损失 '+loss+' · 金币 '+e.gold+' · 经验 '+e.exp:'无法破防';p.append(note);row.append(p);return row;})));
    $('#tower-book-note').hidden=book;$('#tower-load').disabled=!saved||locked;$('#tower-save').disabled=state.won||state.lost||locked;$('#tower-fly-controls').hidden=!state.items.fly;const fly=$('#tower-fly-floor'),available=state.visited.filter(f=>f>0&&f<=20&&f<Math.max(...state.visited)).sort((a,b)=>a-b),signature=available.join(',');if(fly.dataset.floors!==signature){const selected=fly.value;fly.replaceChildren(...available.map(f=>{const o=document.createElement('option');o.value=String(f);o.textContent=T.title(f);return o;}));if(available.includes(Number(selected)))fly.value=selected;fly.dataset.floors=signature;}fly.disabled=locked;$('#tower-fly').disabled=locked||state.floor===26||!fly.children.length;for(const b of document.querySelectorAll('[data-tower-move]'))b.disabled=locked||state.won||state.lost;
    clock();
  }
  function clock(){if(!active)return;const n=T.tick(state);$('#tower-time').textContent=String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');}
  function save(){if(duel||state.battle)return;stop();saved=T.snapshot(state);state.notice='已在本页暂存冒险；刷新或关闭页面后清空。';draw();}
  function load(){if(saved){stop();closeDuel(false,false);state=T.restore(saved);draw();}}
  for(const b of document.querySelectorAll('[data-tower-move]'))b.onclick=()=>{move(...directions[b.dataset.towerMove]);grid.focus({preventScroll:true});};
  $('#tower-reset').onclick=()=>{stop();closeDuel(false,false);state=T.fresh();active=true;draw();grid.focus({preventScroll:true});};$('#tower-save').onclick=save;$('#tower-load').onclick=load;$('#tower-shop-close').onclick=()=>{state.shop=null;draw();};$('#tower-fly').onclick=()=>{if(duel)return;stop();T.fly(state,Number($('#tower-fly-floor').value));draw();};
  document.addEventListener('keydown',e=>{if(e.defaultPrevented||location.hash!=='#games/tower'||document.querySelector('dialog[open]')||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const key={ArrowUp:'up',w:'up',ArrowRight:'right',d:'right',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left'}[e.key.length===1?e.key.toLowerCase():e.key];if(key){e.preventDefault();move(...directions[key]);}else if(e.key==='Escape'&&state.shop){state.shop=null;draw();}else if(e.key==='F5'){e.preventDefault();save();}else if(e.key==='F9'){e.preventDefault();load();}});
  function route(){stop();if(location.hash!=='#games/tower'&&duel)closeDuel(true,false);if(location.hash==='#games/tower'&&!active){state=T.fresh();active=true;draw();}}
  window.addEventListener('hashchange',route);document.addEventListener('visibilitychange',()=>{stop();clearTimeout(battleTimer);battleTimer=0;if(!document.hidden&&duel)scheduleBattle();});window.addEventListener('pagehide',()=>{stop();if(duel)closeDuel(true,false);});setInterval(()=>{if(location.hash==='#games/tower'&&!document.hidden)clock();},1000);draw();route();
})();
