(() => {
  'use strict';const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],L=window.UtilityLogic;
  function cryptoMode(){const aes=$('#crypto-mode').value.startsWith('aes-');$('#crypto-password-field').hidden=!aes;$('#crypto-run').textContent=$('#crypto-mode').value==='aes-decrypt'?'解密':aes?'加密':'开始处理';}
  let cryptoSerial=0;$('#crypto-mode').onchange=()=>{cryptoSerial++;$('#crypto-run').disabled=false;cryptoMode();};cryptoMode();
  $('#crypto-run').onclick=async()=>{const serial=++cryptoSerial;$('#crypto-run').disabled=true;$('#crypto-status').textContent='处理中……';try{const result=await L.process($('#crypto-mode').value,$('#crypto-input').value,$('#crypto-password').value);if(serial!==cryptoSerial)return;$('#crypto-output').value=result;$('#crypto-status').textContent='处理完成。';}catch(e){if(serial!==cryptoSerial)return;$('#crypto-output').value='';$('#crypto-status').textContent=e.message;}finally{if(serial===cryptoSerial)$('#crypto-run').disabled=false;}};
  $('#crypto-swap').onclick=()=>{if(!$('#crypto-output').value)return;$('#crypto-input').value=$('#crypto-output').value;const modes={'morse-encode':'morse-decode','morse-decode':'morse-encode','base64-encode':'base64-decode','base64-decode':'base64-encode','url-encode':'url-decode','url-decode':'url-encode','aes-encrypt':'aes-decrypt','aes-decrypt':'aes-encrypt'};if(modes[$('#crypto-mode').value])$('#crypto-mode').value=modes[$('#crypto-mode').value];cryptoSerial++;$('#crypto-run').disabled=false;cryptoMode();$('#crypto-status').textContent='结果已放入输入框。';};
  async function copy(selector,status){if(!$(selector).value){$(status).textContent='暂无可复制的内容。';return;}try{await navigator.clipboard.writeText($(selector).value);$(status).textContent='内容已复制。';}catch{$(selector).focus();$(selector).select();$(status).textContent='已选中内容，请手动复制。';}}
  $('#crypto-copy').onclick=()=>copy('#crypto-output','#crypto-status');

  const presets={beijing:{name:'北京',country:'中国',latitude:39.9042,longitude:116.4074},shanghai:{name:'上海',country:'中国',latitude:31.2304,longitude:121.4737},guangzhou:{name:'广州',country:'中国',latitude:23.1291,longitude:113.2644},shenzhen:{name:'深圳',country:'中国',latitude:22.5431,longitude:114.0579},chengdu:{name:'成都',country:'中国',latitude:30.5728,longitude:104.0668}};
  let selectedCity=presets.beijing,weatherController,weatherSerial=0,weatherLoaded=false,weatherActive=false,weatherLastFetch=0,weatherPending=false;
  const displayNumber=(value,suffix='')=>Number.isFinite(value)?`${Math.round(value*10)/10}${suffix}`:'暂无数据';
  async function fetchJson(url,signal){const response=await fetch(url,{signal,cache:'no-store'});if(!response.ok)throw Error('天气服务暂时不可用，请稍后重试');const data=await response.json();if(data.error)throw Error('天气数据暂时不可用');return data;}
  function requestStart(){weatherController?.abort();weatherController=new AbortController();const controller=weatherController,serial=++weatherSerial;const timeout=setTimeout(()=>controller.abort(),15000);return {controller,serial,done:()=>clearTimeout(timeout)};}
  function weatherError(error,serial){if(serial!==weatherSerial)return;$('#weather-status').textContent=error.name==='AbortError'?'请求超时，请检查网络后重试。':'无法获取天气，请检查网络后重试。';if(!weatherLoaded)$('#weather-result').hidden=true;else $('#weather-updated').textContent+=' · 当前请求失败，仍显示上次数据';}
  async function loadWeather(city=selectedCity){selectedCity=city;const req=requestStart();weatherPending=true;$('#weather-status').textContent=`正在获取${city.name}天气……`;$('#weather-refresh').disabled=true;try{const url=new URL('https://api.open-meteo.com/v1/forecast');url.search=new URLSearchParams({latitude:city.latitude,longitude:city.longitude,current:'temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max',timezone:'auto',forecast_days:'3'}).toString();const data=await fetchJson(url.href,req.controller.signal);if(req.serial!==weatherSerial)return;const current=data.current;if(!current||!Number.isFinite(current.temperature_2m)||!current.time)throw Error('数据不完整');$('#weather-location').textContent=[city.name,city.admin1,city.country].filter(Boolean).join(' · ');$('#weather-temp').textContent=displayNumber(current.temperature_2m,'°C');$('#weather-description').textContent=L.weatherName(current.weather_code);const details=$('#weather-details');details.replaceChildren();for(const [label,value] of [['体感',displayNumber(current.apparent_temperature,'°C')],['湿度',displayNumber(current.relative_humidity_2m,'%')],['风速',displayNumber(current.wind_speed_10m,' km/h')]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;details.append(dt,dd);}$('#weather-updated').textContent=`数据时间：${current.time.replace('T',' ')}（${data.timezone||'城市当地时间'}） · 当前天气为最新模型数据`;const days=$('#weather-days');days.replaceChildren();(data.daily?.time||[]).forEach((date,i)=>{const card=document.createElement('div'),name=document.createElement('span'),temp=document.createElement('strong'),desc=document.createElement('p');name.textContent=i===0?'今天':i===1?'明天':'后天';temp.textContent=`${displayNumber(data.daily.temperature_2m_min?.[i],'°')} / ${displayNumber(data.daily.temperature_2m_max?.[i],'°')}`;desc.textContent=`${date} · ${L.weatherName(data.daily.weather_code?.[i])} · 降水概率 ${displayNumber(data.daily.precipitation_probability_max?.[i],'%')}`;card.append(name,temp,desc);days.append(card);});$('#weather-result').hidden=false;weatherLoaded=true;weatherLastFetch=Date.now();$('#weather-status').textContent='天气已更新。';}catch(e){weatherError(e,req.serial);}finally{req.done();if(req.serial===weatherSerial){$('#weather-refresh').disabled=false;weatherPending=false;}}}
  async function searchCity(event){event?.preventDefault();const name=$('#weather-city').value.trim();if(name.length<2){$('#weather-status').textContent='请输入至少两个字或字母的城市名称。';return;}const preset=Object.values(presets).find(city=>city.name===name.replace(/市$/,''));if(preset){$('#weather-cities').replaceChildren();loadWeather(preset);return;}const req=requestStart();weatherPending=true;$('#weather-status').textContent='正在搜索城市……';$('#weather-refresh').disabled=true;try{const data={results:await CitySearch.search(name,{signal:req.controller.signal})};if(req.serial!==weatherSerial)return;const results=$('#weather-cities');results.replaceChildren();if(!data.results?.length){$('#weather-status').textContent='未找到城市，请检查中文名称或输入更完整的地名。';return;}for(const city of data.results){const button=document.createElement('button');button.textContent=[city.name,city.admin1,city.country].filter(Boolean).join(' · ');button.onclick=()=>{results.replaceChildren();$('#weather-city').value=city.name;loadWeather(city);};results.append(button);}$('#weather-status').textContent='请选择要查询的城市。';}catch(e){weatherError(e,req.serial);}finally{req.done();if(req.serial===weatherSerial){$('#weather-refresh').disabled=false;weatherPending=false;}}}
  $('#weather-search').onsubmit=searchCity;$('#weather-refresh').onclick=()=>loadWeather();all('[data-city]').forEach(b=>b.onclick=()=>{$('#weather-city').value=presets[b.dataset.city].name;$('#weather-cities').replaceChildren();loadWeather(presets[b.dataset.city]);});
  function updateWeatherActive(){weatherActive=!$('#page-tools').hidden&&!$('#tool-weather').hidden&&!$('#tools-workspace').hidden;if(weatherActive&&!weatherPending&&(!weatherLoaded||Date.now()-weatherLastFetch>600000))loadWeather();if(!weatherActive&&weatherPending){weatherController?.abort();weatherSerial++;weatherPending=false;$('#weather-refresh').disabled=false;}}
  document.addEventListener('hub:selection',()=>queueMicrotask(updateWeatherActive));document.addEventListener('site:pagechange',()=>queueMicrotask(updateWeatherActive));document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateWeatherActive();});setInterval(()=>{if(weatherActive&&!document.hidden&&!weatherPending)loadWeather();},600000);updateWeatherActive();

  let stream=null,cameraSerial=0,cameraFrame=0,lastScan=0,scanSerial=0;const video=$('#scan-video'),scanCanvas=document.createElement('canvas'),scanCtx=scanCanvas.getContext('2d',{willReadFrequently:true});
  function showScan(text){$('#scan-result').value=text;$('#scan-status').textContent='已识别二维码。';const link=$('#scan-open');link.hidden=true;link.removeAttribute('href');try{const url=new URL(text);if(['https:','http:'].includes(url.protocol)&&!url.username&&!url.password){link.href=url.href;link.hidden=false;}}catch{}}
  function stopCamera(message='摄像头已关闭。'){cameraSerial++;cancelAnimationFrame(cameraFrame);stream?.getTracks().forEach(track=>track.stop());stream=null;video.pause();video.srcObject=null;video.hidden=true;$('#scan-camera').disabled=false;$('#scan-stop').disabled=true;if(message)$('#scan-status').textContent=message;}
  function scanPixels(source,width,height){const scale=Math.min(1,1000/Math.max(width,height));scanCanvas.width=Math.max(1,Math.round(width*scale));scanCanvas.height=Math.max(1,Math.round(height*scale));scanCtx.fillStyle='#fff';scanCtx.fillRect(0,0,scanCanvas.width,scanCanvas.height);scanCtx.drawImage(source,0,0,scanCanvas.width,scanCanvas.height);const pixels=scanCtx.getImageData(0,0,scanCanvas.width,scanCanvas.height);return window.jsQR(pixels.data,pixels.width,pixels.height,{inversionAttempts:'attemptBoth'});}
  function cameraTick(now){if(!stream)return;if(now-lastScan>180&&video.readyState>=2){lastScan=now;const code=scanPixels(video,video.videoWidth,video.videoHeight);if(code){showScan(code.data);stopCamera(null);return;}}cameraFrame=requestAnimationFrame(cameraTick);}
  $('#scan-camera').onclick=async()=>{stopCamera(null);const serial=++cameraSerial;$('#scan-camera').disabled=true;$('#scan-status').textContent='等待摄像头授权……';try{if(!navigator.mediaDevices?.getUserMedia)throw Error('此环境无法使用摄像头，请在 HTTPS 网站中打开，或选择图片扫码');const current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});if(serial!==cameraSerial){current.getTracks().forEach(t=>t.stop());return;}stream=current;video.srcObject=current;video.hidden=false;await video.play();if(serial!==cameraSerial)return;$('#scan-stop').disabled=false;$('#scan-status').textContent='将二维码放入画面，识别成功后摄像头自动关闭。';lastScan=0;cameraFrame=requestAnimationFrame(cameraTick);}catch(e){if(serial!==cameraSerial)return;stopCamera(e.name==='NotAllowedError'?'摄像头未获授权，可改用图片扫码。':e.name==='NotFoundError'?'未找到摄像头，可改用图片扫码。':e.message||'摄像头无法开启，请使用图片扫码。');}};
  $('#scan-stop').onclick=()=>stopCamera();
  $('#scan-file').onchange=async()=>{stopCamera(null);const serial=++scanSerial,file=$('#scan-file').files[0];$('#scan-result').value='';$('#scan-open').hidden=true;if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024){$('#scan-status').textContent='请选择小于 20 MB 的 PNG、JPEG 或 WebP 图片。';return;}$('#scan-status').textContent='正在识别图片……';const url=URL.createObjectURL(file),image=new Image();try{await new Promise((res,rej)=>{image.onload=res;image.onerror=()=>rej(Error('无法读取图片'));image.src=url;});if(serial!==scanSerial)return;if(image.width*image.height>40000000)throw Error('图片过大，请缩小后再识别');const code=scanPixels(image,image.width,image.height);if(!code)throw Error('未识别到二维码，请使用清晰完整的图片');showScan(code.data);}catch(e){if(serial===scanSerial)$('#scan-status').textContent=e.message;}finally{URL.revokeObjectURL(url);}};
  $('#scan-copy').onclick=()=>copy('#scan-result','#scan-status');
  function stopIfAway(){if($('#page-tools').hidden||$('#tool-qr').hidden||$('#tools-workspace').hidden){scanSerial++;if(stream||$('#scan-camera').disabled)stopCamera(null);}}
  document.addEventListener('hub:selection',()=>queueMicrotask(stopIfAway));document.addEventListener('site:pagechange',()=>queueMicrotask(stopIfAway));document.addEventListener('visibilitychange',()=>{if(document.hidden&&(stream||$('#scan-camera').disabled))stopCamera('页面已隐藏，摄像头已关闭。');});window.addEventListener('pagehide',()=>stopCamera(null));
})();
