(function(root,factory){const value=factory();if(typeof module==='object'&&module.exports)module.exports=value;else root.UtilityLogic=value;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';const encoder=new TextEncoder(),decoder=new TextDecoder('utf-8',{fatal:true});
  function toBase64(bytes){let binary='';for(let start=0;start<bytes.length;start+=8192)binary+=String.fromCharCode(...bytes.subarray(start,start+8192));return btoa(binary);}
  function fromBase64(text){text=text.replace(/\s/g,'');if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(text))throw Error('Base64 格式不正确');return Uint8Array.from(atob(text),c=>c.charCodeAt(0));}
  async function derive(password,salt,subtle){const key=await subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},key,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
  async function process(mode,text,password='',cryptoImpl=globalThis.crypto){const limit=['base64-encode','aes-encrypt'].includes(mode)?500000:4000000;if(text.length>limit)throw Error('内容过长，请缩短文本后重试');if(!text)throw Error('请先输入内容');if(mode==='morse-encode'||mode==='morse-decode')return globalThis.PlusLogic.morse(text,mode==='morse-decode');if(mode==='base64-encode')return toBase64(encoder.encode(text));if(mode==='base64-decode')return decoder.decode(fromBase64(text));if(mode==='url-encode')return encodeURIComponent(text);if(mode==='url-decode')return decodeURIComponent(text);if(!cryptoImpl?.subtle)throw Error('此功能需要 HTTPS 或 localhost 环境');const subtle=cryptoImpl.subtle;if(mode==='sha256')return Array.from(new Uint8Array(await subtle.digest('SHA-256',encoder.encode(text))),b=>b.toString(16).padStart(2,'0')).join('');if(password.length<8)throw Error('加密口令至少需要 8 个字符');if(mode==='aes-encrypt'){const salt=cryptoImpl.getRandomValues(new Uint8Array(16)),iv=cryptoImpl.getRandomValues(new Uint8Array(12));const key=await derive(password,salt,subtle),data=await subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(text));return JSON.stringify({v:1,algorithm:'AES-256-GCM',kdf:'PBKDF2-SHA256',iterations:210000,salt:toBase64(salt),iv:toBase64(iv),data:toBase64(new Uint8Array(data))},null,2);}if(mode==='aes-decrypt'){try{const box=JSON.parse(text);if(box.v!==1||box.algorithm!=='AES-256-GCM'||box.kdf!=='PBKDF2-SHA256'||box.iterations!==210000)throw Error();const salt=fromBase64(box.salt),iv=fromBase64(box.iv),data=fromBase64(box.data);if(salt.length!==16||iv.length!==12||data.length<16)throw Error();const key=await derive(password,salt,subtle);return decoder.decode(await subtle.decrypt({name:'AES-GCM',iv},key,data));}catch{throw Error('解密失败：口令错误，或加密数据格式不正确');}}throw Error('未知处理方式');}
  const weatherNames={0:'晴',1:'大部晴朗',2:'局部多云',3:'阴',45:'雾',48:'冻雾',51:'小毛毛雨',53:'毛毛雨',55:'强毛毛雨',56:'冻毛毛雨',57:'强冻毛毛雨',61:'小雨',63:'中雨',65:'大雨',66:'冻雨',67:'强冻雨',71:'小雪',73:'中雪',75:'大雪',77:'雪粒',80:'小阵雨',81:'阵雨',82:'强阵雨',85:'阵雪',86:'强阵雪',95:'雷暴',96:'雷暴伴冰雹',99:'强雷暴伴冰雹'};
  return {toBase64,fromBase64,process,weatherName:code=>weatherNames[code]||'天气状态未知'};
});
