(() => {
  'use strict';const $=s=>document.querySelector(s),player=$('#video-player');let file=null,inputURL=null,outputURL=null,worker=null,busy=false,job=0,timer=null,knownDuration=null;
  function message(text){$('#video-status').textContent=text;}
  function clearResult(){if(outputURL)URL.revokeObjectURL(outputURL);outputURL=null;$('#video-result').hidden=true;$('#video-result-player').pause();$('#video-result-player').removeAttribute('src');$('#video-result-image').removeAttribute('src');$('#video-download').removeAttribute('href');$('#video-result-note').textContent='不同浏览器的播放格式支持不同；无法预览的文件可以下载后播放。';}
  function terminate(){worker?.terminate();worker=null;clearTimeout(timer);timer=null;}
  function controls(){busy?$('#video-convert').disabled=true:$('#video-convert').disabled=!file;$('#video-cancel').hidden=!busy;for(const e of document.querySelectorAll('#video-settings input,#video-settings select'))e.disabled=busy;$('#video-audio-options').hidden=$('#video-kind').value!=='audio';$('#video-picture-options').hidden=$('#video-kind').value==='audio';$('#video-time-options').hidden=!$('#video-range').checked;}
  function cancel(text='已取消转换。'){job++;busy=false;terminate();controls();if(text)message(text);}
  function formats(){const set=$('#video-kind').value==='audio'?AudioConvertLogic.formats:VideoLogic.formats;$('#video-format').replaceChildren(...Object.entries(set).map(([key,f])=>{const o=document.createElement('option');o.value=key;o.textContent=f.title;return o;}));controls();}
  $('#video-kind').onchange=()=>{clearResult();formats();};$('#video-range').onchange=controls;
  $('#video-format').addEventListener('change',()=>{if($('#video-kind').value==='video'&&$('#video-format').value==='mpg'){$('#video-fps').value='25';message('MPEG 输出固定为 25 fps，其余格式可以选择帧率。');}if($('#video-kind').value==='video'&&$('#video-format').value==='gif')$('#video-fps').value='12';});
  for(const e of document.querySelectorAll('#video-settings input,#video-settings select'))e.addEventListener('change',()=>{if(!busy)clearResult();});
  async function load(next){cancel('');clearResult();if(inputURL)URL.revokeObjectURL(inputURL);inputURL=null;file=null;knownDuration=null;player.pause();player.removeAttribute('src');$('#video-info').textContent='';$('#video-start').value=0;$('#video-end').value='';$('#video-range').checked=false;controls();if(!next)return;if(next.size>120*1024*1024){message('请选择不超过 120 MB 的视频。');return;}if(!next.size){message('该文件为空。');return;}file=next;inputURL=URL.createObjectURL(file);player.src=inputURL;player.load();$('#video-info').textContent=file.name+' · '+(file.size/1024/1024).toFixed(1)+' MB';message('文件已打开。浏览器不能播放的格式也可尝试转换。');controls();}
  $('#video-file').onchange=()=>load($('#video-file').files[0]);player.addEventListener('loadedmetadata',()=>{if(!file)return;if(Number.isFinite(player.duration)){knownDuration=player.duration;$('#video-end').value=player.duration.toFixed(2);$('#video-info').textContent=file.name+' · '+player.videoWidth+' × '+player.videoHeight+' · '+player.duration.toFixed(1)+' 秒';}});player.addEventListener('error',()=>{if(file&&!busy)message('浏览器无法直接播放此格式，可以尝试转换为 MP4 或 WebM。');});
  $('#video-volume').oninput=()=>{player.volume=Number($('#video-volume').value)/100;player.muted=player.volume===0;};$('#video-rate').onchange=()=>player.playbackRate=Number($('#video-rate').value);$('#video-fullscreen').onclick=()=>{const action=player.requestFullscreen||player.webkitEnterFullscreen;if(action)Promise.resolve(action.call(player)).catch(()=>message('浏览器未允许全屏'));else message('当前浏览器请使用播放器自带的全屏按钮。');};
  function arm(ms,text){clearTimeout(timer);timer=setTimeout(()=>cancel(text),ms);}
  $('#video-convert').onclick=async()=>{if(!file||busy)return;let options;try{options=VideoLogic.settings({kind:$('#video-kind').value,format:$('#video-format').value,height:$('#video-height').value,fps:$('#video-fps').value,quality:Number($('#video-quality').value),bitrate:Number($('#video-bitrate').value),range:$('#video-range').checked,start:Number($('#video-start').value),end:$('#video-end').value});if(knownDuration>600)throw Error('请选择 10 分钟以内的视频');}catch(e){message(e.message);return;}const id=++job,source=file;busy=true;clearResult();controls();$('#video-progress').value=0;message('正在准备转换核心（首次约下载 31 MB）……');arm(120000,'核心下载超时，请检查网络后重试。');
    try{const bytes=new Uint8Array(await source.arrayBuffer());if(id!==job)return;if(!worker)worker=new Worker('video-worker.js?v=9f43c3f90906');worker.onmessage=({data})=>{if(id!==job||data.id!==id||!busy)return;if(data.type==='loading'){message('正在加载转换核心……');}
      if(data.type==='metadata'){if(data.duration)knownDuration=data.duration;}
      if(data.type==='encoding'){message('正在转换，视频较大时可能需要几分钟……');arm(15*60*1000,'转换耗时过长，已停止。请缩短片段或降低分辨率。');}
      if(data.type==='progress'){$('#video-progress').value=data.percent;message('正在转换 · '+data.percent+'%');}
      if(data.type==='error'){cancel(data.message);}
      if(data.type==='done'){busy=false;clearTimeout(timer);timer=null;outputURL=URL.createObjectURL(new Blob([data.bytes],{type:data.mime}));const download=$('#video-download');download.href=outputURL;download.download=source.name.replace(/\.[^.]*$/,'')+'-'+(options.kind==='audio'?'audio':'converted')+'.'+data.ext;$('#video-result').hidden=false;const result=$('#video-result-player'),image=$('#video-result-image');result.hidden=data.ext==='gif';image.hidden=data.ext!=='gif';if(data.ext==='gif')image.src=outputURL;else{result.src=outputURL;result.load();}$('#video-progress').value=100;message('转换完成 · '+(data.bytes.length/1024/1024).toFixed(2)+' MB；可下载保存。');controls();}}
    worker.onerror=()=>cancel('转换核心无法运行，请尝试较小文件或更新浏览器。');worker.postMessage({id,bytes,extension:source.name.split('.').pop(),options},[bytes.buffer]);}catch(e){if(id===job)cancel('无法开始转换：'+e.message);}};
  $('#video-cancel').onclick=()=>cancel();$('#video-result-player').addEventListener('error',()=>{if(outputURL)$('#video-result-note').textContent='当前浏览器无法预览这个输出格式，可以下载后使用支持该格式的播放器。';});
  const panel=$('#tool-video');panel.addEventListener('dragover',e=>e.preventDefault());panel.addEventListener('drop',e=>{e.preventDefault();load(e.dataTransfer.files[0]);});
  window.addEventListener('hashchange',()=>{if(location.hash!=='#tools/video'){player.pause();$('#video-result-player').pause();if(busy)cancel('已停止转换；返回工具后可重试。');else terminate();}});window.addEventListener('pagehide',()=>{cancel('');clearResult();if(inputURL)URL.revokeObjectURL(inputURL);});formats();controls();
})();
